export type CompactLesson = {
  slug: string;
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  moduleSlug: string;
  sortOrder: number;
  estimatedMinutes: number;
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  skillSlug: string;
  learningObjective: "IDENTIFY" | "APPLY" | "ANALYZE" | "DECIDE";
  isShort?: boolean;
  shortTopic?: string;
  shortDurationSeconds?: number;
  textBodyFr: string;
  textBodyEn: string;
  flashcardFrontFr: string;
  flashcardFrontEn: string;
  flashcardBackFr: string;
  flashcardBackEn: string;
  exercisePromptFr: string;
  exercisePromptEn: string;
  question: {
    type: "SINGLE_CHOICE" | "TRUE_FALSE" | "MULTIPLE_CHOICE";
    promptFr: string;
    promptEn: string;
    explanationCorrectFr: string;
    explanationCorrectEn: string;
    difficulty: number;
    options: Array<{ labelFr: string; labelEn: string; isCorrect: boolean }>;
  };
};

export const CF_MODULES = [
  { slug: "financial-statements", titleFr: "États financiers", titleEn: "Financial Statements", category: "FINANCIAL_STATEMENTS", sortOrder: 0 },
  { slug: "working-capital", titleFr: "Besoin en fonds de roulement", titleEn: "Working Capital", category: "WORKING_CAPITAL", sortOrder: 1 },
  { slug: "valuation", titleFr: "Valorisation", titleEn: "Valuation", category: "VALUATION", sortOrder: 2 },
  { slug: "dcf", titleFr: "DCF", titleEn: "DCF", category: "DCF", sortOrder: 3 },
  { slug: "ma-basics", titleFr: "Bases M&A", titleEn: "M&A Basics", category: "MA_BASICS", sortOrder: 4 },
];

export const CF_LESSONS: CompactLesson[] = [
  {
    slug: "income-statement",
    titleFr: "Compte de résultat",
    titleEn: "Income Statement",
    descriptionFr: "Comprenez le compte de résultat et la performance d'une entreprise.",
    descriptionEn: "Understand the income statement and company performance.",
    moduleSlug: "financial-statements",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-foundations",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le compte de résultat mesure la performance sur une période : revenus, coûts et résultat net. Il commence par le chiffre d'affaires et déduit les charges pour arriver au bénéfice ou la perte. Contrairement au bilan, il couvre une période (trimestre, année). C'est un outil d'analyse pédagogique, pas un audit financier.",
    textBodyEn: "The income statement measures performance over a period: revenue, costs, and net result. It starts with sales and deducts expenses to reach profit or loss. Unlike the balance sheet, it covers a period (quarter, year). It is a pedagogical analysis tool, not a financial audit.",
    flashcardFrontFr: "Compte de résultat",
    flashcardFrontEn: "Income statement",
    flashcardBackFr: "État qui mesure la performance sur une période.",
    flashcardBackEn: "Statement measuring performance over a period.",
    exercisePromptFr: "Nommez les trois grandes lignes d'un compte de résultat.",
    exercisePromptEn: "Name the three main lines of an income statement.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel état mesure la performance sur une période ?",
      promptEn: "Which statement measures performance over a period?",
      explanationCorrectFr: "Le compte de résultat couvre une période et mesure le résultat.",
      explanationCorrectEn: "The income statement covers a period and measures results.",
      difficulty: 1,
      options: [
        { labelFr: "Le bilan", labelEn: "Balance sheet", isCorrect: false },
        { labelFr: "Le compte de résultat", labelEn: "Income statement", isCorrect: true },
        { labelFr: "Le budget", labelEn: "Budget", isCorrect: false },
      ],
    },
  },
  {
    slug: "balance-sheet",
    titleFr: "Bilan",
    titleEn: "Balance Sheet",
    descriptionFr: "Découvrez le bilan et l'équation fondamentale actif = passif + capitaux propres.",
    descriptionEn: "Discover the balance sheet and assets = liabilities + equity.",
    moduleSlug: "financial-statements",
    sortOrder: 1,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-foundations",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le bilan présente la situation financière à une date précise. L'équation fondamentale est Actifs = Passifs + Capitaux propres. Les actifs sont ce que l'entreprise possède ; les passifs ce qu'elle doit. Les capitaux propres représentent la valeur nette pour les actionnaires.",
    textBodyEn: "The balance sheet shows financial position at a specific date. The fundamental equation is Assets = Liabilities + Equity. Assets are what the company owns; liabilities what it owes. Equity represents net value for shareholders.",
    flashcardFrontFr: "Bilan",
    flashcardFrontEn: "Balance sheet",
    flashcardBackFr: "Actifs = Passifs + Capitaux propres à une date donnée.",
    flashcardBackEn: "Assets = Liabilities + Equity at a point in time.",
    exercisePromptFr: "Expliquez l'équation fondamentale du bilan.",
    exercisePromptEn: "Explain the balance sheet fundamental equation.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Le bilan présente la situation à une date précise.",
      promptEn: "The balance sheet shows position at a specific date.",
      explanationCorrectFr: "Vrai. Le bilan est une photo à une date, pas une période.",
      explanationCorrectEn: "True. The balance sheet is a snapshot at a date, not a period.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "cash-flow-statement",
    titleFr: "Tableau de flux de trésorerie",
    titleEn: "Cash Flow Statement",
    descriptionFr: "Comprenez les flux d'exploitation, d'investissement et de financement.",
    descriptionEn: "Understand operating, investing, and financing cash flows.",
    moduleSlug: "financial-statements",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "cf-cash-flow",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le tableau de flux de trésorerie montre les mouvements de cash sur une période. Il se divise en trois sections : exploitation (activité courante), investissement (CAPEX, acquisitions) et financement (dettes, dividendes). Le résultat comptable peut différer du cash réel — c'est pourquoi ce tableau est essentiel.",
    textBodyEn: "The cash flow statement shows cash movements over a period. It divides into three sections: operating (core activity), investing (CAPEX, acquisitions), and financing (debt, dividends). Accounting profit can differ from real cash — why this statement is essential.",
    flashcardFrontFr: "Flux d'exploitation",
    flashcardFrontEn: "Operating cash flow",
    flashcardBackFr: "Cash généré par l'activité opérationnelle courante.",
    flashcardBackEn: "Cash generated by core operating activity.",
    exercisePromptFr: "Classez ces flux : paiement fournisseurs, achat d'usine, émission d'obligations.",
    exercisePromptEn: "Classify: supplier payment, plant purchase, bond issuance.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "L'achat d'une usine apparaît typiquement dans quel flux ?",
      promptEn: "Buying a plant typically appears in which cash flow?",
      explanationCorrectFr: "L'achat d'actifs productifs est un flux d'investissement.",
      explanationCorrectEn: "Buying productive assets is an investing cash flow.",
      difficulty: 2,
      options: [
        { labelFr: "Exploitation", labelEn: "Operating", isCorrect: false },
        { labelFr: "Investissement", labelEn: "Investing", isCorrect: true },
        { labelFr: "Financement", labelEn: "Financing", isCorrect: false },
      ],
    },
  },
  {
    slug: "revenue-basics",
    titleFr: "Bases du revenu",
    titleEn: "Revenue Basics",
    descriptionFr: "Comprenez le chiffre d'affaires et sa reconnaissance.",
    descriptionEn: "Understand revenue and its recognition.",
    moduleSlug: "financial-statements",
    sortOrder: 3,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-foundations",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le revenu (chiffre d'affaires) est la première ligne du compte de résultat. Il représente les ventes de produits ou services. La reconnaissance du revenu suit des règles comptables (livraison, service rendu). Le revenu ne signifie pas cash : une vente à crédit génère du revenu sans cash immédiat.",
    textBodyEn: "Revenue (sales) is the first line of the income statement. It represents product or service sales. Revenue recognition follows accounting rules (delivery, service rendered). Revenue is not cash: credit sales generate revenue without immediate cash.",
    flashcardFrontFr: "Chiffre d'affaires",
    flashcardFrontEn: "Revenue",
    flashcardBackFr: "Première ligne du compte de résultat : ventes totales.",
    flashcardBackEn: "First income statement line: total sales.",
    exercisePromptFr: "Expliquez la différence entre revenu et cash perçu.",
    exercisePromptEn: "Explain the difference between revenue and cash received.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Le revenu comptable peut différer du cash perçu.",
      promptEn: "Accounting revenue can differ from cash received.",
      explanationCorrectFr: "Vrai. Les ventes à crédit génèrent du revenu sans cash immédiat.",
      explanationCorrectEn: "True. Credit sales generate revenue without immediate cash.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "ebitda-basics",
    titleFr: "Bases de l'EBITDA",
    titleEn: "EBITDA Basics",
    descriptionFr: "Découvrez l'EBITDA et son usage en analyse financière.",
    descriptionEn: "Discover EBITDA and its use in financial analysis.",
    moduleSlug: "financial-statements",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "cf-foundations",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "ebitda",
    shortDurationSeconds: 145,
    textBodyFr: "L'EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization) approxime le résultat opérationnel avant intérêts, impôts, dépréciation et amortissement. Il est utile pour comparer des entreprises avec des structures différentes. C'est une mesure pédagogique, pas un substitut du cash flow réel.",
    textBodyEn: "EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization) approximates operating result before interest, taxes, depreciation, and amortization. It helps compare companies with different structures. It is a pedagogical measure, not a substitute for real cash flow.",
    flashcardFrontFr: "EBITDA",
    flashcardFrontEn: "EBITDA",
    flashcardBackFr: "Résultat avant intérêts, impôts, dépréciation et amortissement.",
    flashcardBackEn: "Earnings before interest, taxes, depreciation, and amortization.",
    exercisePromptFr: "Placez l'EBITDA dans la cascade du compte de résultat.",
    exercisePromptEn: "Place EBITDA in the income statement cascade.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'EBITDA exclut la dépréciation et l'amortissement.",
      promptEn: "EBITDA excludes depreciation and amortization.",
      explanationCorrectFr: "Vrai. D&A sont explicitement exclus de l'EBITDA.",
      explanationCorrectEn: "True. D&A are explicitly excluded from EBITDA.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "ebit-basics",
    titleFr: "Bases de l'EBIT",
    titleEn: "EBIT Basics",
    descriptionFr: "Comprenez l'EBIT et sa place dans l'analyse de performance.",
    descriptionEn: "Understand EBIT and its place in performance analysis.",
    moduleSlug: "financial-statements",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-foundations",
    learningObjective: "ANALYZE",
    textBodyFr: "L'EBIT (Earnings Before Interest and Taxes) est le résultat opérationnel après dépréciation et amortissement. Il se situe entre l'EBITDA et le résultat net. L'EBIT reflète la performance opérationnelle en tenant compte de la dépréciation des actifs — mesure pédagogique pour comparer des entreprises.",
    textBodyEn: "EBIT (Earnings Before Interest and Taxes) is operating profit after depreciation and amortization. It sits between EBITDA and net income. EBIT reflects operating performance including asset depreciation — pedagogical measure for comparing companies.",
    flashcardFrontFr: "EBIT",
    flashcardFrontEn: "EBIT",
    flashcardBackFr: "Résultat opérationnel après D&A, avant intérêts et impôts.",
    flashcardBackEn: "Operating profit after D&A, before interest and taxes.",
    exercisePromptFr: "Comparez EBIT et EBITDA sur un exemple simple.",
    exercisePromptEn: "Compare EBIT and EBITDA on a simple example.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "L'EBIT est calculé…",
      promptEn: "EBIT is calculated…",
      explanationCorrectFr: "Après dépréciation et amortissement, avant intérêts et impôts.",
      explanationCorrectEn: "After depreciation and amortization, before interest and taxes.",
      difficulty: 2,
      options: [
        { labelFr: "Après D&A, avant intérêts et impôts", labelEn: "After D&A, before interest and taxes", isCorrect: true },
        { labelFr: "Avant toute charge", labelEn: "Before any expense", isCorrect: false },
        { labelFr: "Après impôts", labelEn: "After taxes", isCorrect: false },
      ],
    },
  },
  {
    slug: "net-income",
    titleFr: "Résultat net",
    titleEn: "Net Income",
    descriptionFr: "Comprenez le résultat net et sa signification pour les actionnaires.",
    descriptionEn: "Understand net income and its meaning for shareholders.",
    moduleSlug: "financial-statements",
    sortOrder: 6,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-foundations",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le résultat net est la dernière ligne du compte de résultat : revenus moins toutes les charges, intérêts et impôts. Il représente le profit disponible pour les actionnaires. Le BPA (bénéfice par action) divise le résultat net par le nombre d'actions. Le résultat net ne reflète pas directement le cash disponible.",
    textBodyEn: "Net income is the last income statement line: revenue minus all expenses, interest, and taxes. It represents profit available to shareholders. EPS (earnings per share) divides net income by share count. Net income does not directly reflect available cash.",
    flashcardFrontFr: "Résultat net",
    flashcardFrontEn: "Net income",
    flashcardBackFr: "Profit après toutes charges, intérêts et impôts.",
    flashcardBackEn: "Profit after all expenses, interest, and taxes.",
    exercisePromptFr: "Calculez le BPA avec un résultat net de 10 M€ et 5 M actions.",
    exercisePromptEn: "Calculate EPS with €10M net income and 5M shares.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Le BPA est calculé comme…",
      promptEn: "EPS is calculated as…",
      explanationCorrectFr: "Résultat net divisé par le nombre d'actions.",
      explanationCorrectEn: "Net income divided by number of shares.",
      difficulty: 2,
      options: [
        { labelFr: "Résultat net ÷ actions", labelEn: "Net income ÷ shares", isCorrect: true },
        { labelFr: "Revenu ÷ actifs", labelEn: "Revenue ÷ assets", isCorrect: false },
        { labelFr: "EBITDA ÷ dette", labelEn: "EBITDA ÷ debt", isCorrect: false },
      ],
    },
  },
  {
    slug: "accounts-receivable",
    titleFr: "Créances clients",
    titleEn: "Accounts Receivable",
    descriptionFr: "Comprenez les créances clients et leur impact sur le cash.",
    descriptionEn: "Understand accounts receivable and their cash impact.",
    moduleSlug: "working-capital",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-cash-flow",
    learningObjective: "IDENTIFY",
    textBodyFr: "Les créances clients représentent l'argent dû par les clients pour des ventes déjà facturées. Une hausse des créances consomme du cash : l'entreprise a vendu mais n'a pas encore été payée. Le délai de recouvrement (DSO) mesure la rapidité de collecte — indicateur pédagogique de gestion du BFR.",
    textBodyEn: "Accounts receivable represent money owed by customers for already invoiced sales. Rising receivables consume cash: the company sold but has not been paid yet. Days Sales Outstanding (DSO) measures collection speed — pedagogical working capital indicator.",
    flashcardFrontFr: "Créances clients",
    flashcardFrontEn: "Accounts receivable",
    flashcardBackFr: "Montants dus par les clients pour ventes facturées.",
    flashcardBackEn: "Amounts owed by customers for invoiced sales.",
    exercisePromptFr: "Expliquez pourquoi une hausse des créances réduit le cash.",
    exercisePromptEn: "Explain why rising receivables reduce cash.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Une hausse des créances clients consomme du cash.",
      promptEn: "Rising accounts receivable consumes cash.",
      explanationCorrectFr: "Vrai. L'entreprise vend mais n'a pas encore été payée.",
      explanationCorrectEn: "True. The company sold but has not been paid yet.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "accounts-payable",
    titleFr: "Dettes fournisseurs",
    titleEn: "Accounts Payable",
    descriptionFr: "Découvrez les dettes fournisseurs et leur effet sur le BFR.",
    descriptionEn: "Discover accounts payable and their working capital effect.",
    moduleSlug: "working-capital",
    sortOrder: 1,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-cash-flow",
    learningObjective: "IDENTIFY",
    textBodyFr: "Les dettes fournisseurs représentent l'argent dû aux fournisseurs pour des achats non encore payés. Une hausse des dettes fournisseurs libère du cash : l'entreprise a acheté mais n'a pas encore payé. Le délai de paiement (DPO) mesure cette pratique — outil de gestion du BFR, pas une recommandation de retard de paiement.",
    textBodyEn: "Accounts payable represent money owed to suppliers for unpaid purchases. Rising payables release cash: the company bought but has not paid yet. Days Payable Outstanding (DPO) measures this practice — working capital tool, not a late payment recommendation.",
    flashcardFrontFr: "Dettes fournisseurs",
    flashcardFrontEn: "Accounts payable",
    flashcardBackFr: "Montants dus aux fournisseurs pour achats non payés.",
    flashcardBackEn: "Amounts owed to suppliers for unpaid purchases.",
    exercisePromptFr: "Expliquez pourquoi une hausse des dettes fournisseurs libère du cash.",
    exercisePromptEn: "Explain why rising payables release cash.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Une hausse des dettes fournisseurs libère généralement du cash.",
      promptEn: "Rising accounts payable generally releases cash.",
      explanationCorrectFr: "Vrai. L'entreprise a acheté mais n'a pas encore payé.",
      explanationCorrectEn: "True. The company bought but has not paid yet.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "inventory-basics",
    titleFr: "Bases des stocks",
    titleEn: "Inventory Basics",
    descriptionFr: "Comprenez les stocks et leur impact sur le besoin en fonds de roulement.",
    descriptionEn: "Understand inventory and its working capital impact.",
    moduleSlug: "working-capital",
    sortOrder: 2,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-cash-flow",
    learningObjective: "ANALYZE",
    textBodyFr: "Les stocks représentent les produits achetés ou fabriqués mais pas encore vendus. Une hausse des stocks consomme du cash : l'entreprise a investi dans des produits non vendus. Le délai de rotation des stocks (DIO) mesure la vitesse de vente — indicateur de gestion opérationnelle pédagogique.",
    textBodyEn: "Inventory represents products purchased or manufactured but not yet sold. Rising inventory consumes cash: the company invested in unsold products. Days Inventory Outstanding (DIO) measures sales speed — pedagogical operational management indicator.",
    flashcardFrontFr: "Stocks",
    flashcardFrontEn: "Inventory",
    flashcardBackFr: "Produits achetés ou fabriqués non encore vendus.",
    flashcardBackEn: "Products purchased or manufactured not yet sold.",
    exercisePromptFr: "Expliquez pourquoi une hausse des stocks réduit le cash.",
    exercisePromptEn: "Explain why rising inventory reduces cash.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Une hausse des stocks consomme généralement du cash.",
      promptEn: "Rising inventory generally consumes cash.",
      explanationCorrectFr: "Vrai. L'entreprise a investi dans des produits non vendus.",
      explanationCorrectEn: "True. The company invested in unsold products.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "working-capital",
    titleFr: "Besoin en fonds de roulement",
    titleEn: "Working Capital",
    descriptionFr: "Calculez et interprétez le besoin en fonds de roulement (BFR).",
    descriptionEn: "Calculate and interpret working capital.",
    moduleSlug: "working-capital",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-cash-flow",
    learningObjective: "ANALYZE",
    textBodyFr: "Le besoin en fonds de roulement (BFR) mesure le cash immobilisé dans le cycle d'exploitation : stocks + créances − dettes fournisseurs. Un BFR élevé signale plus de cash bloqué dans l'activité. Une hausse du BFR consomme du cash même si le résultat comptable est positif — concept pédagogique clé en finance d'entreprise.",
    textBodyEn: "Working capital measures cash tied in the operating cycle: inventory + receivables − payables. High working capital signals more cash locked in operations. Rising working capital consumes cash even when accounting profit is positive — key pedagogical concept in corporate finance.",
    flashcardFrontFr: "BFR",
    flashcardFrontEn: "Working capital",
    flashcardBackFr: "Stocks + créances − dettes fournisseurs.",
    flashcardBackEn: "Inventory + receivables − payables.",
    exercisePromptFr: "Calculez le BFR avec stocks 50, créances 80, dettes fournisseurs 40.",
    exercisePromptEn: "Calculate WC with inventory 50, receivables 80, payables 40.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Le BFR est calculé comme…",
      promptEn: "Working capital is calculated as…",
      explanationCorrectFr: "Stocks + créances clients − dettes fournisseurs.",
      explanationCorrectEn: "Inventory + receivables − payables.",
      difficulty: 2,
      options: [
        { labelFr: "Stocks + créances − dettes fournisseurs", labelEn: "Inventory + receivables − payables", isCorrect: true },
        { labelFr: "Revenu − coûts", labelEn: "Revenue − costs", isCorrect: false },
        { labelFr: "Actifs − passifs totaux", labelEn: "Assets − total liabilities", isCorrect: false },
      ],
    },
  },
  {
    slug: "cash-conversion-cycle",
    titleFr: "Cycle de conversion du cash",
    titleEn: "Cash Conversion Cycle",
    descriptionFr: "Mesurez le délai entre l'investissement et le recouvrement du cash.",
    descriptionEn: "Measure the delay between investment and cash recovery.",
    moduleSlug: "working-capital",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-cash-flow",
    learningObjective: "ANALYZE",
    textBodyFr: "Le cycle de conversion du cash (CCC) combine DIO + DSO − DPO. Il mesure le nombre de jours entre l'achat de matières et le recouvrement du cash des ventes. Un CCC court signale une gestion efficace du BFR. C'est un indicateur de gestion opérationnelle, pas une norme universelle.",
    textBodyEn: "Cash Conversion Cycle (CCC) combines DIO + DSO − DPO. It measures days between buying materials and recovering sales cash. A short CCC signals efficient working capital management. It is an operational management indicator, not a universal standard.",
    flashcardFrontFr: "Cycle de conversion du cash",
    flashcardFrontEn: "Cash conversion cycle",
    flashcardBackFr: "DIO + DSO − DPO (jours).",
    flashcardBackEn: "DIO + DSO − DPO (days).",
    exercisePromptFr: "Calculez le CCC avec DIO 30, DSO 45, DPO 20.",
    exercisePromptEn: "Calculate CCC with DIO 30, DSO 45, DPO 20.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Le CCC est calculé comme…",
      promptEn: "CCC is calculated as…",
      explanationCorrectFr: "DIO + DSO − DPO.",
      explanationCorrectEn: "DIO + DSO − DPO.",
      difficulty: 2,
      options: [
        { labelFr: "DIO + DSO − DPO", labelEn: "DIO + DSO − DPO", isCorrect: true },
        { labelFr: "DSO + DPO − DIO", labelEn: "DSO + DPO − DIO", isCorrect: false },
        { labelFr: "Revenu ÷ actifs", labelEn: "Revenue ÷ assets", isCorrect: false },
      ],
    },
  },
  {
    slug: "enterprise-value",
    titleFr: "Enterprise Value",
    titleEn: "Enterprise Value",
    descriptionFr: "Comprenez l'Enterprise Value et sa signification.",
    descriptionEn: "Understand Enterprise Value and its meaning.",
    moduleSlug: "valuation",
    sortOrder: 0,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "enterprise-value",
    shortDurationSeconds: 160,
    textBodyFr: "L'Enterprise Value (EV) représente la valeur de l'activité opérationnelle pour tous les fournisseurs de capital (actionnaires et créanciers). EV = Equity Value + dette nette (simplifié). Elle est utilisée pour les multiples EV/EBITDA et les analyses DCF — mesure pédagogique, pas une valorisation professionnelle.",
    textBodyEn: "Enterprise Value (EV) represents operating business value for all capital providers (shareholders and creditors). EV = Equity Value + net debt (simplified). Used for EV/EBITDA multiples and DCF analyses — pedagogical measure, not a professional valuation.",
    flashcardFrontFr: "Enterprise Value",
    flashcardFrontEn: "Enterprise Value",
    flashcardBackFr: "Valeur de l'entreprise pour dette + equity.",
    flashcardBackEn: "Firm value for debt + equity.",
    exercisePromptFr: "Calculez l'EV avec Equity Value 500 M€ et dette nette 200 M€.",
    exercisePromptEn: "Calculate EV with Equity Value €500M and net debt €200M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "L'EV inclut typiquement…",
      promptEn: "EV typically includes…",
      explanationCorrectFr: "La valeur pour actionnaires et créanciers (dette + equity).",
      explanationCorrectEn: "Value for shareholders and creditors (debt + equity).",
      difficulty: 2,
      options: [
        { labelFr: "Dette + equity", labelEn: "Debt + equity", isCorrect: true },
        { labelFr: "Uniquement les dividendes", labelEn: "Only dividends", isCorrect: false },
        { labelFr: "Uniquement le cash", labelEn: "Only cash", isCorrect: false },
      ],
    },
  },
  {
    slug: "equity-value",
    titleFr: "Equity Value",
    titleEn: "Equity Value",
    descriptionFr: "Découvrez la valeur des capitaux propres pour les actionnaires.",
    descriptionEn: "Discover equity value for shareholders.",
    moduleSlug: "valuation",
    sortOrder: 1,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "IDENTIFY",
    textBodyFr: "L'Equity Value est la valeur pour les actionnaires uniquement : capitalisation boursière pour une société cotée, ou valeur des parts pour une société privée. Equity Value = EV − dette nette. Les multiples P/E et P/B utilisent l'Equity Value — distinction pédagogique essentielle en valorisation.",
    textBodyEn: "Equity Value is value for shareholders only: market cap for listed companies, or share value for private firms. Equity Value = EV − net debt. P/E and P/B multiples use Equity Value — essential pedagogical distinction in valuation.",
    flashcardFrontFr: "Equity Value",
    flashcardFrontEn: "Equity Value",
    flashcardBackFr: "Valeur pour les actionnaires uniquement.",
    flashcardBackEn: "Value for shareholders only.",
    exercisePromptFr: "Calculez l'Equity Value avec EV 700 M€ et dette nette 200 M€.",
    exercisePromptEn: "Calculate Equity Value with EV €700M and net debt €200M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Equity Value = EV −…",
      promptEn: "Equity Value = EV −…",
      explanationCorrectFr: "Dette nette.",
      explanationCorrectEn: "Net debt.",
      difficulty: 2,
      options: [
        { labelFr: "Dette nette", labelEn: "Net debt", isCorrect: true },
        { labelFr: "Revenu total", labelEn: "Total revenue", isCorrect: false },
        { labelFr: "EBITDA", labelEn: "EBITDA", isCorrect: false },
      ],
    },
  },
  {
    slug: "net-debt",
    titleFr: "Dette nette",
    titleEn: "Net Debt",
    descriptionFr: "Calculez la dette nette et son rôle dans la valorisation.",
    descriptionEn: "Calculate net debt and its role in valuation.",
    moduleSlug: "valuation",
    sortOrder: 2,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "La dette nette = dettes financières − cash et équivalents. Elle relie l'EV et l'Equity Value. Une entreprise avec beaucoup de cash peut avoir une dette nette négative (cash net). Toujours vérifier la cohérence EV vs Equity lors d'une analyse — règle pédagogique fondamentale.",
    textBodyEn: "Net debt = financial debt − cash and equivalents. It links EV and Equity Value. A company with much cash may have negative net debt (net cash). Always verify EV vs Equity consistency in analysis — fundamental pedagogical rule.",
    flashcardFrontFr: "Dette nette",
    flashcardFrontEn: "Net debt",
    flashcardBackFr: "Dettes financières − cash et équivalents.",
    flashcardBackEn: "Financial debt − cash and equivalents.",
    exercisePromptFr: "Calculez la dette nette avec dettes 300 M€ et cash 80 M€.",
    exercisePromptEn: "Calculate net debt with debt €300M and cash €80M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Dette nette =…",
      promptEn: "Net debt =…",
      explanationCorrectFr: "Dettes financières − cash et équivalents.",
      explanationCorrectEn: "Financial debt − cash and equivalents.",
      difficulty: 2,
      options: [
        { labelFr: "Dettes − cash", labelEn: "Debt − cash", isCorrect: true },
        { labelFr: "Revenu − coûts", labelEn: "Revenue − costs", isCorrect: false },
        { labelFr: "EV − Equity Value", labelEn: "EV − Equity Value", isCorrect: false },
      ],
    },
  },
  {
    slug: "trading-multiples",
    titleFr: "Multiples de trading",
    titleEn: "Trading Multiples",
    descriptionFr: "Utilisez les multiples de sociétés cotées comparables.",
    descriptionEn: "Use multiples from comparable listed companies.",
    moduleSlug: "valuation",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "ANALYZE",
    textBodyFr: "Les multiples de trading comparent des sociétés cotées similaires (comps). Exemples : EV/EBITDA, P/E. Ils reflètent le marché public et sont mis à jour quotidiennement. La qualité des pairs comparables est cruciale — jamais une vérité unique, toujours un outil de triangulation pédagogique.",
    textBodyEn: "Trading multiples compare similar listed companies (comps). Examples: EV/EBITDA, P/E. They reflect the public market and update daily. Comparable peer quality is crucial — never a single truth, always a pedagogical triangulation tool.",
    flashcardFrontFr: "Multiple EV/EBITDA",
    flashcardFrontEn: "EV/EBITDA multiple",
    flashcardBackFr: "Enterprise Value divisé par EBITDA.",
    flashcardBackEn: "Enterprise Value divided by EBITDA.",
    exercisePromptFr: "Citez deux multiples de trading courants.",
    exercisePromptEn: "Name two common trading multiples.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Les multiples de trading reflètent…",
      promptEn: "Trading multiples reflect…",
      explanationCorrectFr: "Le marché public des sociétés cotées comparables.",
      explanationCorrectEn: "The public market of comparable listed companies.",
      difficulty: 2,
      options: [
        { labelFr: "Le marché public coté", labelEn: "Listed public market", isCorrect: true },
        { labelFr: "Les transactions M&A privées", labelEn: "Private M&A transactions", isCorrect: false },
        { labelFr: "Le budget de l'entreprise", labelEn: "Company budget", isCorrect: false },
      ],
    },
  },
  {
    slug: "transaction-multiples",
    titleFr: "Multiples de transaction",
    titleEn: "Transaction Multiples",
    descriptionFr: "Analysez les multiples des transactions M&A.",
    descriptionEn: "Analyze multiples from M&A transactions.",
    moduleSlug: "valuation",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "ANALYZE",
    textBodyFr: "Les multiples de transaction reflètent les prix payés dans les deals M&A. Ils incluent souvent une prime de contrôle par rapport aux multiples de trading. Utiles pour estimer une valeur en contexte d'acquisition — outil de triangulation, pas une valorisation définitive.",
    textBodyEn: "Transaction multiples reflect prices paid in M&A deals. They often include a control premium over trading multiples. Useful for estimating value in acquisition context — triangulation tool, not a definitive valuation.",
    flashcardFrontFr: "Prime de contrôle",
    flashcardFrontEn: "Control premium",
    flashcardBackFr: "Surcote fréquente dans les multiples de transaction M&A.",
    flashcardBackEn: "Uplift often seen in M&A transaction multiples.",
    exercisePromptFr: "Comparez un multiple de trading et un multiple de transaction.",
    exercisePromptEn: "Compare a trading multiple and a transaction multiple.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Les multiples de transaction incluent souvent une prime de contrôle.",
      promptEn: "Transaction multiples often include a control premium.",
      explanationCorrectFr: "Vrai. Les deals M&A paient souvent pour le contrôle.",
      explanationCorrectEn: "True. M&A deals often pay for control.",
      difficulty: 2,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "ev-revenue",
    titleFr: "Multiple EV/Revenu",
    titleEn: "EV/Revenue Multiple",
    descriptionFr: "Utilisez le multiple EV/Revenu pour valoriser des entreprises.",
    descriptionEn: "Use the EV/Revenue multiple to value companies.",
    moduleSlug: "valuation",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "Le multiple EV/Revenu compare l'Enterprise Value au chiffre d'affaires. Utile pour les entreprises en croissance ou non rentables. Un EV/Revenu de 5x signifie que l'EV vaut 5 fois le revenu annuel. Comparez toujours des entreprises similaires — mesure pédagogique, pas une recommandation d'investissement.",
    textBodyEn: "EV/Revenue multiple compares Enterprise Value to revenue. Useful for growth or unprofitable companies. EV/Revenue of 5x means EV is 5 times annual revenue. Always compare similar companies — pedagogical measure, not an investment recommendation.",
    flashcardFrontFr: "EV/Revenu",
    flashcardFrontEn: "EV/Revenue",
    flashcardBackFr: "Enterprise Value divisé par le chiffre d'affaires.",
    flashcardBackEn: "Enterprise Value divided by revenue.",
    exercisePromptFr: "Calculez l'EV avec un multiple EV/Revenu de 4x et revenu 100 M€.",
    exercisePromptEn: "Calculate EV with EV/Revenue 4x and revenue €100M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "EV/Revenu de 5x signifie que l'EV vaut…",
      promptEn: "EV/Revenue of 5x means EV is…",
      explanationCorrectFr: "5 fois le revenu annuel.",
      explanationCorrectEn: "5 times annual revenue.",
      difficulty: 2,
      options: [
        { labelFr: "5 fois le revenu", labelEn: "5 times revenue", isCorrect: true },
        { labelFr: "5 % du revenu", labelEn: "5% of revenue", isCorrect: false },
        { labelFr: "Le revenu divisé par 5", labelEn: "Revenue divided by 5", isCorrect: false },
      ],
    },
  },
  {
    slug: "ev-ebitda",
    titleFr: "Multiple EV/EBITDA",
    titleEn: "EV/EBITDA Multiple",
    descriptionFr: "Appliquez le multiple EV/EBITDA en valorisation.",
    descriptionEn: "Apply the EV/EBITDA multiple in valuation.",
    moduleSlug: "valuation",
    sortOrder: 6,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "EV/EBITDA est le multiple le plus courant en valorisation d'entreprise. Il compare l'EV à l'EBITDA, indépendamment de la structure de capital et des impôts. Un EV/EBITDA de 10x signifie EV = 10 × EBITDA. Utilisez le simulateur pédagogique pour observer l'impact — pas une valorisation professionnelle.",
    textBodyEn: "EV/EBITDA is the most common enterprise valuation multiple. It compares EV to EBITDA, independent of capital structure and taxes. EV/EBITDA of 10x means EV = 10 × EBITDA. Use the pedagogical simulator to observe impact — not a professional valuation.",
    flashcardFrontFr: "EV/EBITDA",
    flashcardFrontEn: "EV/EBITDA",
    flashcardBackFr: "Enterprise Value divisé par EBITDA.",
    flashcardBackEn: "Enterprise Value divided by EBITDA.",
    exercisePromptFr: "Calculez l'EV avec EV/EBITDA 8x et EBITDA 50 M€.",
    exercisePromptEn: "Calculate EV with EV/EBITDA 8x and EBITDA €50M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "EV/EBITDA de 10x signifie EV =…",
      promptEn: "EV/EBITDA of 10x means EV =…",
      explanationCorrectFr: "10 × EBITDA.",
      explanationCorrectEn: "10 × EBITDA.",
      difficulty: 2,
      options: [
        { labelFr: "10 × EBITDA", labelEn: "10 × EBITDA", isCorrect: true },
        { labelFr: "EBITDA ÷ 10", labelEn: "EBITDA ÷ 10", isCorrect: false },
        { labelFr: "10 % de l'EBITDA", labelEn: "10% of EBITDA", isCorrect: false },
      ],
    },
  },
  {
    slug: "free-cash-flow",
    titleFr: "Free Cash Flow",
    titleEn: "Free Cash Flow",
    descriptionFr: "Calculez le Free Cash Flow disponible pour les investisseurs.",
    descriptionEn: "Calculate Free Cash Flow available to investors.",
    moduleSlug: "dcf",
    sortOrder: 0,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-cash-flow",
    learningObjective: "APPLY",
    isShort: true,
    shortTopic: "free-cash-flow",
    shortDurationSeconds: 165,
    textBodyFr: "Le Free Cash Flow (FCF) approxime le cash disponible après investissements nécessaires : souvent CFO − CAPEX (simplifié pédagogiquement). Le FCF est la base du DCF car il représente le cash réellement disponible. Une hausse du BFR consomme du FCF même si le résultat comptable est positif.",
    textBodyEn: "Free Cash Flow (FCF) approximates cash available after required investment: often CFO − CAPEX (pedagogical simplification). FCF is the DCF basis as it represents truly available cash. Rising working capital consumes FCF even when accounting profit is positive.",
    flashcardFrontFr: "Free Cash Flow",
    flashcardFrontEn: "Free Cash Flow",
    flashcardBackFr: "Cash d'exploitation moins CAPEX nécessaires.",
    flashcardBackEn: "Operating cash minus required CAPEX.",
    exercisePromptFr: "Calculez le FCF avec CFO 100 M€ et CAPEX 30 M€.",
    exercisePromptEn: "Calculate FCF with CFO €100M and CAPEX €30M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "FCF simplifié =…",
      promptEn: "Simplified FCF =…",
      explanationCorrectFr: "Cash d'exploitation (CFO) − CAPEX.",
      explanationCorrectEn: "Operating cash (CFO) − CAPEX.",
      difficulty: 2,
      options: [
        { labelFr: "CFO − CAPEX", labelEn: "CFO − CAPEX", isCorrect: true },
        { labelFr: "Revenu − coûts", labelEn: "Revenue − costs", isCorrect: false },
        { labelFr: "EBITDA − impôts", labelEn: "EBITDA − taxes", isCorrect: false },
      ],
    },
  },
  {
    slug: "wacc-basics",
    titleFr: "Bases du WACC",
    titleEn: "WACC Basics",
    descriptionFr: "Comprenez le coût moyen pondéré du capital (WACC).",
    descriptionEn: "Understand the weighted average cost of capital (WACC).",
    moduleSlug: "dcf",
    sortOrder: 1,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-capital-structure",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "wacc",
    shortDurationSeconds: 155,
    textBodyFr: "Le WACC (Weighted Average Cost of Capital) est un taux d'actualisation pédagogique qui pondère le coût de la dette et le coût des fonds propres. Plus le risque perçu monte, plus le WACC tend à monter — ce qui baisse la valeur actualisée dans un DCF simplifié. C'est un outil pédagogique, pas un taux de marché certifié.",
    textBodyEn: "WACC (Weighted Average Cost of Capital) is a pedagogical discount rate weighting debt cost and equity cost. As perceived risk rises, WACC tends to rise — lowering present value in a simplified DCF. It is a pedagogical tool, not a certified market rate.",
    flashcardFrontFr: "WACC",
    flashcardFrontEn: "WACC",
    flashcardBackFr: "Coût moyen pondéré du capital (dette + equity).",
    flashcardBackEn: "Weighted average cost of capital (debt + equity).",
    exercisePromptFr: "Citez deux composantes du WACC.",
    exercisePromptEn: "Name two components of WACC.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Le WACC sert typiquement à…",
      promptEn: "WACC is typically used to…",
      explanationCorrectFr: "Actualiser des flux dans une approche DCF pédagogique.",
      explanationCorrectEn: "Discount cash flows in an educational DCF approach.",
      difficulty: 2,
      options: [
        { labelFr: "Actualiser des flux (DCF)", labelEn: "Discount cash flows (DCF)", isCorrect: true },
        { labelFr: "Remplacer le bilan", labelEn: "Replace balance sheet", isCorrect: false },
        { labelFr: "Mesurer uniquement le dividende", labelEn: "Measure dividends only", isCorrect: false },
      ],
    },
  },
  {
    slug: "terminal-value",
    titleFr: "Valeur terminale",
    titleEn: "Terminal Value",
    descriptionFr: "Estimez la valeur terminale dans un modèle DCF.",
    descriptionEn: "Estimate terminal value in a DCF model.",
    moduleSlug: "dcf",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "La valeur terminale capture la valeur au-delà de la période de projection explicite. Méthodes courantes : Gordon Growth (FCF × (1+g) / (WACC−g)) ou multiple de sortie. Elle représente souvent une grande part de la valeur totale — illustration pédagogique, pas une valorisation certifiée.",
    textBodyEn: "Terminal value captures value beyond the explicit forecast period. Common methods: Gordon Growth (FCF × (1+g) / (WACC−g)) or exit multiple. It often represents a large share of total value — pedagogical illustration, not a certified valuation.",
    flashcardFrontFr: "Valeur terminale",
    flashcardFrontEn: "Terminal value",
    flashcardBackFr: "Valeur estimée au-delà de la période de projection.",
    flashcardBackEn: "Estimated value beyond the forecast period.",
    exercisePromptFr: "Expliquez pourquoi la valeur terminale est souvent importante.",
    exercisePromptEn: "Explain why terminal value is often significant.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "La valeur terminale représente souvent une grande part de la valeur DCF totale.",
      promptEn: "Terminal value often represents a large share of total DCF value.",
      explanationCorrectFr: "Vrai. Elle capture la valeur au-delà de la période explicite.",
      explanationCorrectEn: "True. It captures value beyond the explicit period.",
      difficulty: 2,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "discounting-basics",
    titleFr: "Bases de l'actualisation",
    titleEn: "Discounting Basics",
    descriptionFr: "Comprenez le principe de l'actualisation des flux futurs.",
    descriptionEn: "Understand the principle of discounting future cash flows.",
    moduleSlug: "dcf",
    sortOrder: 3,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "cf-valuation",
    learningObjective: "IDENTIFY",
    textBodyFr: "L'actualisation convertit un flux futur en sa valeur présente. Un euro dans 5 ans vaut moins qu'un euro aujourd'hui car le temps et le risque ont un coût. Le taux d'actualisation (WACC en DCF) reflète ce coût. Plus le taux est élevé, plus la valeur présente est faible — principe fondamental du DCF.",
    textBodyEn: "Discounting converts a future cash flow to its present value. One euro in 5 years is worth less than one euro today because time and risk have a cost. The discount rate (WACC in DCF) reflects this cost. A higher rate means lower present value — fundamental DCF principle.",
    flashcardFrontFr: "Actualisation",
    flashcardFrontEn: "Discounting",
    flashcardBackFr: "Convertir un flux futur en valeur présente.",
    flashcardBackEn: "Convert a future cash flow to present value.",
    exercisePromptFr: "Expliquez pourquoi un flux futur vaut moins qu'un flux présent.",
    exercisePromptEn: "Explain why a future cash flow is worth less than a present one.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Un taux d'actualisation plus élevé réduit la valeur présente.",
      promptEn: "A higher discount rate reduces present value.",
      explanationCorrectFr: "Vrai. Plus le taux est élevé, plus la valeur présente est faible.",
      explanationCorrectEn: "True. A higher rate means lower present value.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "dcf-enterprise-value",
    titleFr: "DCF → Enterprise Value",
    titleEn: "DCF to Enterprise Value",
    descriptionFr: "Calculez l'Enterprise Value via un modèle DCF.",
    descriptionEn: "Calculate Enterprise Value via a DCF model.",
    moduleSlug: "dcf",
    sortOrder: 4,
    estimatedMinutes: 10,
    difficulty: "ADVANCED",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "Un DCF d'entreprise actualise les FCF futurs au WACC pour obtenir l'Enterprise Value. EV = somme des FCF actualisés + valeur terminale actualisée. Cette approche est indépendante de la structure de capital. Utilisez le simulateur pédagogique pour observer l'impact du WACC et de la croissance — pas une valorisation professionnelle.",
    textBodyEn: "An enterprise DCF discounts future FCF at WACC to get Enterprise Value. EV = sum of discounted FCF + discounted terminal value. This approach is independent of capital structure. Use the pedagogical simulator to observe WACC and growth impact — not a professional valuation.",
    flashcardFrontFr: "DCF entreprise",
    flashcardFrontEn: "Enterprise DCF",
    flashcardBackFr: "Actualisation des FCF au WACC pour obtenir l'EV.",
    flashcardBackEn: "Discounting FCF at WACC to obtain EV.",
    exercisePromptFr: "Décrivez les étapes d'un DCF pour obtenir l'EV.",
    exercisePromptEn: "Describe the steps of a DCF to obtain EV.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Un DCF entreprise actualise les flux au…",
      promptEn: "An enterprise DCF discounts flows at…",
      explanationCorrectFr: "WACC (coût moyen pondéré du capital).",
      explanationCorrectEn: "WACC (weighted average cost of capital).",
      difficulty: 2,
      options: [
        { labelFr: "WACC", labelEn: "WACC", isCorrect: true },
        { labelFr: "Taux d'inflation", labelEn: "Inflation rate", isCorrect: false },
        { labelFr: "Taux de dividende", labelEn: "Dividend rate", isCorrect: false },
      ],
    },
  },
  {
    slug: "dcf-equity-value",
    titleFr: "DCF → Equity Value",
    titleEn: "DCF to Equity Value",
    descriptionFr: "Passez de l'Enterprise Value à l'Equity Value via le DCF.",
    descriptionEn: "Move from Enterprise Value to Equity Value via DCF.",
    moduleSlug: "dcf",
    sortOrder: 5,
    estimatedMinutes: 9,
    difficulty: "ADVANCED",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "Après calcul de l'EV par DCF, l'Equity Value s'obtient par EV − dette nette. Alternative : actualiser les flux disponibles pour les actionnaires (dividendes ou FCFE) au coût des fonds propres. Les deux approches doivent converger si correctement appliquées — vérification pédagogique de cohérence.",
    textBodyEn: "After computing EV via DCF, Equity Value = EV − net debt. Alternative: discount cash flows to shareholders (dividends or FCFE) at cost of equity. Both approaches should converge if correctly applied — pedagogical consistency check.",
    flashcardFrontFr: "EV → Equity Value",
    flashcardFrontEn: "EV to Equity Value",
    flashcardBackFr: "Equity Value = EV − dette nette.",
    flashcardBackEn: "Equity Value = EV − net debt.",
    exercisePromptFr: "Calculez l'Equity Value avec EV 800 M€ et dette nette 150 M€.",
    exercisePromptEn: "Calculate Equity Value with EV €800M and net debt €150M.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Equity Value = EV −…",
      promptEn: "Equity Value = EV −…",
      explanationCorrectFr: "Dette nette.",
      explanationCorrectEn: "Net debt.",
      difficulty: 2,
      options: [
        { labelFr: "Dette nette", labelEn: "Net debt", isCorrect: true },
        { labelFr: "EBITDA", labelEn: "EBITDA", isCorrect: false },
        { labelFr: "Revenu total", labelEn: "Total revenue", isCorrect: false },
      ],
    },
  },
  {
    slug: "purchase-price",
    titleFr: "Prix d'acquisition",
    titleEn: "Purchase Price",
    descriptionFr: "Comprenez le prix d'acquisition dans une transaction M&A.",
    descriptionEn: "Understand purchase price in an M&A transaction.",
    moduleSlug: "ma-basics",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le prix d'acquisition est le montant payé pour acquérir une entreprise ou ses actifs. Il peut inclure cash, actions de l'acquéreur et assumption de dettes. Le prix dépend de la valorisation, la négociation et les synergies attendues — contexte pédagogique M&A, pas un conseil de transaction.",
    textBodyEn: "Purchase price is the amount paid to acquire a company or its assets. It may include cash, acquirer shares, and debt assumption. Price depends on valuation, negotiation, and expected synergies — M&A pedagogical context, not transaction advice.",
    flashcardFrontFr: "Prix d'acquisition",
    flashcardFrontEn: "Purchase price",
    flashcardBackFr: "Montant total payé pour acquérir une entreprise.",
    flashcardBackEn: "Total amount paid to acquire a company.",
    exercisePromptFr: "Listez trois composantes possibles d'un prix d'acquisition.",
    exercisePromptEn: "List three possible components of a purchase price.",
    question: {
      type: "MULTIPLE_CHOICE",
      promptFr: "Le prix d'acquisition peut inclure… (Plusieurs réponses)",
      promptEn: "Purchase price may include… (Multiple answers)",
      explanationCorrectFr: "Cash, actions et assumption de dettes sont des composantes courantes.",
      explanationCorrectEn: "Cash, shares, and debt assumption are common components.",
      difficulty: 2,
      options: [
        { labelFr: "Cash", labelEn: "Cash", isCorrect: true },
        { labelFr: "Actions de l'acquéreur", labelEn: "Acquirer shares", isCorrect: true },
        { labelFr: "Assumption de dettes", labelEn: "Debt assumption", isCorrect: true },
        { labelFr: "TVA uniquement", labelEn: "VAT only", isCorrect: false },
      ],
    },
  },
  {
    slug: "sources-uses",
    titleFr: "Sources et emplois",
    titleEn: "Sources and Uses",
    descriptionFr: "Construisez un tableau sources et emplois en M&A.",
    descriptionEn: "Build a sources and uses table in M&A.",
    moduleSlug: "ma-basics",
    sortOrder: 1,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "APPLY",
    textBodyFr: "Le tableau sources et emplois équilibre les fonds nécessaires (emplois : prix, frais, refinancement) avec les fonds disponibles (sources : cash, dette, equity). Total sources = total emplois. C'est un outil de structuration pédagogique pour comprendre comment une deal est financée — pas un modèle de transaction réel.",
    textBodyEn: "The sources and uses table balances required funds (uses: price, fees, refinancing) with available funds (sources: cash, debt, equity). Total sources = total uses. It is a pedagogical structuring tool to understand how a deal is financed — not a real transaction model.",
    flashcardFrontFr: "Sources et emplois",
    flashcardFrontEn: "Sources and uses",
    flashcardBackFr: "Tableau équilibrant fonds nécessaires et fonds disponibles.",
    flashcardBackEn: "Table balancing required and available funds.",
    exercisePromptFr: "Listez trois emplois et trois sources typiques en M&A.",
    exercisePromptEn: "List three typical uses and three sources in M&A.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Total sources doit égaler total emplois.",
      promptEn: "Total sources must equal total uses.",
      explanationCorrectFr: "Vrai. C'est le principe fondamental du tableau.",
      explanationCorrectEn: "True. That is the table's fundamental principle.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "synergies-basics",
    titleFr: "Bases des synergies",
    titleEn: "Synergies Basics",
    descriptionFr: "Comprenez les synergies en contexte M&A.",
    descriptionEn: "Understand synergies in M&A context.",
    moduleSlug: "ma-basics",
    sortOrder: 2,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "ANALYZE",
    textBodyFr: "Les synergies sont des gains attendus de la combinaison de deux entreprises : coûts réduits (synergies de coûts) ou revenus augmentés (synergies de revenus). Elles justifient partiellement une prime d'acquisition. Les synergies réalisées sont souvent inférieures aux synergies annoncées — observation pédagogique, pas une promesse.",
    textBodyEn: "Synergies are expected gains from combining two companies: cost reductions (cost synergies) or revenue increases (revenue synergies). They partially justify an acquisition premium. Realized synergies are often below announced synergies — pedagogical observation, not a promise.",
    flashcardFrontFr: "Synergies de coûts",
    flashcardFrontEn: "Cost synergies",
    flashcardBackFr: "Réductions de coûts attendues après la combinaison.",
    flashcardBackEn: "Expected cost reductions after combination.",
    exercisePromptFr: "Citez un exemple de synergie de coûts et un de revenus.",
    exercisePromptEn: "Give one cost synergy and one revenue synergy example.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Les synergies de coûts impliquent typiquement…",
      promptEn: "Cost synergies typically involve…",
      explanationCorrectFr: "Des réductions de coûts après la combinaison.",
      explanationCorrectEn: "Cost reductions after combination.",
      difficulty: 2,
      options: [
        { labelFr: "Réductions de coûts", labelEn: "Cost reductions", isCorrect: true },
        { labelFr: "Hausse des prix", labelEn: "Price increases", isCorrect: false },
        { labelFr: "Augmentation des dettes", labelEn: "Debt increases", isCorrect: false },
      ],
    },
  },
  {
    slug: "accretion-dilution",
    titleFr: "Accrétion / dilution",
    titleEn: "Accretion / Dilution",
    descriptionFr: "Analysez l'effet d'une acquisition sur le BPA.",
    descriptionEn: "Analyze an acquisition's effect on EPS.",
    moduleSlug: "ma-basics",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "ADVANCED",
    skillSlug: "cf-valuation",
    learningObjective: "ANALYZE",
    textBodyFr: "L'accrétion / dilution compare le BPA pro forma après acquisition au BPA standalone. Une opération est accretive si le BPA augmente, dilutive s'il baisse. C'est un test pédagogique de structure (cash / dette / actions), pas une garantie de création de valeur économique.",
    textBodyEn: "Accretion / dilution compares pro forma EPS after acquisition to standalone EPS. A deal is accretive if EPS rises, dilutive if it falls. It is a pedagogical structure test (cash / debt / shares), not a guarantee of economic value creation.",
    flashcardFrontFr: "Accretive",
    flashcardFrontEn: "Accretive",
    flashcardBackFr: "Le BPA pro forma augmente après l'opération.",
    flashcardBackEn: "Pro forma EPS increases after the deal.",
    exercisePromptFr: "Citez un facteur qui peut rendre une acquisition dilutive.",
    exercisePromptEn: "Name one factor that can make an acquisition dilutive.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Une opération dilutive signifie typiquement que…",
      promptEn: "A dilutive deal typically means that…",
      explanationCorrectFr: "Le BPA pro forma diminue.",
      explanationCorrectEn: "Pro forma EPS decreases.",
      difficulty: 2,
      options: [
        { labelFr: "Le BPA pro forma diminue", labelEn: "Pro forma EPS decreases", isCorrect: true },
        { labelFr: "Le cash disparaît toujours", labelEn: "Cash always disappears", isCorrect: false },
        { labelFr: "Le WACC devient nul", labelEn: "WACC becomes zero", isCorrect: false },
      ],
    },
  },
  {
    slug: "strategic-rationale",
    titleFr: "Rationale stratégique",
    titleEn: "Strategic Rationale",
    descriptionFr: "Évaluez la logique stratégique d'une acquisition M&A.",
    descriptionEn: "Evaluate the strategic logic of an M&A acquisition.",
    moduleSlug: "ma-basics",
    sortOrder: 4,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "cf-valuation",
    learningObjective: "DECIDE",
    textBodyFr: "La rationale stratégique explique pourquoi une acquisition crée de la valeur : expansion géographique, consolidation de marché, acquisition de technologies, diversification. Elle doit être distincte de la justification financière (synergies, multiples). Une deal sans rationale stratégique claire est plus risquée — cadre d'analyse pédagogique.",
    textBodyEn: "Strategic rationale explains why an acquisition creates value: geographic expansion, market consolidation, technology acquisition, diversification. It must be distinct from financial justification (synergies, multiples). A deal without clear strategic rationale is riskier — pedagogical analysis framework.",
    flashcardFrontFr: "Rationale stratégique",
    flashcardFrontEn: "Strategic rationale",
    flashcardBackFr: "Logique stratégique justifiant une acquisition.",
    flashcardBackEn: "Strategic logic justifying an acquisition.",
    exercisePromptFr: "Citez trois rationales stratégiques pour une acquisition.",
    exercisePromptEn: "Name three strategic rationales for an acquisition.",
    question: {
      type: "MULTIPLE_CHOICE",
      promptFr: "Quelles sont des rationales stratégiques ? (Plusieurs réponses)",
      promptEn: "Which are strategic rationales? (Multiple answers)",
      explanationCorrectFr: "Expansion géographique, consolidation et acquisition de technologies sont des rationales courantes.",
      explanationCorrectEn: "Geographic expansion, consolidation, and technology acquisition are common rationales.",
      difficulty: 2,
      options: [
        { labelFr: "Expansion géographique", labelEn: "Geographic expansion", isCorrect: true },
        { labelFr: "Consolidation de marché", labelEn: "Market consolidation", isCorrect: true },
        { labelFr: "Acquisition de technologies", labelEn: "Technology acquisition", isCorrect: true },
        { labelFr: "Réduire le salaire du CEO", labelEn: "Reduce CEO salary", isCorrect: false },
      ],
    },
  },
];
