import { buildPfLesson, opt, q } from "./pf-factory";
import type { CompactLesson } from "./compact";

export const PF_DEBT_LESSONS: CompactLesson[] = [
  buildPfLesson({
    slug: "what-is-debt",
    titleFr: "Qu'est-ce que la dette ?",
    titleEn: "What Is Debt?",
    descriptionFr: "Définir la dette, ses formes courantes et ce qu'elle implique pour votre budget.",
    descriptionEn: "Define debt, its common forms, and what it means for your budget.",
    moduleSlug: "debt",
    sortOrder: 0,
    estimatedMinutes: 6,
    difficulty: "BEGINNER",
    skillSlug: "pf-debt",
    learningObjective: "IDENTIFY",
    isShort: false,
    objectiveFr: "Reconnaître ce qu'est une dette et distinguer dette, dépense et actif.",
    objectiveEn: "Recognize what debt is and distinguish debt, spending, and assets.",
    explanationFr:
      "La dette est de l'argent emprunté que vous devez rembourner, généralement avec des intérêts. Elle peut financer un achat immédiat (carte, prêt auto, hypothèque) ou combler un déficit temporaire. Contrairement à une dépense payée comptant, la dette crée un engagement futur : des paiements réguliers jusqu'à extinction. Les règles (taux max, durée, protection du débiteur) varient selon les pays.",
    explanationEn:
      "Debt is borrowed money you must repay, usually with interest. It can fund an immediate purchase (card, auto loan, mortgage) or bridge a temporary shortfall. Unlike cash spending, debt creates a future obligation: regular payments until it is cleared. Rules (rate caps, terms, borrower protection) vary by country.",
    exampleFr:
      "1) Carte : 800 utilisés, minimum 25 / mois. 2) Prêt perso : 5 000 à 8 % sur 3 ans. 3) Hypothèque : 180 000 sur 20 ans. Chaque ligne = capital + intérêts à payer.",
    exampleEn:
      "1) Card: 800 used, 25 minimum / month. 2) Personal loan: 5,000 at 8% over 3 years. 3) Mortgage: 180,000 over 20 years. Each line = principal + interest to pay.",
    practicalFr:
      "Listez vos dettes actuelles avec trois colonnes : solde, paiement mensuel, taux ou TAEG si connu.",
    practicalEn:
      "List your current debts in three columns: balance, monthly payment, rate or APR if known.",
    mistakeFr:
      "Traiter un paiement minimum comme un « remboursement normal » sans voir que le solde stagne ou croît.",
    mistakeEn:
      "Treating a minimum payment as “normal repayment” without seeing the balance stall or grow.",
    takeawayFr: "La dette reporte un coût dans le futur — le prix total dépend du taux et de la durée.",
    takeawayEn: "Debt shifts a cost into the future — total price depends on rate and term.",
    decisionFr: "Savoir si une dette est un outil temporaire ou un engagement long qui réduit votre marge mensuelle.",
    decisionEn: "Know whether debt is a temporary tool or a long commitment that shrinks monthly margin.",
    flashcardFrontFr: "Dette",
    flashcardFrontEn: "Debt",
    flashcardBackFr: "Argent emprunté à rembourner, souvent avec intérêts.",
    flashcardBackEn: "Borrowed money to repay, often with interest.",
    exercisePromptFr:
      "Situation : solde carte 1 200, paiement minimum 40, intérêts mensuels ~18. Que se passe-t-il si vous ne payez que 40 ?",
    exercisePromptEn:
      "Situation: card balance 1,200, minimum payment 40, monthly interest ~18. What happens if you only pay 40?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Quelle situation illustre le mieux une dette plutôt qu'une simple dépense ?",
      promptEn: "Which situation best illustrates debt rather than simple spending?",
      explanationCorrectFr:
        "Acheter avec un prêt à rembourser sur plusieurs mois crée une obligation future — c'est de la dette.",
      explanationCorrectEn:
        "Buying with a loan repaid over several months creates a future obligation — that is debt.",
      difficulty: 1,
      options: [
        opt("Payer 50 en espèces pour un repas", "Paying 50 cash for a meal", false, "C'est une dépense immédiate, pas un emprunt.", "That is immediate spending, not borrowing."),
        opt("Financer 3 000 sur 24 mois avec intérêts", "Financing 3,000 over 24 months with interest", true),
        opt("Recevoir un salaire", "Receiving a salary", false, "Un salaire est un revenu, pas une dette.", "Salary is income, not debt."),
      ],
    }),
    questions: [
      q({
        type: "TRUE_FALSE",
        promptFr: "Une hypothèque est une forme de dette.",
        promptEn: "A mortgage is a form of debt.",
        explanationCorrectFr: "Vrai : c'est un prêt garanti par le bien, à rembourser avec intérêts.",
        explanationCorrectEn: "True: it is a loan secured by the property, repaid with interest.",
        difficulty: 1,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "Une hypothèque est bien un emprunt à rembourser.", "A mortgage is indeed borrowed money to repay."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "good-vs-bad-debt",
    titleFr: "Dette bonne vs mauvaise",
    titleEn: "Good vs Bad Debt",
    descriptionFr: "Distinguer dettes productives et dettes coûteuses selon le contexte.",
    descriptionEn: "Distinguish productive and costly debt depending on context.",
    moduleSlug: "debt",
    sortOrder: 1,
    estimatedMinutes: 7,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    isShort: false,
    objectiveFr: "Évaluer une dette selon son coût, son usage et votre capacité de remboursement.",
    objectiveEn: "Evaluate debt by cost, use, and your repayment capacity.",
    explanationFr:
      "Une dette « productive » finance un actif ou une compétence qui peut générer de la valeur (formation, outil professionnel, immobilier locatif). Une dette « coûteuse » finance la consommation à un taux élevé (carte revolving, micro-crédit). La frontière n'est pas absolue : un prêt étudiant à 4 % peut être raisonnable ; une carte à 22 % pour des loisirs est généralement coûteuse. Les seuils et produits varient selon les marchés.",
    explanationEn:
      "“Productive” debt funds an asset or skill that may generate value (training, professional tool, rental property). “Costly” debt funds consumption at high rates (revolving cards, payday loans). The line is not absolute: a 4% student loan may be reasonable; a 22% card for leisure is usually costly. Thresholds and products vary by market.",
    exampleFr:
      "Dette A : prêt pro 6 000 à 5 % pour un outil qui augmente le revenu. Dette B : carte 2 500 à 19 % pour des achats non essentiels. Même montant emprunté, coût et logique très différents.",
    exampleEn:
      "Debt A: 6,000 pro loan at 5% for a tool that raises income. Debt B: 2,500 card at 19% for non-essential purchases. Same borrowed amount, very different cost and logic.",
    practicalFr:
      "Classez trois dettes que vous connaissez (ou fictives) : productive, neutre ou coûteuse — et notez le taux.",
    practicalEn:
      "Classify three debts you know (or fictional ones): productive, neutral, or costly — and note the rate.",
    mistakeFr:
      "Appeler « bonne dette » tout emprunt lié à un actif, sans regarder le taux ni la capacité de remboursement.",
    mistakeEn:
      "Calling any asset-linked borrowing “good debt” without checking rate or repayment capacity.",
    takeawayFr: "Le label « bonne dette » ne remplace pas l'analyse du coût total et du risque.",
    takeawayEn: "The “good debt” label does not replace analyzing total cost and risk.",
    decisionFr: "Avant d'emprunter : usage, taux, durée, et impact sur votre marge mensuelle.",
    decisionEn: "Before borrowing: use, rate, term, and impact on your monthly margin.",
    flashcardFrontFr: "Dette coûteuse",
    flashcardFrontEn: "Costly debt",
    flashcardBackFr: "Emprunt à taux élevé pour consommation — intérêts qui grignotent la marge.",
    flashcardBackEn: "High-rate borrowing for consumption — interest that erodes margin.",
    exercisePromptFr:
      "Comparez : prêt auto 15 000 à 6 % vs carte 3 000 à 21 %. Quelle dette coûte plus d'intérêts sur 2 ans si les paiements sont similaires ?",
    exercisePromptEn:
      "Compare: 15,000 auto loan at 6% vs 3,000 card at 21%. Which costs more interest over 2 years if payments are similar?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Quel exemple est typiquement une dette coûteuse ?",
      promptEn: "Which example is typically costly debt?",
      explanationCorrectFr: "Le crédit revolving à taux élevé finance souvent la consommation avec des intérêts lourds.",
      explanationCorrectEn: "High-rate revolving credit often funds consumption with heavy interest.",
      difficulty: 2,
      options: [
        opt("Crédit revolving à 22 %", "22% revolving credit", true),
        opt("Prêt étudiant à 3 %", "3% student loan", false, "Taux bas + formation peut être raisonnable selon le contexte.", "Low rate + education may be reasonable in context."),
        opt("Hypothèque résidence à 4 %", "4% home mortgage", false, "Taux modéré sur actif long terme — pas le profil « coûteux ».", "Moderate rate on long-term asset — not the costly profile."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Un prêt pour acheter un outil qui augmente durablement le revenu est plutôt :",
        promptEn: "A loan to buy a tool that durably raises income is rather:",
        explanationCorrectFr: "Potentiellement productive si le rendement excède le coût du crédit.",
        explanationCorrectEn: "Potentially productive if return exceeds credit cost.",
        difficulty: 2,
        options: [
          opt("Productive (à analyser)", "Productive (to analyze)", true),
          opt("Toujours mauvaise", "Always bad", false, "Le contexte et le taux comptent — pas une catégorie absolue.", "Context and rate matter — not an absolute category."),
          opt("Identique à une carte loisirs", "Same as a leisure card", false, "L'usage et le taux diffèrent fortement.", "Use and rate differ sharply."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "understanding-interest",
    titleFr: "Comprendre l'intérêt",
    titleEn: "Understanding Interest",
    descriptionFr: "Ce que l'intérêt représente sur un prêt ou un placement.",
    descriptionEn: "What interest represents on a loan or investment.",
    moduleSlug: "debt",
    sortOrder: 2,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "pf-interest",
    learningObjective: "IDENTIFY",
    isShort: false,
    objectiveFr: "Expliquer l'intérêt comme prix du temps et du risque, et calculer un intérêt simple court.",
    objectiveEn: "Explain interest as the price of time and risk, and compute short simple interest.",
    explanationFr:
      "L'intérêt est ce que le prêteur demande pour céder de l'argent maintenant. Le taux (ex. 6 % / an) s'applique au capital sur une période. Sur un prêt, c'est un coût pour vous ; sur un dépôt, un rendement. Les conventions (taux annuel, mensuel, TAEG) diffèrent selon les pays — lisez toujours la définition du produit.",
    explanationEn:
      "Interest is what the lender charges to hand over money now. The rate (e.g. 6% / year) applies to principal over a period. On a loan it is a cost for you; on a deposit, a return. Conventions (annual, monthly, APR) differ by country — always read the product definition.",
    exampleFr:
      "Capital 1 000, taux 5 % / an, intérêt simple 1 an = 1 000 × 0,05 = 50. Total dû après 1 an : 1 050.",
    exampleEn:
      "Principal 1,000, rate 5% / year, simple interest 1 year = 1,000 × 0.05 = 50. Total due after 1 year: 1,050.",
    practicalFr: "Calculez l'intérêt simple sur 2 000 à 4 % pour un an. Quel serait le paiement total ?",
    practicalEn: "Compute simple interest on 2,000 at 4% for one year. What would the total payment be?",
    mistakeFr: "Comparer deux prêts uniquement sur le taux affiché sans la durée ni les frais.",
    mistakeEn: "Comparing two loans only on the advertised rate without term or fees.",
    takeawayFr: "Le taux traduit un coût (ou rendement) en pourcentage du capital — le contexte compte.",
    takeawayEn: "The rate expresses a cost (or return) as a percent of principal — context matters.",
    decisionFr: "Convertir un taux en euros (ou dollars) concrets avant de juger un emprunt.",
    decisionEn: "Convert a rate into concrete currency before judging a loan.",
    flashcardFrontFr: "Intérêt simple (1 an)",
    flashcardFrontEn: "Simple interest (1 year)",
    flashcardBackFr: "Capital × taux (ex. 1 000 × 5 % = 50).",
    flashcardBackEn: "Principal × rate (e.g. 1,000 × 5% = 50).",
    exercisePromptFr: "3 500 à 6 % simple sur 1 an : intérêt ? Total ?",
    exercisePromptEn: "3,500 at 6% simple for 1 year: interest? Total?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "1 000 à 5 % d'intérêt simple pour 1 an : intérêt et total ?",
      promptEn: "1,000 at 5% simple interest for 1 year: interest and total?",
      explanationCorrectFr: "Intérêt = 50 ; total = 1 050.",
      explanationCorrectEn: "Interest = 50; total = 1,050.",
      difficulty: 1,
      options: [
        opt("50 → total 1 050", "50 → total 1,050", true),
        opt("500 → total 1 500", "500 → total 1,500", false, "5 % de 1 000 = 50, pas 500.", "5% of 1,000 = 50, not 500."),
        opt("0 → total 1 000", "0 → total 1,000", false, "Un taux positif génère des intérêts.", "A positive rate generates interest."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Sur un prêt, le taux d'intérêt représente principalement :",
        promptEn: "On a loan, the interest rate mainly represents:",
        explanationCorrectFr: "Le coût du financement pour l'emprunteur.",
        explanationCorrectEn: "The cost of financing for the borrower.",
        difficulty: 1,
        options: [
          opt("Le coût du financement", "The cost of financing", true),
          opt("La taxe sur le revenu", "Income tax", false, "Les intérêts ne sont pas la taxe sur le revenu.", "Interest is not income tax."),
          opt("Le prix du bien acheté", "The price of the purchased item", false, "Le prix du bien est distinct du coût du crédit.", "Item price is separate from credit cost."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "simple-vs-compound-interest",
    titleFr: "Intérêt simple vs composé",
    titleEn: "Simple vs Compound Interest",
    descriptionFr: "Comparer simple et composé — bénéfice pour l'épargne, risque sur la dette.",
    descriptionEn: "Compare simple and compound — benefit for savings, risk on debt.",
    moduleSlug: "debt",
    sortOrder: 3,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-interest",
    learningObjective: "ANALYZE",
    isShort: false,
    objectiveFr: "Contraster intérêt simple et composé sur plusieurs périodes avec des montants concrets.",
    objectiveEn: "Contrast simple and compound interest over several periods with concrete amounts.",
    explanationFr:
      "Intérêt simple : calculé seulement sur le capital initial. Intérêt composé : les intérêts s'ajoutent au capital et génèrent eux-mêmes des intérêts. Sur 10 ans, 1 000 à 5 % composé annuel ≈ 1 629 ; simple ≈ 1 500. Pour une dette à taux élevé, la capitalisation accélère le coût — illustration pédagogique, pas une projection garantie.",
    explanationEn:
      "Simple interest: calculated only on initial principal. Compound interest: interest is added to principal and earns more interest. Over 10 years, 1,000 at 5% compounded annually ≈ 1,629; simple ≈ 1,500. On high-rate debt, compounding accelerates cost — pedagogical illustration, not a guaranteed projection.",
    exampleFr:
      "1 000 à 5 % / an, 3 ans : simple → 1 150 total. Composé → 1 000 × 1,05³ ≈ 1 158. L'écart grandit avec le temps.",
    exampleEn:
      "1,000 at 5% / year, 3 years: simple → 1,150 total. Compound → 1,000 × 1.05³ ≈ 1,158. The gap widens over time.",
    practicalFr: "Estimez simple vs composé sur 2 000 à 6 % sur 5 ans (calcul ou tableur).",
    practicalEn: "Estimate simple vs compound on 2,000 at 6% over 5 years (calculation or spreadsheet).",
    mistakeFr: "Supposer que les intérêts de carte « ne s'accumulent pas » si on paie le minimum.",
    mistakeEn: "Assuming card interest “does not pile up” when paying the minimum.",
    takeawayFr: "La capitalisation amplifie les effets — favorable à l'épargne, pénible sur dette coûteuse.",
    takeawayEn: "Compounding amplifies effects — helpful for savings, painful on costly debt.",
    decisionFr: "Identifier quelles dettes capitalisent les intérêts (cartes, certains prêts) vs intérêt simple.",
    decisionEn: "Identify which debts compound interest (cards, some loans) vs simple interest.",
    flashcardFrontFr: "Intérêt composé",
    flashcardFrontEn: "Compound interest",
    flashcardBackFr: "Intérêts calculés sur capital + intérêts antérieurs.",
    flashcardBackEn: "Interest on principal plus prior interest.",
    exercisePromptFr: "1 500 à 8 % composé annuel sur 2 ans : capital final approximatif ?",
    exercisePromptEn: "1,500 at 8% compounded annually for 2 years: approximate final amount?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Sur 10 ans, 1 000 à 5 % : le composé dépasse le simple car :",
      promptEn: "Over 10 years, 1,000 at 5%: compound beats simple because:",
      explanationCorrectFr: "Les intérêts précédents sont réinvestis et génèrent de nouveaux intérêts.",
      explanationCorrectEn: "Prior interest is reinvested and earns new interest.",
      difficulty: 2,
      options: [
        opt("Les intérêts s'ajoutent au capital chaque période", "Interest is added to principal each period", true),
        opt("Le taux augmente chaque année", "The rate rises each year", false, "Le taux peut rester fixe — c'est la capitalisation qui change le total.", "Rate can stay fixed — compounding changes the total."),
        opt("Le capital diminue automatiquement", "Principal shrinks automatically", false, "Le capital croît avec les intérêts composés.", "Principal grows with compound interest."),
      ],
    }),
    questions: [
      q({
        type: "TRUE_FALSE",
        promptFr: "Sur une dette à taux élevé, l'intérêt composé peut aggraver le coût total.",
        promptEn: "On high-rate debt, compound interest can worsen total cost.",
        explanationCorrectFr: "Vrai : les intérêts non payés s'ajoutent au solde et génèrent plus d'intérêts.",
        explanationCorrectEn: "True: unpaid interest adds to balance and generates more interest.",
        difficulty: 1,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "C'est un mécanisme clé des dettes à capitalisation.", "That is a key mechanism of compounding debts."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "loans-basics",
    titleFr: "Bases des prêts",
    titleEn: "Loans Basics",
    descriptionFr: "Capital, taux, durée, TAEG — les pièces d'un prêt.",
    descriptionEn: "Principal, rate, term, APR — the pieces of a loan.",
    moduleSlug: "debt",
    sortOrder: 4,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "pf-debt",
    learningObjective: "IDENTIFY",
    isShort: false,
    objectiveFr: "Identifier les trois composantes d'un prêt et utiliser le TAEG pour comparer.",
    objectiveEn: "Identify the three loan components and use APR to compare.",
    explanationFr:
      "Un prêt = capital emprunté + taux d'intérêt + durée de remboursement. La mensualité dépend des trois. Le TAEG (ou APR) intègre frais et intérêts — utile pour comparer des offres. Les formules et obligations d'affichage varient selon les juridictions.",
    explanationEn:
      "A loan = borrowed principal + interest rate + repayment term. The monthly payment depends on all three. APR integrates fees and interest — useful to compare offers. Formulas and disclosure rules vary by jurisdiction.",
    exampleFr:
      "Prêt 10 000, 6 %, 5 ans → mensualité ~193 (illustration). Même capital à 9 % → ~208. +15 / mois × 60 mois = différence notable.",
    exampleEn:
      "Loan 10,000, 6%, 5 years → ~193 monthly (illustration). Same principal at 9% → ~208. +15 / month × 60 months = a notable difference.",
    practicalFr: "Pour deux offres fictives, notez capital, taux, durée, TAEG et mensualité.",
    practicalEn: "For two fictional offers, note principal, rate, term, APR, and monthly payment.",
    mistakeFr: "Choisir le prêt à la plus petite mensualité sans regarder la durée totale ni le coût global.",
    mistakeEn: "Choosing the smallest monthly payment without checking total term or overall cost.",
    takeawayFr: "Comparez le coût total du crédit, pas seulement la mensualité ou le taux isolé.",
    takeawayEn: "Compare total cost of credit, not just the monthly payment or isolated rate.",
    decisionFr: "Vérifier TAEG, durée et pénalités avant de signer.",
    decisionEn: "Check APR, term, and penalties before signing.",
    flashcardFrontFr: "TAEG / APR",
    flashcardFrontEn: "APR",
    flashcardBackFr: "Mesure du coût total du crédit (intérêts + frais).",
    flashcardBackEn: "Measure of total credit cost (interest + fees).",
    exercisePromptFr: "10 000 sur 4 ans vs 6 ans au même taux : quelle option coûte plus d'intérêts totaux ?",
    exercisePromptEn: "10,000 over 4 years vs 6 years at the same rate: which costs more total interest?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Que mesure le TAEG ?",
      promptEn: "What does APR measure?",
      explanationCorrectFr: "Le coût total du crédit, incluant intérêts et frais usuels.",
      explanationCorrectEn: "Total cost of credit, including interest and usual fees.",
      difficulty: 2,
      options: [
        opt("Coût total du crédit", "Total cost of credit", true),
        opt("Salaire minimum légal", "Legal minimum wage", false, "Le TAEG concerne le crédit, pas le salaire.", "APR concerns credit, not wages."),
        opt("Valeur future du bien", "Future value of the asset", false, "La valeur du bien est distincte du coût du prêt.", "Asset value is separate from loan cost."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Allonger la durée d'un prêt (même taux) tend à :",
        promptEn: "Extending loan term (same rate) tends to:",
        explanationCorrectFr: "Réduire la mensualité mais augmenter les intérêts totaux.",
        explanationCorrectEn: "Lower the monthly payment but raise total interest.",
        difficulty: 2,
        options: [
          opt("Baisser mensualité, hausser intérêts totaux", "Lower monthly, raise total interest", true),
          opt("Baisser mensualité et intérêts totaux", "Lower monthly and total interest", false, "Plus de mois = plus de périodes d'intérêts.", "More months = more interest periods."),
          opt("Augmenter mensualité et intérêts", "Raise monthly and interest", false, "La mensualité baisse généralement quand la durée s'allonge.", "Monthly payment usually falls when term lengthens."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "loan-amortization",
    titleFr: "Amortissement d'un prêt",
    titleEn: "Loan Amortization",
    descriptionFr: "Comment chaque paiement se partage entre intérêts et capital.",
    descriptionEn: "How each payment splits between interest and principal.",
    moduleSlug: "debt",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    isShort: false,
    objectiveFr: "Lire un tableau d'amortissement et comprendre la part capital vs intérêts.",
    objectiveEn: "Read an amortization schedule and understand principal vs interest share.",
    explanationFr:
      "L'amortissement décrit comment un prêt est remboursé période par période. En mensualités fixes, le paiement total est stable mais la part intérêts diminue et la part capital augmente au fil du temps. Au début, vous payez surtout des intérêts ; vers la fin, surtout du capital. Les prêts à mensualités progressives (certains marchés) suivent une autre logique.",
    explanationEn:
      "Amortization describes how a loan is repaid period by period. With fixed payments, total payment is stable but the interest share falls and principal share rises over time. Early on you pay mostly interest; near the end, mostly principal. Progressive-payment loans (some markets) follow different logic.",
    exampleFr:
      "Mensualité 200 sur prêt amortissable : mois 1 → ~120 intérêts + 80 capital ; mois 48 → ~40 intérêts + 160 capital (illustration). Le total mensuel reste 200.",
    exampleEn:
      "200 payment on amortizing loan: month 1 → ~120 interest + 80 principal; month 48 → ~40 interest + 160 principal (illustration). Monthly total stays 200.",
    practicalFr: "Demandez ou simulez un échéancier : repérez la ligne où la part capital dépasse les intérêts.",
    practicalEn: "Request or simulate a schedule: find the line where principal share exceeds interest.",
    mistakeFr: "Croire qu'une mensualité fixe signifie que vous remboursez le même capital chaque mois.",
    mistakeEn: "Believing a fixed payment means you repay the same principal each month.",
    takeawayFr: "Amortissement = redistribution progressive du paiement vers le capital.",
    takeawayEn: "Amortization = gradual shift of payment toward principal.",
    decisionFr: "Savoir lire une ligne d'échéancier avant de refinancer ou vendre tôt.",
    decisionEn: "Know how to read a schedule line before refinancing or selling early.",
    flashcardFrontFr: "Amortissement",
    flashcardFrontEn: "Amortization",
    flashcardBackFr: "Partage paiement → intérêts + capital, évolution dans le temps.",
    flashcardBackEn: "Payment split → interest + principal, evolving over time.",
    exercisePromptFr: "Paiement 350 : intérêts 210, capital 140. Quel % va aux intérêts ce mois ?",
    exercisePromptEn: "Payment 350: interest 210, principal 140. What % goes to interest this month?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Avec mensualités fixes, en début de prêt la part intérêts est généralement :",
      promptEn: "With fixed payments, early in the loan the interest share is generally:",
      explanationCorrectFr: "Plus élevée — le solde restant est encore grand.",
      explanationCorrectEn: "Higher — remaining balance is still large.",
      difficulty: 2,
      options: [
        opt("Plus élevée qu'au milieu du prêt", "Higher than mid-loan", true),
        opt("Nulle dès le premier mois", "Zero from month one", false, "Des intérêts sont dus sur le capital restant.", "Interest is due on remaining principal."),
        opt("Identique chaque mois en euros", "Same each month in currency", false, "La part en euros diminue généralement.", "The currency share usually falls."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Paiement 400 : intérêts 250, capital 150. Part capital ?",
        promptEn: "Payment 400: interest 250, principal 150. Principal share?",
        explanationCorrectFr: "150 / 400 = 37,5 %.",
        explanationCorrectEn: "150 / 400 = 37.5%.",
        difficulty: 2,
        options: [
          opt("37,5 %", "37.5%", true),
          opt("62,5 %", "62.5%", false, "62,5 % est la part intérêts (250/400).", "62.5% is the interest share (250/400)."),
          opt("150 %", "150%", false, "Une part ne peut pas excéder 100 % du paiement.", "A share cannot exceed 100% of payment."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "credit-basics",
    titleFr: "Bases du crédit",
    titleEn: "Credit Basics",
    descriptionFr: "Crédit, historique de paiement et score — notions internationales.",
    descriptionEn: "Credit, payment history, and score — international basics.",
    moduleSlug: "debt",
    sortOrder: 6,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "pf-debt",
    learningObjective: "IDENTIFY",
    isShort: false,
    objectiveFr: "Expliquer le crédit et le rôle du score (ou registre) selon les systèmes nationaux.",
    objectiveEn: "Explain credit and the role of score (or registry) across national systems.",
    explanationFr:
      "Le crédit permet d'emprunter en promettant un remboursement futur. Les prêteurs évaluent la probabilité de remboursement via l'historique (score aux USA/UK, fichiers bancaires en France, etc.). Paiements ponctuels, faible utilisation de carte et ancienneté aident généralement ; retards et défauts pénalisent. Les critères et agences diffèrent selon les pays.",
    explanationEn:
      "Credit lets you borrow with a promise of future repayment. Lenders assess repayment likelihood via history (score in US/UK, banking files in France, etc.). On-time payments, low card utilization, and age of accounts generally help; late payments and defaults hurt. Criteria and agencies differ by country.",
    exampleFr:
      "Score 720 vs 580 sur le même prêt auto : le profil 720 peut obtenir ~6 % ; le 580 peut voir ~12 % (illustration — marchés variables).",
    exampleEn:
      "Score 720 vs 580 on the same auto loan: 720 profile may get ~6%; 580 may see ~12% (illustration — markets vary).",
    practicalFr: "Identifiez dans votre pays : où consulter votre historique et quels facteurs sont suivis.",
    practicalEn: "Identify in your country: where to check your history and which factors are tracked.",
    mistakeFr: "Ouvrir plusieurs comptes crédit juste avant un gros emprunt sans comprendre l'impact.",
    mistakeEn: "Opening several credit accounts just before a large loan without understanding impact.",
    takeawayFr: "Le crédit est une réputation de remboursement — elle influence les conditions offertes.",
    takeawayEn: "Credit is a repayment reputation — it influences offered terms.",
    decisionFr: "Protéger l'historique : paiements à date et utilisation raisonnable des limites.",
    decisionEn: "Protect history: on-time payments and reasonable use of limits.",
    flashcardFrontFr: "Score de crédit",
    flashcardFrontEn: "Credit score",
    flashcardBackFr: "Indicateur de solvabilité basé sur l'historique — définitions variables.",
    flashcardBackEn: "Solvency indicator from history — definitions vary.",
    exercisePromptFr: "Listez trois actions qui améliorent généralement un profil crédit, et une qui le dégrade.",
    exercisePromptEn: "List three actions that generally improve a credit profile, and one that harms it.",
    question: q({
      type: "TRUE_FALSE",
      promptFr: "Des paiements réguliers améliorent généralement le profil crédit.",
      promptEn: "Regular payments generally improve credit profile.",
      explanationCorrectFr: "Vrai : la ponctualité est un facteur clé dans la plupart des systèmes.",
      explanationCorrectEn: "True: punctuality is a key factor in most systems.",
      difficulty: 1,
      options: [
        opt("Vrai", "True", true),
        opt("Faux", "False", false, "Les retards sont généralement pénalisants.", "Late payments are generally penalized."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Utiliser 90 % de la limite de carte en permanence tend à :",
        promptEn: "Permanently using 90% of card limit tends to:",
        explanationCorrectFr: "Signaliser une utilisation élevée — souvent perçue négativement.",
        explanationCorrectEn: "Signal high utilization — often viewed negatively.",
        difficulty: 2,
        options: [
          opt("Augmenter le risque perçu", "Raise perceived risk", true),
          opt("Améliorer automatiquement le score", "Automatically improve score", false, "Utilisation élevée est généralement un signal de risque.", "High utilization is generally a risk signal."),
          opt("N'avoir aucun effet", "Have no effect", false, "L'utilisation des limites est généralement suivie.", "Limit utilization is generally tracked."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "minimum-payments",
    titleFr: "Paiements minimums",
    titleEn: "Minimum Payments",
    descriptionFr: "Ce que le minimum paie vraiment — et ce qu'il laisse en arrière.",
    descriptionEn: "What the minimum really pays — and what it leaves behind.",
    moduleSlug: "debt",
    sortOrder: 7,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "pf-debt",
    learningObjective: "APPLY",
    isShort: false,
    objectiveFr: "Calculer l'effet d'un paiement minimum sur durée et intérêts d'une dette carte.",
    objectiveEn: "Calculate minimum payment effect on term and interest on card debt.",
    explanationFr:
      "Le paiement minimum est le montant le plus faible accepté pour éviter un défaut formel. Il couvre souvent peu ou pas de capital : les intérêts mensuels peuvent absorber la majeure partie. Règles de calcul du minimum (%, seuil fixe) varient par émetteur et pays. Payer seulement le minimum prolonge la dette et augmente les intérêts totaux.",
    explanationEn:
      "The minimum payment is the lowest amount accepted to avoid formal default. It often covers little or no principal: monthly interest may absorb most of it. Minimum calculation rules (%, flat floor) vary by issuer and country. Paying only the minimum extends debt and raises total interest.",
    exampleFr:
      "Solde 2 000, taux 18 % / an → intérêts ~30 / mois. Minimum 50 : seulement ~20 vont au capital. Durée de remboursement : plusieurs années (illustration).",
    exampleEn:
      "Balance 2,000, rate 18% / year → interest ~30 / month. Minimum 50: only ~20 goes to principal. Repayment term: several years (illustration).",
    practicalFr: "Sur une dette carte fictive, comparez minimum vs +50 / mois : durée et intérêts estimés.",
    practicalEn: "On fictional card debt, compare minimum vs +50 / month: estimated term and interest.",
    mistakeFr: "Voir le minimum comme un plan de remboursement « normal ».",
    mistakeEn: "Seeing the minimum as a “normal” repayment plan.",
    takeawayFr: "Le minimum maintient souvent la dette — pas un objectif de remboursement.",
    takeawayEn: "The minimum often keeps debt alive — not a repayment goal.",
    decisionFr: "Fixer un paiement cible au-dessus du minimum quand vous voulez réduire le solde.",
    decisionEn: "Set a target payment above minimum when you want to shrink the balance.",
    flashcardFrontFr: "Paiement minimum",
    flashcardFrontEn: "Minimum payment",
    flashcardBackFr: "Seuil légal/contractuel — souvent insuffisant pour effacer la dette vite.",
    flashcardBackEn: "Legal/contractual floor — often insufficient to clear debt quickly.",
    exercisePromptFr: "Solde 1 500, intérêts ~22 / mois, minimum 40. Capital réduit ce mois ?",
    exercisePromptEn: "Balance 1,500, interest ~22 / month, minimum 40. Principal reduced this month?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Solde 1 800, intérêts mensuels ~27, minimum 35. Capital réduit ce mois ?",
      promptEn: "Balance 1,800, monthly interest ~27, minimum 35. Principal reduced this month?",
      explanationCorrectFr: "35 − 27 = 8 seulement vers le capital.",
      explanationCorrectEn: "35 − 27 = 8 only toward principal.",
      difficulty: 2,
      options: [
        opt("~8", "~8", true),
        opt("~35", "~35", false, "35 inclut les intérêts — pas tout au capital.", "35 includes interest — not all to principal."),
        opt("0 (solde stable)", "0 (stable balance)", false, "8 € réduisent le capital, mais c'est faible.", "8 reduces principal, but it is small."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Payer uniquement le minimum sur une carte à taux élevé tend à :",
        promptEn: "Paying only minimum on high-rate card tends to:",
        explanationCorrectFr: "Prolonger la durée et augmenter les intérêts totaux.",
        explanationCorrectEn: "Extend duration and increase total interest.",
        difficulty: 1,
        options: [
          opt("Prolonger et coûter plus d'intérêts", "Extend and cost more interest", true),
          opt("Effacer la dette en quelques mois", "Clear debt in a few months", false, "Le minimum couvre peu de capital.", "Minimum covers little principal."),
          opt("Éliminer les intérêts", "Eliminate interest", false, "Les intérêts continuent sur le solde restant.", "Interest continues on remaining balance."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "debt-to-income",
    titleFr: "Ratio dette/revenu",
    titleEn: "Debt-to-Income Ratio",
    descriptionFr: "Mesurer la pression des dettes sur le revenu brut.",
    descriptionEn: "Measure debt pressure on gross income.",
    moduleSlug: "debt",
    sortOrder: 8,
    estimatedMinutes: 7,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    isShort: false,
    objectiveFr: "Calculer le DTI et interpréter un niveau élevé ou confortable.",
    objectiveEn: "Calculate DTI and interpret a high or comfortable level.",
    explanationFr:
      "Le ratio dette/revenu (DTI) = paiements mensuels de dettes ÷ revenu brut mensuel. Exemple : dettes 1 500, revenu brut 5 000 → DTI 30 %. Un DTI élevé signale une marge réduite et peut limiter l'accès au crédit. Seuils acceptés par les prêteurs (ex. 36 %, 43 %) varient selon marchés et produits — outil de diagnostic, pas règle universelle.",
    explanationEn:
      "Debt-to-income (DTI) = monthly debt payments ÷ gross monthly income. Example: debts 1,500, gross income 5,000 → DTI 30%. High DTI signals reduced margin and may limit credit access. Lender thresholds (e.g. 36%, 43%) vary by market and product — a diagnostic tool, not a universal rule.",
    exampleFr: "Paiements dettes 1 200, revenu brut 4 000 → DTI = 30 %. À 2 000 de dettes → 50 %.",
    exampleEn: "Debt payments 1,200, gross income 4,000 → DTI = 30%. At 2,000 debts → 50%.",
    practicalFr: "Calculez votre DTI avec revenu brut et tous paiements de dettes récurrents.",
    practicalEn: "Compute your DTI with gross income and all recurring debt payments.",
    mistakeFr: "Utiliser le revenu net ou omettre certaines dettes (auto, étudiant, minimum carte).",
    mistakeEn: "Using net income or omitting some debts (auto, student, card minimum).",
    takeawayFr: "DTI montre combien du revenu brut est déjà « engagé » par les dettes.",
    takeawayEn: "DTI shows how much gross income is already “committed” to debt.",
    decisionFr: "Avant un nouvel emprunt : estimer le DTI après le nouveau paiement.",
    decisionEn: "Before new borrowing: estimate DTI after the new payment.",
    flashcardFrontFr: "DTI",
    flashcardFrontEn: "DTI",
    flashcardBackFr: "Paiements dettes mensuels ÷ revenu brut mensuel.",
    flashcardBackEn: "Monthly debt payments ÷ gross monthly income.",
    exercisePromptFr: "Dettes 1 800, revenu brut 6 000. DTI ? Que signifie 30 % vs 45 % ?",
    exercisePromptEn: "Debts 1,800, gross income 6,000. DTI? What does 30% vs 45% mean?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Dettes 1 500 / mois, revenu brut 5 000. DTI ?",
      promptEn: "Debts 1,500 / month, gross income 5,000. DTI?",
      explanationCorrectFr: "1 500 / 5 000 = 30 %.",
      explanationCorrectEn: "1,500 / 5,000 = 30%.",
      difficulty: 2,
      options: [
        opt("30 %", "30%", true),
        opt("15 %", "15%", false, "1 500/5 000 n'est pas 15 %.", "1,500/5,000 is not 15%."),
        opt("50 %", "50%", false, "50 % serait 2 500 de dettes sur 5 000.", "50% would be 2,500 debts on 5,000."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Un DTI de 40 % signifie que :",
        promptEn: "A DTI of 40% means that:",
        explanationCorrectFr: "40 % du revenu brut sert aux paiements de dettes.",
        explanationCorrectEn: "40% of gross income goes to debt payments.",
        difficulty: 1,
        options: [
          opt("40 % du revenu brut → dettes", "40% of gross income → debts", true),
          opt("La dette totale = 40 % du patrimoine", "Total debt = 40% of net worth", false, "DTI compare flux mensuels, pas patrimoine.", "DTI compares monthly flows, not net worth."),
          opt("Il ne reste que 40 % à vivre", "Only 40% left to live on", false, "40 % va aux dettes — le reste couvre taxes et vie.", "40% goes to debts — remainder covers taxes and life."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "debt-repayment-strategies",
    titleFr: "Stratégies de remboursement",
    titleEn: "Debt Repayment Strategies",
    descriptionFr: "Comparer avalanche, boule de neige et règles de priorisation.",
    descriptionEn: "Compare avalanche, snowball, and prioritization rules.",
    moduleSlug: "debt",
    sortOrder: 9,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "DECIDE",
    isShort: false,
    objectiveFr: "Choisir une stratégie de remboursement cohérente avec coût et motivation.",
    objectiveEn: "Choose a repayment strategy aligned with cost and motivation.",
    explanationFr:
      "Face à plusieurs dettes, trois leviers : (1) payer plus que les minimums, (2) choisir quelle dette cibler en extra, (3) automatiser. Avalanche : priorité au taux le plus élevé (souvent moins d'intérêts totaux). Boule de neige : priorité au plus petit solde (victoires rapides). Hybrides existent. Aucune méthode garantit un résultat — adaptez à votre situation.",
    explanationEn:
      "With several debts, three levers: (1) pay above minimums, (2) pick which debt gets extra, (3) automate. Avalanche: highest rate first (often less total interest). Snowball: smallest balance first (quick wins). Hybrids exist. No method guarantees an outcome — adapt to your situation.",
    exampleFr:
      "Dettes : carte 3 000 à 22 %, auto 8 000 à 6 %, perso 2 000 à 10 %. Extra 150 / mois : avalanche → carte d'abord ; boule de neige → perso (2 000) d'abord.",
    exampleEn:
      "Debts: card 3,000 at 22%, auto 8,000 at 6%, personal 2,000 at 10%. Extra 150 / month: avalanche → card first; snowball → personal (2,000) first.",
    practicalFr: "Listez vos dettes par taux et par solde. Où irait un extra 100 avec chaque méthode ?",
    practicalEn: "List your debts by rate and balance. Where would extra 100 go with each method?",
    mistakeFr: "Changer de méthode chaque mois sans règle stable — perte de momentum.",
    mistakeEn: "Switching methods every month with no stable rule — loss of momentum.",
    takeawayFr: "La bonne stratégie est celle que vous tenez — coût mathématique et motivation comptent.",
    takeawayEn: "The right strategy is one you sustain — math cost and motivation both matter.",
    decisionFr: "Pick une règle (avalanche ou boule de neige), automatisez, suivez mensuellement.",
    decisionEn: "Pick a rule (avalanche or snowball), automate, track monthly.",
    simulatorFr:
      "Ouvrez le simulateur Remboursement de dette de cette leçon : comparez deux mensualités sur un solde et observez la différence de durée et d'intérêts totaux.",
    simulatorEn:
      "Open this lesson's Debt Repayment simulator: compare two monthly payments on a balance and observe the difference in duration and total interest.",
    flashcardFrontFr: "Stratégie avalanche",
    flashcardFrontEn: "Avalanche strategy",
    flashcardBackFr: "Extra vers la dette au taux le plus élevé.",
    flashcardBackEn: "Extra toward highest-rate debt.",
    exercisePromptFr: "Trois dettes : 500 à 24 %, 4 000 à 8 %, 1 200 à 15 %. Priorité avalanche ?",
    exercisePromptEn: "Three debts: 500 at 24%, 4,000 at 8%, 1,200 at 15%. Avalanche priority?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Avec extra disponible, l'avalanche cible en premier :",
      promptEn: "With extra available, avalanche targets first:",
      explanationCorrectFr: "La dette au taux d'intérêt le plus élevé.",
      explanationCorrectEn: "The debt with the highest interest rate.",
      difficulty: 2,
      options: [
        opt("Taux le plus élevé", "Highest rate", true),
        opt("Plus petit solde", "Smallest balance", false, "Plus petit solde = boule de neige, pas avalanche.", "Smallest balance = snowball, not avalanche."),
        opt("Dette la plus ancienne", "Oldest debt", false, "L'ancienneté n'est pas la règle avalanche.", "Age is not the avalanche rule."),
      ],
    }),
    questions: [
      q({
        type: "TRUE_FALSE",
        promptFr: "Automatiser les paiements réduit le risque d'oublier un minimum.",
        promptEn: "Automating payments reduces risk of missing a minimum.",
        explanationCorrectFr: "Vrai : l'automatisation aide la régularité.",
        explanationCorrectEn: "True: automation supports consistency.",
        difficulty: 1,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "Les oublis de minimum peuvent coûter frais et pénalités.", "Missing minimums can cost fees and penalties."),
        ],
      }),
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Carte 22 %, prêt 7 %. Extra 200 : où en avalanche ?",
        promptEn: "Card 22%, loan 7%. Extra 200: where in avalanche?",
        explanationCorrectFr: "Vers la carte à 22 % — taux le plus élevé.",
        explanationCorrectEn: "Toward the 22% card — highest rate.",
        difficulty: 2,
        options: [
          opt("Carte 22 %", "22% card", true),
          opt("Prêt 7 %", "7% loan", false, "7 % est inférieur à 22 %.", "7% is lower than 22%."),
          opt("Diviser 50/50 sans règle", "Split 50/50 with no rule", false, "L'avalanche suit un ordre de taux, pas un split égal.", "Avalanche follows rate order, not equal split."),
        ],
      }),
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Quel levier réduit le plus sûrement les intérêts totaux ?",
        promptEn: "Which lever most reliably cuts total interest?",
        explanationCorrectFr: "Payer plus que les minimums quand c'est possible.",
        explanationCorrectEn: "Paying more than minimums when possible.",
        difficulty: 2,
        options: [
          opt("Payer plus que les minimums", "Pay more than minimums", true),
          opt("Changer de banque chaque mois", "Switch banks every month", false, "Changer souvent n'efface pas les soldes.", "Frequent switching does not erase balances."),
          opt("Ignorer les petites dettes", "Ignore small debts", false, "Les petites dettes peuvent coûter des intérêts.", "Small debts can still cost interest."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "debt-snowball",
    titleFr: "Méthode boule de neige",
    titleEn: "Debt Snowball Method",
    descriptionFr: "Rembourser du plus petit solde au plus grand pour créer du momentum.",
    descriptionEn: "Repay from smallest balance to largest to build momentum.",
    moduleSlug: "debt",
    sortOrder: 10,
    estimatedMinutes: 7,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "APPLY",
    isShort: false,
    objectiveFr: "Appliquer la boule de neige : ordre, rollover et suivi des victoires.",
    objectiveEn: "Apply snowball: order, rollover, and tracking wins.",
    explanationFr:
      "La boule de neige : payez les minimums sur toutes les dettes, puis dirigez tout extra vers le plus petit solde. Une fois effacée, le paiement de cette dette « roule » vers la suivante plus petite. L'effet psychologique (dettes qui disparaissent) motive certains emprunteurs. Elle peut coûter plus d'intérêts qu'une avalanche si le petit solde n'est pas le taux le plus élevé.",
    explanationEn:
      "Snowball: pay minimums on all debts, then send all extra to the smallest balance. Once cleared, that payment “rolls” to the next smallest. The psychological effect (debts vanishing) motivates some borrowers. It may cost more interest than avalanche if the small balance is not the highest rate.",
    exampleFr:
      "Dettes : 400 (carte), 3 500 (auto), 900 (perso). Ordre boule de neige : 400 → 900 → 3 500. Quand 400 est fini, son paiement s'ajoute à l'extra sur 900.",
    exampleEn:
      "Debts: 400 (card), 3,500 (auto), 900 (personal). Snowball order: 400 → 900 → 3,500. When 400 is done, its payment adds to extra on 900.",
    practicalFr: "Classez trois dettes par solde. Simulez le rollover quand la première est payée.",
    practicalEn: "Rank three debts by balance. Simulate rollover when the first is paid off.",
    mistakeFr: "Arrêter les minimums sur les autres dettes pendant que vous ciblez la petite.",
    mistakeEn: "Stopping minimums on other debts while targeting the small one.",
    takeawayFr: "Boule de neige = momentum par victoires rapides, pas optimisation mathématique pure.",
    takeawayEn: "Snowball = momentum through quick wins, not pure math optimization.",
    decisionFr: "Choisir boule de neige si les victoires rapides vous aident à tenir le plan.",
    decisionEn: "Choose snowball if quick wins help you stick to the plan.",
    flashcardFrontFr: "Boule de neige",
    flashcardFrontEn: "Snowball",
    flashcardBackFr: "Extra vers le plus petit solde ; paiement roule ensuite.",
    flashcardBackEn: "Extra to smallest balance; payment then rolls forward.",
    exercisePromptFr: "Soldes 250, 1 800, 600. Ordre boule de neige ? Que roule après le premier ?",
    exercisePromptEn: "Balances 250, 1,800, 600. Snowball order? What rolls after the first?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Soldes : 300, 2 000, 750. Première cible boule de neige ?",
      promptEn: "Balances: 300, 2,000, 750. First snowball target?",
      explanationCorrectFr: "300 — le plus petit solde.",
      explanationCorrectEn: "300 — the smallest balance.",
      difficulty: 1,
      options: [
        opt("300", "300", true),
        opt("750", "750", false, "750 est plus grand que 300.", "750 is larger than 300."),
        opt("2 000", "2,000", false, "2 000 est le plus grand solde.", "2,000 is the largest balance."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Après avoir effacé la dette de 300 (paiement 45), que fait la boule de neige ?",
        promptEn: "After clearing the 300 debt (payment 45), what does snowball do?",
        explanationCorrectFr: "Les 45 s'ajoutent à l'extra sur la prochaine plus petite dette.",
        explanationCorrectEn: "The 45 adds to extra on the next smallest debt.",
        difficulty: 2,
        options: [
          opt("45 roule vers la prochaine petite dette", "45 rolls to next smallest debt", true),
          opt("Arrêter tous paiements", "Stop all payments", false, "Les minimums continuent sur les autres dettes.", "Minimums continue on other debts."),
          opt("Réinvestir en actions", "Reinvest in stocks", false, "Le rollover va vers la dette suivante, pas un placement.", "Rollover goes to next debt, not investment."),
        ],
      }),
      q({
        type: "TRUE_FALSE",
        promptFr: "La boule de neige peut coûter plus d'intérêts qu'une avalanche.",
        promptEn: "Snowball may cost more interest than avalanche.",
        explanationCorrectFr: "Vrai : si le petit solde a un taux bas, l'avalanche serait moins coûteuse en intérêts.",
        explanationCorrectEn: "True: if small balance has a low rate, avalanche would cost less interest.",
        difficulty: 2,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "L'ordre par solde ≠ ordre par taux.", "Balance order ≠ rate order."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "debt-avalanche",
    titleFr: "Méthode avalanche",
    titleEn: "Debt Avalanche Method",
    descriptionFr: "Prioriser le taux le plus élevé pour réduire les intérêts totaux.",
    descriptionEn: "Prioritize highest rate to reduce total interest.",
    moduleSlug: "debt",
    sortOrder: 11,
    estimatedMinutes: 7,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "APPLY",
    isShort: false,
    objectiveFr: "Appliquer l'avalanche : classer par taux, extra ciblé, rollover.",
    objectiveEn: "Apply avalanche: rank by rate, targeted extra, rollover.",
    explanationFr:
      "L'avalanche : minimums sur toutes les dettes, extra vers le taux le plus élevé. Quand cette dette est soldée, l'extra (et souvent son paiement) va vers le prochain taux le plus élevé. Mathématiquement, cela tend à minimiser les intérêts totaux à paiement constant. Demande de la patience si la dette à taux élevé est aussi la plus grande.",
    explanationEn:
      "Avalanche: minimums on all debts, extra to highest rate. When that debt is cleared, extra (and often its payment) goes to the next highest rate. Mathematically, this tends to minimize total interest at constant payment. Requires patience if the high-rate debt is also the largest.",
    exampleFr:
      "Taux : carte 24 % (2 500), auto 5 % (12 000), étudiant 6 % (4 000). Ordre avalanche : carte → étudiant → auto.",
    exampleEn:
      "Rates: card 24% (2,500), auto 5% (12,000), student 6% (4,000). Avalanche order: card → student → auto.",
    practicalFr: "Classez trois dettes par taux décroissant. Où va un extra 75 en avalanche ?",
    practicalEn: "Rank three debts by descending rate. Where does extra 75 go in avalanche?",
    mistakeFr: "Cibler la plus grande dette par frustration, sans regarder le taux.",
    mistakeEn: "Targeting the largest debt out of frustration, without checking rate.",
    takeawayFr: "Avalanche optimise le coût — pas toujours le confort psychologique.",
    takeawayEn: "Avalanche optimizes cost — not always psychological comfort.",
    decisionFr: "Utiliser avalanche si vous privilégiez le coût total et pouvez tenir le plan.",
    decisionEn: "Use avalanche if you prioritize total cost and can stick to the plan.",
    flashcardFrontFr: "Avalanche",
    flashcardFrontEn: "Avalanche",
    flashcardBackFr: "Extra vers le taux le plus élevé ; rollover par taux décroissant.",
    flashcardBackEn: "Extra to highest rate; rollover by descending rate.",
    exercisePromptFr: "Taux 19 %, 8 %, 14 %. Ordre avalanche ? Première cible ?",
    exercisePromptEn: "Rates 19%, 8%, 14%. Avalanche order? First target?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Taux : 21 %, 9 %, 15 %. Première cible avalanche ?",
      promptEn: "Rates: 21%, 9%, 15%. First avalanche target?",
      explanationCorrectFr: "21 % — le taux le plus élevé.",
      explanationCorrectEn: "21% — the highest rate.",
      difficulty: 1,
      options: [
        opt("21 %", "21%", true),
        opt("15 %", "15%", false, "15 % est inférieur à 21 %.", "15% is lower than 21%."),
        opt("9 %", "9%", false, "9 % est le taux le plus bas.", "9% is the lowest rate."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Carte 26 % (petit solde), prêt 7 % (gros solde). Avalanche cible :",
        promptEn: "Card 26% (small balance), loan 7% (large balance). Avalanche targets:",
        explanationCorrectFr: "La carte à 26 % — le taux prime, pas le solde.",
        explanationCorrectEn: "The 26% card — rate trumps balance.",
        difficulty: 2,
        options: [
          opt("Carte 26 %", "26% card", true),
          opt("Prêt 7 % (plus gros)", "7% loan (larger)", false, "La taille ne définit pas l'avalanche.", "Size does not define avalanche."),
          opt("Diviser l'extra également", "Split extra equally", false, "L'avalanche concentre l'extra sur le taux max.", "Avalanche concentrates extra on max rate."),
        ],
      }),
      q({
        type: "TRUE_FALSE",
        promptFr: "L'avalanche tend à réduire les intérêts totaux vs boule de neige (paiement constant).",
        promptEn: "Avalanche tends to cut total interest vs snowball (constant payment).",
        explanationCorrectFr: "Vrai en général — car les taux élevés sont attaqués en premier.",
        explanationCorrectEn: "True in general — high rates are attacked first.",
        difficulty: 2,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "Attaquer les taux élevés réduit généralement les intérêts.", "Attacking high rates generally cuts interest."),
        ],
      }),
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Après effacer la dette à 21 %, l'extra avalanche va vers :",
        promptEn: "After clearing the 21% debt, avalanche extra goes to:",
        explanationCorrectFr: "La dette au prochain taux le plus élevé restant.",
        explanationCorrectEn: "The debt with the next highest remaining rate.",
        difficulty: 2,
        options: [
          opt("Prochain taux le plus élevé", "Next highest rate", true),
          opt("Plus petit solde restant", "Smallest remaining balance", false, "Plus petit solde = logique boule de neige.", "Smallest balance = snowball logic."),
          opt("Dette au taux le plus bas", "Lowest-rate debt", false, "Le taux le plus bas est attaqué en dernier.", "Lowest rate is attacked last."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "refinancing-basics",
    titleFr: "Bases du refinancement",
    titleEn: "Refinancing Basics",
    descriptionFr: "Remplacer un prêt par un nouveau — quand et quoi comparer.",
    descriptionEn: "Replace a loan with a new one — when and what to compare.",
    moduleSlug: "debt",
    sortOrder: 12,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    isShort: false,
    objectiveFr: "Évaluer une offre de refinancement : taux, frais, durée et coût total.",
    objectiveEn: "Evaluate a refinance offer: rate, fees, term, and total cost.",
    explanationFr:
      "Refinancer = contracter un nouveau prêt pour payer l'ancien (taux plus bas, durée différente, consolidation). Avantages possibles : mensualité ou intérêts totaux réduits. Coûts : frais de dossier, pénalités de sortie anticipée, assurance. Comparez le coût total sur la durée, pas seulement le nouveau taux. Règles et produits (rachat, balance transfer) varient fortement selon les pays.",
    explanationEn:
      "Refinancing = taking a new loan to pay off the old one (lower rate, different term, consolidation). Possible benefits: lower payment or total interest. Costs: application fees, early payoff penalties, insurance. Compare total cost over the term, not just the new rate. Rules and products (refinance, balance transfer) vary widely by country.",
    exampleFr:
      "Prêt actuel 8 %, reste 15 000, 4 ans. Offre refinancement 5 %, 4 ans, frais 300. Intérêts totaux futurs + frais vs reste actuel — seul le comparatif total compte.",
    exampleEn:
      "Current loan 8%, 15,000 left, 4 years. Refinance offer 5%, 4 years, 300 fee. Future total interest + fees vs current remainder — only total comparison matters.",
    practicalFr: "Pour une offre fictive, listez : nouveau taux, frais, durée, pénalité sortie ancien prêt.",
    practicalEn: "For a fictional offer, list: new rate, fees, term, old loan exit penalty.",
    mistakeFr: "Refinancer pour baisser la mensualité en allongeant fortement la durée — intérêts totaux en hausse.",
    mistakeEn: "Refinancing to cut monthly payment by sharply extending term — total interest rises.",
    takeawayFr: "Refinancer est un trade-off : taux, durée, frais — pas une victoire automatique.",
    takeawayEn: "Refinancing is a trade-off: rate, term, fees — not an automatic win.",
    decisionFr: "Calculer coût total actuel vs projeté avant de signer un refinancement.",
    decisionEn: "Compute current vs projected total cost before signing a refinance.",
    flashcardFrontFr: "Refinancement",
    flashcardFrontEn: "Refinancing",
    flashcardBackFr: "Nouveau prêt pour remplacer l'ancien — comparer coût total.",
    flashcardBackEn: "New loan to replace old — compare total cost.",
    exercisePromptFr: "Taux baisse 2 points mais durée +3 ans et frais 500. Quelles questions poser ?",
    exercisePromptEn: "Rate drops 2 points but term +3 years and 500 fees. What questions to ask?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Avant de refinancer, la comparaison la plus importante est :",
      promptEn: "Before refinancing, the most important comparison is:",
      explanationCorrectFr: "Coût total (intérêts + frais) sur la durée vs situation actuelle.",
      explanationCorrectEn: "Total cost (interest + fees) over the term vs current situation.",
      difficulty: 2,
      options: [
        opt("Coût total sur la durée", "Total cost over the term", true),
        opt("Seulement le nouveau taux affiché", "Only the new advertised rate", false, "Le taux seul ignore frais et durée.", "Rate alone ignores fees and term."),
        opt("Couleur du formulaire bancaire", "Color of the bank form", false, "Non pertinent pour la décision financière.", "Not relevant to the financial decision."),
      ],
    }),
    questions: [
      q({
        type: "TRUE_FALSE",
        promptFr: "Allonger la durée en refinancement peut augmenter les intérêts totaux.",
        promptEn: "Extending term when refinancing can increase total interest.",
        explanationCorrectFr: "Vrai : mensualité plus basse mais plus de périodes d'intérêts.",
        explanationCorrectEn: "True: lower monthly but more interest periods.",
        difficulty: 2,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "Plus de mois = souvent plus d'intérêts cumulés.", "More months = often more cumulative interest."),
        ],
      }),
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Frais de 400 et pénalité sortie 200. Impact sur l'analyse ?",
        promptEn: "Fees of 400 and exit penalty 200. Impact on analysis?",
        explanationCorrectFr: "Ajouter 600 au coût du refinancement dans la comparaison.",
        explanationCorrectEn: "Add 600 to refinance cost in the comparison.",
        difficulty: 2,
        options: [
          opt("Inclure 600 dans le coût total", "Include 600 in total cost", true),
          opt("Ignorer — seul le taux compte", "Ignore — only rate matters", false, "Les frais changent le coût réel.", "Fees change real cost."),
          opt("Compter seulement la pénalité", "Count only the penalty", false, "Les deux frais doivent être inclus.", "Both fees should be included."),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "cost-of-borrowing",
    titleFr: "Coût de l'emprunt",
    titleEn: "Cost of Borrowing",
    descriptionFr: "Intérêts totaux, frais et prix réel du crédit.",
    descriptionEn: "Total interest, fees, and the real price of credit.",
    moduleSlug: "debt",
    sortOrder: 13,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    isShort: false,
    objectiveFr: "Estimer le coût total d'un emprunt : intérêts, frais et comparaison au capital.",
    objectiveEn: "Estimate total borrowing cost: interest, fees, and comparison to principal.",
    explanationFr:
      "Le coût de l'emprunt = capital remboursé + intérêts + frais (dossier, assurance si obligatoire, pénalités). Exemple : 10 000 sur 5 ans à 7 % → intérêts totaux ~1 880 (illustration) + frais. Le TAEG synthétise une partie de ce coût. Toujours demander : « Combien je paie en plus du capital ? » Les taxes et subventions sur crédit varient selon les pays.",
    explanationEn:
      "Borrowing cost = principal repaid + interest + fees (application, mandatory insurance, penalties). Example: 10,000 over 5 years at 7% → total interest ~1,880 (illustration) + fees. APR summarizes part of this cost. Always ask: “How much do I pay beyond principal?” Credit taxes and subsidies vary by country.",
    exampleFr:
      "1) Auto 20 000, 6 %, 5 ans → ~3 200 d'intérêts (illustration). 2) Carte 5 000 à 20 %, minimum seulement → intérêts bien plus élevés sur durée longue.",
    exampleEn:
      "1) Auto 20,000, 6%, 5 years → ~3,200 interest (illustration). 2) Card 5,000 at 20%, minimum only → much higher interest over long duration.",
    practicalFr: "Pour un prêt fictif, estimez intérêts totaux + frais. Quel % du capital emprunté ?",
    practicalEn: "For a fictional loan, estimate total interest + fees. What % of borrowed principal?",
    mistakeFr: "Ne regarder que la mensualité « abordable » sans le coût total sur la durée.",
    mistakeEn: "Looking only at an “affordable” monthly payment without total cost over the term.",
    takeawayFr: "Le prix réel du crédit = capital + intérêts + frais — la mensualité ne suffit pas.",
    takeawayEn: "Real credit price = principal + interest + fees — monthly payment is not enough.",
    decisionFr: "Comparer coût total avant d'emprunter ; négocier frais et taux quand c'est possible.",
    decisionEn: "Compare total cost before borrowing; negotiate fees and rate when possible.",
    flashcardFrontFr: "Coût total du crédit",
    flashcardFrontEn: "Total credit cost",
    flashcardBackFr: "Capital + intérêts + frais sur la durée.",
    flashcardBackEn: "Principal + interest + fees over the term.",
    exercisePromptFr: "8 000 empruntés, 1 200 d'intérêts, 150 de frais. Coût total ? % au-delà du capital ?",
    exercisePromptEn: "8,000 borrowed, 1,200 interest, 150 fees. Total cost? % beyond principal?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "8 000 empruntés, intérêts 1 200, frais 150. Coût total payé ?",
      promptEn: "8,000 borrowed, interest 1,200, fees 150. Total amount paid?",
      explanationCorrectFr: "8 000 + 1 200 + 150 = 9 350.",
      explanationCorrectEn: "8,000 + 1,200 + 150 = 9,350.",
      difficulty: 2,
      options: [
        opt("9 350", "9,350", true),
        opt("9 200", "9,200", false, "9 200 omet les frais de 150.", "9,200 omits the 150 fees."),
        opt("8 150", "8,150", false, "8 150 ne compte pas les intérêts.", "8,150 does not count interest."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Quel scénario a généralement le coût d'intérêts le plus élevé ?",
        promptEn: "Which scenario generally has the highest interest cost?",
        explanationCorrectFr: "Taux élevé + longue durée + paiements faibles (minimum).",
        explanationCorrectEn: "High rate + long duration + low payments (minimum).",
        difficulty: 2,
        options: [
          opt("Taux élevé, longue durée, minimums", "High rate, long term, minimums", true),
          opt("Taux bas, courte durée, paiements élevés", "Low rate, short term, high payments", false, "Ce profil minimise généralement les intérêts.", "This profile generally minimizes interest."),
          opt("Emprunt remboursé en une semaine", "Loan repaid in one week", false, "Durée très courte limite les intérêts.", "Very short duration limits interest."),
        ],
      }),
      q({
        type: "TRUE_FALSE",
        promptFr: "Le TAEG aide à comparer le coût total entre offres similaires.",
        promptEn: "APR helps compare total cost among similar offers.",
        explanationCorrectFr: "Vrai : il intègre taux et frais usuels dans une mesure comparable.",
        explanationCorrectEn: "True: it integrates rate and usual fees in a comparable measure.",
        difficulty: 1,
        options: [
          opt("Vrai", "True", true),
          opt("Faux", "False", false, "Le TAEG est conçu pour faciliter la comparaison.", "APR is designed to ease comparison."),
        ],
      }),
    ],
  }),
];
