import { buildPfLesson, opt, q } from "./pf-factory";
import type { CompactLesson } from "./compact";
import { PF_FOUNDATIONS_PART1 as PART1 } from "./pf-foundations-part1";

const PART2: CompactLesson[] = [
  buildPfLesson({
    slug: "cash-flow-basics",
    titleFr: "Flux de trésorerie personnel",
    titleEn: "Personal Cash Flow",
    descriptionFr: "Voir l'argent qui entre et sort sur une période.",
    descriptionEn: "See money in and out over a period.",
    moduleSlug: "foundations",
    sortOrder: 7,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "pf-budgeting",
    learningObjective: "ANALYZE",
    objectiveFr: "Calculer un flux de trésorerie mensuel simple (entrées − sorties).",
    objectiveEn: "Compute a simple monthly cash flow (inflows − outflows).",
    explanationFr:
      "Le cash flow personnel = entrées − sorties sur une période. Positif : vous renforcez votre coussin. Négatif : vous piochez dans l'épargne ou la dette. C'est l'indicateur le plus concret du mois — plus parlant qu'un budget théorique non suivi.",
    explanationEn:
      "Personal cash flow = inflows − outflows over a period. Positive: you strengthen your cushion. Negative: you tap savings or debt. It is the most concrete monthly signal — clearer than an untracked theoretical budget.",
    exampleFr: "Entrées 2 600, sorties 2 450 → cash flow +150. Trois mois à −200 signalent un ajustement urgent.",
    exampleEn: "Inflows 2,600, outflows 2,450 → cash flow +150. Three months at −200 signal an urgent adjustment.",
    practicalFr: "Calculez votre cash flow du mois dernier avec relevés bancaires.",
    practicalEn: "Compute last month’s cash flow from your statements.",
    mistakeFr: "Confondre un solde de compte élevé avec un cash flow positif (héritage d'anciens mois).",
    mistakeEn: "Confusing a high account balance with positive cash flow (leftover from prior months).",
    takeawayFr: "Le solde montre le stock ; le cash flow montre la tendance.",
    takeawayEn: "Balance shows stock; cash flow shows the trend.",
    decisionFr: "Savoir si le mois a été positif ou négatif — et pourquoi.",
    decisionEn: "Know whether the month was positive or negative — and why.",
    flashcardFrontFr: "Cash flow",
    flashcardFrontEn: "Cash flow",
    flashcardBackFr: "Entrées − sorties sur une période.",
    flashcardBackEn: "Inflows − outflows over a period.",
    exercisePromptFr: "Entrées 3 100, sorties 3 400. Cash flow ? Quelle action prioritaire ?",
    exercisePromptEn: "Inflows 3,100, outflows 3,400. Cash flow? What is the priority action?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Entrées 3 100, sorties 3 400. Cash flow ?",
      promptEn: "Inflows 3,100, outflows 3,400. Cash flow?",
      explanationCorrectFr: "3 100 − 3 400 = −300.",
      explanationCorrectEn: "3,100 − 3,400 = −300.",
      difficulty: 1,
      options: [
        opt("+300", "+300", false),
        opt("−300", "−300", true),
        opt("3 400", "3,400", false),
      ],
    }),
  }),

  buildPfLesson({
    slug: "emergency-fund",
    titleFr: "Fonds d'urgence",
    titleEn: "Emergency Fund",
    descriptionFr: "Constituer une réserve liquide pour les chocs de vie.",
    descriptionEn: "Build a liquid reserve for life shocks.",
    moduleSlug: "foundations",
    sortOrder: 8,
    estimatedMinutes: 6,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "APPLY",
    isShort: true,
    shortDurationSeconds: 140,
    objectiveFr: "Estimer une cible de fonds d'urgence et où le placer (liquidité).",
    objectiveEn: "Estimate an emergency-fund target and where to keep it (liquidity).",
    explanationFr:
      "Un fonds d'urgence couvre typiquement 3 à 6 mois de dépenses essentielles, dans un compte liquide et accessible. Il évite de vendre des investissements ou d'emprunter cher après un choc (perte d'emploi, réparation). La taille exacte dépend de la stabilité de vos revenus.",
    explanationEn:
      "An emergency fund typically covers 3–6 months of essential expenses in a liquid, accessible account. It avoids selling investments or borrowing expensively after a shock (job loss, repair). Exact size depends on income stability.",
    exampleFr: "Dépenses essentielles 1 800 / mois → cible 3 mois = 5 400 ; 6 mois = 10 800.",
    exampleEn: "Essential expenses 1,800 / month → 3-month target = 5,400; 6 months = 10,800.",
    practicalFr: "Calculez votre cible 3 mois. Quel montant mensuel pour l'atteindre en 12 mois ?",
    practicalEn: "Compute your 3-month target. What monthly amount reaches it in 12 months?",
    mistakeFr: "Placer le fonds d'urgence dans un actif volatil « pour gagner plus ».",
    mistakeEn: "Parking the emergency fund in a volatile asset “to earn more.”",
    takeawayFr: "Liquidité d'abord : le fonds d'urgence doit être disponible, pas maximisé en rendement.",
    takeawayEn: "Liquidity first: the emergency fund must be available, not yield-maximized.",
    decisionFr: "Choisir une cible (ex. 3 mois) et un rythme mensuel de constitution.",
    decisionEn: "Choose a target (e.g. 3 months) and a monthly build pace.",
    flashcardFrontFr: "Fonds d'urgence",
    flashcardFrontEn: "Emergency fund",
    flashcardBackFr: "Réserve liquide pour chocs — souvent 3–6 mois de dépenses essentielles.",
    flashcardBackEn: "Liquid reserve for shocks — often 3–6 months of essential expenses.",
    exercisePromptFr: "Essentiels 2 000 / mois. Cible 3 mois ? Versement mensuel pour y arriver en 10 mois ?",
    exercisePromptEn: "Essentials 2,000 / month. 3-month target? Monthly deposit to reach it in 10 months?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Essentiels 2 000 / mois. Cible 3 mois ?",
      promptEn: "Essentials 2,000 / month. 3-month target?",
      explanationCorrectFr: "2 000 × 3 = 6 000.",
      explanationCorrectEn: "2,000 × 3 = 6,000.",
      difficulty: 1,
      options: [
        opt("2 000", "2,000", false),
        opt("6 000", "6,000", true),
        opt("12 000", "12,000", false, "12 000 serait plutôt 6 mois.", "12,000 would be closer to 6 months."),
      ],
    }),
    questions: [
      q({
        type: "SINGLE_CHOICE",
        promptFr: "Où placer en priorité un fonds d'urgence ?",
        promptEn: "Where should an emergency fund sit first?",
        explanationCorrectFr: "Compte liquide accessible, pas un actif très volatil.",
        explanationCorrectEn: "A liquid accessible account — not a highly volatile asset.",
        difficulty: 1,
        options: [
          opt("Actions très volatiles", "Highly volatile stocks", false),
          opt("Compte liquide accessible", "Liquid accessible account", true),
          opt("Objet de collection", "Collectible item", false),
        ],
      }),
    ],
  }),

  buildPfLesson({
    slug: "saving-rate",
    titleFr: "Taux d'épargne",
    titleEn: "Saving Rate",
    descriptionFr: "Mesurer la part du revenu net mise de côté.",
    descriptionEn: "Measure the share of net income set aside.",
    moduleSlug: "foundations",
    sortOrder: 9,
    estimatedMinutes: 6,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "APPLY",
    objectiveFr: "Calculer et interpréter un taux d'épargne mensuel.",
    objectiveEn: "Compute and interpret a monthly savings rate.",
    explanationFr:
      "Taux d'épargne = épargne / revenu net. C'est un indicateur de trajectoire plus puissant que le solde isolé. Améliorer le taux (même de quelques points) change fortement le long terme grâce à la régularité.",
    explanationEn:
      "Savings rate = savings / net income. It is a stronger trajectory signal than a lone balance. Improving the rate (even a few points) changes the long run through consistency.",
    exampleFr: "Net 2 500, épargne 375 → taux = 15 %.",
    exampleEn: "Net 2,500, savings 375 → rate = 15%.",
    practicalFr: "Calculez votre taux des 2 derniers mois. Quelle variation observez-vous ?",
    practicalEn: "Compute your rate for the last 2 months. What change do you see?",
    mistakeFr: "Compter comme « épargne » un virement vers un compte qui est immédiatement redépensé.",
    mistakeEn: "Counting as “savings” a transfer that is immediately spent again.",
    takeawayFr: "Le taux d'épargne mesure la discipline du mois, pas la chance.",
    takeawayEn: "Savings rate measures the month’s discipline, not luck.",
    decisionFr: "Fixer un taux cible minimal (ex. 10 %) et le suivre 3 mois.",
    decisionEn: "Set a minimum target rate (e.g. 10%) and track it for 3 months.",
    flashcardFrontFr: "Taux d'épargne",
    flashcardFrontEn: "Savings rate",
    flashcardBackFr: "Épargne ÷ revenu net.",
    flashcardBackEn: "Savings ÷ net income.",
    exercisePromptFr: "Net 4 000, épargne 600. Taux ? Que devient-il si l'épargne passe à 800 ?",
    exercisePromptEn: "Net 4,000, savings 600. Rate? What if savings rise to 800?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Net 4 000, épargne 600. Taux ?",
      promptEn: "Net 4,000, savings 600. Rate?",
      explanationCorrectFr: "600 / 4 000 = 15 %.",
      explanationCorrectEn: "600 / 4,000 = 15%.",
      difficulty: 1,
      options: [
        opt("10 %", "10%", false),
        opt("15 %", "15%", true),
        opt("25 %", "25%", false),
      ],
    }),
  }),

  buildPfLesson({
    slug: "saving-habits",
    titleFr: "Habitudes d'épargne",
    titleEn: "Saving Habits",
    descriptionFr: "Automatiser et rendre l'épargne régulière.",
    descriptionEn: "Automate and make saving consistent.",
    moduleSlug: "foundations",
    sortOrder: 10,
    estimatedMinutes: 6,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "APPLY",
    objectiveFr: "Mettre en place une habitude d'épargne automatique réaliste.",
    objectiveEn: "Set up a realistic automatic saving habit.",
    explanationFr:
      "L'épargne régulière bat l'épargne « quand il reste quelque chose ». Automatiser un virement juste après le salaire (payer d'abord soi-même) réduit la dépendance à la volonté. Commencez petit, puis augmentez.",
    explanationEn:
      "Regular saving beats saving “whatever is left.” Automating a transfer right after payday (pay yourself first) reduces reliance on willpower. Start small, then increase.",
    exampleFr: "Virement auto de 150 le jour de paie → 1 800 / an avant même d'y penser.",
    exampleEn: "Auto-transfer 150 on payday → 1,800 / year before you even think about it.",
    practicalFr: "Choisissez un montant que vous pouvez tenir 3 mois sans douleur, et un jour de virement.",
    practicalEn: "Pick an amount you can sustain 3 months without pain, and a transfer day.",
    mistakeFr: "Viser un montant trop ambitieux qui casse l'habitude en deux semaines.",
    mistakeEn: "Aiming for an ambitious amount that breaks the habit in two weeks.",
    takeawayFr: "La régularité bat l'intensité ponctuelle.",
    takeawayEn: "Consistency beats occasional intensity.",
    decisionFr: "Décider d'un montant auto et d'une date — puis le démarrer.",
    decisionEn: "Decide an auto amount and date — then start it.",
    flashcardFrontFr: "Payer d'abord soi-même",
    flashcardFrontEn: "Pay yourself first",
    flashcardBackFr: "Épargner dès réception du revenu, avant les envies.",
    flashcardBackEn: "Save when income arrives, before discretionary spending.",
    exercisePromptFr: "Proposez un plan : montant, fréquence, compte destination, date de démarrage.",
    exercisePromptEn: "Propose a plan: amount, frequency, destination account, start date.",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Quelle pratique soutient le mieux l'épargne régulière ?",
      promptEn: "Which practice best supports regular saving?",
      explanationCorrectFr: "Automatiser un virement après le salaire.",
      explanationCorrectEn: "Automating a transfer after payday.",
      difficulty: 1,
      options: [
        opt("Attendre ce qu'il reste en fin de mois", "Wait for whatever is left at month-end", false),
        opt("Virement automatique dès le salaire", "Automatic transfer on payday", true),
        opt("Épargner seulement après un bonus", "Save only after a bonus", false),
      ],
    }),
  }),

  buildPfLesson({
    slug: "opportunity-cost",
    titleFr: "Coût d'opportunité",
    titleEn: "Opportunity Cost",
    descriptionFr: "Voir ce que vous abandonnez quand vous choisissez une option.",
    descriptionEn: "See what you give up when you choose one option.",
    moduleSlug: "foundations",
    sortOrder: 11,
    estimatedMinutes: 7,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-foundations",
    learningObjective: "ANALYZE",
    objectiveFr: "Identifier le coût d'opportunité d'une dépense ou d'un choix financier.",
    objectiveEn: "Identify the opportunity cost of a spending or financial choice.",
    explanationFr:
      "Le coût d'opportunité est la valeur de la meilleure alternative abandonnée. Acheter un objet à 600, c'est aussi renoncer à 600 d'épargne ou de remboursement de dette. Rendre ce coût visible améliore les décisions sans moraliser.",
    explanationEn:
      "Opportunity cost is the value of the best alternative you give up. Buying a 600 item also means giving up 600 of saving or debt repayment. Making that cost visible improves decisions without moralizing.",
    exampleFr: "600 en gadget vs 600 sur une dette à 18 % / an — le coût d'opportunité inclut les intérêts évités.",
    exampleEn: "600 on a gadget vs 600 on 18%/year debt — opportunity cost includes interest avoided.",
    practicalFr: "Pour un achat non essentiel récent, écrivez l'alternative que vous auriez pu financer.",
    practicalEn: "For a recent non-essential purchase, write the alternative you could have funded.",
    mistakeFr: "Ne compter que le prix affiché et ignorer les alternatives.",
    mistakeEn: "Counting only the sticker price and ignoring alternatives.",
    takeawayFr: "Chaque choix a un « au lieu de » — rendez-le explicite.",
    takeawayEn: "Every choice has an “instead of” — make it explicit.",
    decisionFr: "Avant un achat > 200, nommer l'alternative abandonnée.",
    decisionEn: "Before a purchase > 200, name the alternative you forgo.",
    flashcardFrontFr: "Coût d'opportunité",
    flashcardFrontEn: "Opportunity cost",
    flashcardBackFr: "Valeur de la meilleure option non choisie.",
    flashcardBackEn: "Value of the best option not chosen.",
    exercisePromptFr:
      "Choix : week-end 400 vs remboursement anticipé d'une dette à 12 %. Quel coût d'opportunité qualitative décrivez-vous ?",
    exercisePromptEn:
      "Choice: 400 weekend vs early repayment of 12% debt. What qualitative opportunity cost do you describe?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Acheter un bien à 500 au lieu de rembourser une dette coûteuse illustre surtout :",
      promptEn: "Buying a 500 item instead of repaying expensive debt mainly illustrates:",
      explanationCorrectFr: "Un coût d'opportunité : intérêts et liberté financière reportés.",
      explanationCorrectEn: "Opportunity cost: delayed interest savings and financial freedom.",
      difficulty: 2,
      options: [
        opt("Une absence totale de coût", "A total absence of cost", false),
        opt("Un coût d'opportunité", "An opportunity cost", true),
        opt("Une garantie de rendement", "A guaranteed return", false),
      ],
    }),
  }),

  buildPfLesson({
    slug: "inflation-basics",
    titleFr: "Bases de l'inflation",
    titleEn: "Inflation Basics",
    descriptionFr: "Comprendre la perte de pouvoir d'achat dans le temps.",
    descriptionEn: "Understand purchasing-power loss over time.",
    moduleSlug: "foundations",
    sortOrder: 12,
    estimatedMinutes: 6,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortDurationSeconds: 150,
    objectiveFr: "Expliquer comment l'inflation réduit le pouvoir d'achat d'une épargne non rémunérée.",
    objectiveEn: "Explain how inflation reduces the purchasing power of unrewarded cash.",
    explanationFr:
      "L'inflation est la hausse générale des prix. À 3 % / an, 100 aujourd'hui achètent moins dans 10 ans. Une épargne à 0 % de rendement perd en valeur réelle. Comprendre cela motive la recherche de placements adaptés — sans promesse de performance.",
    explanationEn:
      "Inflation is a general rise in prices. At 3%/year, 100 today buys less in 10 years. Cash earning 0% loses real value. Understanding this motivates suitable placements — without performance promises.",
    exampleFr: "Panier à 100 aujourd'hui ; à +3 % / an ≈ 134 dans 10 ans.",
    exampleEn: "Basket at 100 today; at +3%/year ≈ 134 in 10 years.",
    practicalFr: "Citez un bien dont le prix a clairement monté en 5 ans autour de vous.",
    practicalEn: "Name a good whose price clearly rose over 5 years around you.",
    mistakeFr: "Croire que « garder cash sous le matelas » protège toujours le pouvoir d'achat.",
    mistakeEn: "Believing “cash under the mattress” always protects purchasing power.",
    takeawayFr: "L'inflation taxe silencieusement l'épargne non rémunérée.",
    takeawayEn: "Inflation silently taxes unrewarded cash.",
    decisionFr: "Savoir pourquoi un rendement nul peut être insuffisant sur le long terme.",
    decisionEn: "Know why a zero return can be insufficient over the long term.",
    flashcardFrontFr: "Pouvoir d'achat",
    flashcardFrontEn: "Purchasing power",
    flashcardBackFr: "Quantité de biens/services qu'une somme peut acheter.",
    flashcardBackEn: "Quantity of goods/services a sum can buy.",
    exercisePromptFr: "Si l'inflation est 4 % et votre compte rapporte 1 %, quel est le rendement réel approximatif ?",
    exercisePromptEn: "If inflation is 4% and your account yields 1%, what is approximate real return?",
    question: q({
      type: "SINGLE_CHOICE",
      promptFr: "Inflation 4 %, rendement nominal 1 %. Rendement réel approx. ?",
      promptEn: "Inflation 4%, nominal yield 1%. Approx. real return?",
      explanationCorrectFr: "Environ 1 % − 4 % = −3 %.",
      explanationCorrectEn: "About 1% − 4% = −3%.",
      difficulty: 2,
      options: [
        opt("+3 %", "+3%", false),
        opt("−3 %", "−3%", true),
        opt("+5 %", "+5%", false),
      ],
    }),
  }),
];

export const PF_FOUNDATIONS_LESSONS: CompactLesson[] = [...PART1, ...PART2];
