export type CompactLesson = {
  slug: string;
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  moduleSlug: string;
  sortOrder: number;
  estimatedMinutes: number;
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  skillSlug: string;
  learningObjective: "IDENTIFY" | "APPLY" | "ANALYZE" | "DECIDE";
  isShort?: boolean;
  shortTopic?: string;
  shortDurationSeconds?: number;
  textBodyFr: string;
  textBodyEn: string;
  flashcardFrontFr: string;
  flashcardFrontEn: string;
  flashcardBackFr: string;
  flashcardBackEn: string;
  exercisePromptFr: string;
  exercisePromptEn: string;
  question: {
    type: "SINGLE_CHOICE" | "TRUE_FALSE" | "MULTIPLE_CHOICE";
    promptFr: string;
    promptEn: string;
    explanationCorrectFr: string;
    explanationCorrectEn: string;
    difficulty: number;
    options: Array<{ labelFr: string; labelEn: string; isCorrect: boolean }>;
  };
};

export const PF_MODULES = [
  { slug: "foundations", titleFr: "Fondamentaux", titleEn: "Foundations", category: "FOUNDATIONS", sortOrder: 0 },
  { slug: "debt", titleFr: "Dette et remboursement", titleEn: "Debt & Repayment", category: "DEBT", sortOrder: 1 },
  { slug: "saving-investing", titleFr: "Épargne et investissement", titleEn: "Saving & Investing", category: "INVESTING", sortOrder: 2 },
  { slug: "wealth-building", titleFr: "Construction de patrimoine", titleEn: "Wealth Building", category: "WEALTH_BUILDING", sortOrder: 3 },
];

export const PF_LESSONS: CompactLesson[] = [
  {
    slug: "understanding-income",
    titleFr: "Comprendre les revenus",
    titleEn: "Understanding Income",
    descriptionFr: "Découvrez les différentes sources de revenus et comment les identifier.",
    descriptionEn: "Discover different income sources and how to identify them.",
    moduleSlug: "foundations",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-income",
    learningObjective: "IDENTIFY",
    textBodyFr: "Les revenus proviennent de sources actives (salaire, freelance) ou passives (loyers, dividendes, intérêts). Distinguez les flux récurrents des revenus ponctuels et mesurez le revenu net après impôts. Un diagnostic clair de vos revenus est la première étape avant le budget et l'épargne — contenu pédagogique, pas un conseil personnalisé.",
    textBodyEn: "Income comes from active sources (salary, freelance) or passive sources (rent, dividends, interest). Separate recurring flows from one-off income and measure net income after tax. A clear income picture is the first step before budgeting and saving — educational content, not personalized advice.",
    flashcardFrontFr: "Revenu actif",
    flashcardFrontEn: "Active income",
    flashcardBackFr: "Revenu gagné en échangeant temps ou compétences (ex. salaire).",
    flashcardBackEn: "Income earned by trading time or skills (e.g. salary).",
    exercisePromptFr: "Listez vos trois principales sources de revenus.",
    exercisePromptEn: "List your three main sources of income.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Lequel est un exemple de revenu passif ?",
      promptEn: "Which is an example of passive income?",
      explanationCorrectFr: "Les dividendes sont un revenu passif car ils ne nécessitent pas un échange direct de temps.",
      explanationCorrectEn: "Dividends are passive income because they do not require a direct exchange of time.",
      difficulty: 1,
      options: [
        { labelFr: "Salaire mensuel", labelEn: "Monthly salary", isCorrect: false },
        { labelFr: "Dividendes d'actions", labelEn: "Stock dividends", isCorrect: true },
        { labelFr: "Honoraires freelance", labelEn: "Freelance fees", isCorrect: false },
      ],
    },
  },
  {
    slug: "tracking-expenses",
    titleFr: "Comprendre les dépenses",
    titleEn: "Understanding Expenses",
    descriptionFr: "Apprenez à catégoriser et suivre vos dépenses quotidiennes.",
    descriptionEn: "Learn to categorize and track your daily expenses.",
    moduleSlug: "foundations",
    sortOrder: 1,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-budgeting",
    learningObjective: "IDENTIFY",
    textBodyFr: "Suivre vos dépenses révèle où part votre argent : besoins essentiels, envies et fuites (abonnements, frais bancaires). Classez vos dépenses sur 30 jours, calculez votre taux d'épargne, puis reliez chaque catégorie à une priorité. Ce diagnostic vous aide à construire un budget réaliste — sans jugement ni conseil personnalisé.",
    textBodyEn: "Tracking expenses reveals where money goes: essential needs, wants, and leaks (subscriptions, bank fees). Classify spending for 30 days, compute your savings rate, then link each category to a priority. This diagnosis helps build a realistic budget — without judgment or personalized advice.",
    flashcardFrontFr: "Dépense fixe",
    flashcardFrontEn: "Fixed expense",
    flashcardBackFr: "Dépense récurrente et prévisible (ex. loyer, assurance).",
    flashcardBackEn: "Recurring and predictable expense (e.g. rent, insurance).",
    exercisePromptFr: "Classez 5 dépenses récentes en fixes ou variables.",
    exercisePromptEn: "Classify 5 recent expenses as fixed or variable.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Les dépenses variables changent d'un mois à l'autre.",
      promptEn: "Variable expenses change from month to month.",
      explanationCorrectFr: "Vrai. Les dépenses variables fluctuent selon vos habitudes de consommation.",
      explanationCorrectEn: "True. Variable expenses fluctuate based on your consumption habits.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "needs-vs-wants",
    titleFr: "Besoins vs envies",
    titleEn: "Needs vs Wants",
    descriptionFr: "Distinguez les besoins essentiels des envies pour mieux budgéter.",
    descriptionEn: "Distinguish essential needs from wants to budget better.",
    moduleSlug: "foundations",
    sortOrder: 2,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-budgeting",
    learningObjective: "ANALYZE",
    textBodyFr: "Un besoin est indispensable à la survie ou au fonctionnement quotidien (logement, nourriture, transport essentiel). Une envie améliore le confort mais peut être réduite ou reportée. Cette distinction aide à prioriser en période de contrainte budgétaire. Les frontières varient selon chaque situation — utilisez cet outil comme guide général, pas comme règle absolue.",
    textBodyEn: "A need is essential for survival or daily functioning (housing, food, essential transport). A want improves comfort but can be reduced or delayed. This distinction helps prioritize during budget constraints. Boundaries vary by situation — use this as a general guide, not an absolute rule.",
    flashcardFrontFr: "Besoin essentiel",
    flashcardFrontEn: "Essential need",
    flashcardBackFr: "Dépense indispensable pour vivre ou travailler (ex. logement).",
    flashcardBackEn: "Expense indispensable for living or working (e.g. housing).",
    exercisePromptFr: "Classez cinq dépenses en besoin ou envie.",
    exercisePromptEn: "Classify five expenses as need or want.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel exemple illustre typiquement une envie ?",
      promptEn: "Which example typically illustrates a want?",
      explanationCorrectFr: "Un restaurant gastronomique est une envie, pas un besoin alimentaire de base.",
      explanationCorrectEn: "A fine-dining restaurant is a want, not a basic food need.",
      difficulty: 1,
      options: [
        { labelFr: "Loyer du logement", labelEn: "Housing rent", isCorrect: false },
        { labelFr: "Restaurant gastronomique", labelEn: "Fine-dining restaurant", isCorrect: true },
        { labelFr: "Électricité", labelEn: "Electricity", isCorrect: false },
      ],
    },
  },
  {
    slug: "building-a-budget",
    titleFr: "Construire un budget",
    titleEn: "Building a Budget",
    descriptionFr: "Créez un budget simple basé sur vos revenus et dépenses.",
    descriptionEn: "Create a simple budget based on your income and expenses.",
    moduleSlug: "foundations",
    sortOrder: 3,
    estimatedMinutes: 10,
    difficulty: "BEGINNER",
    skillSlug: "pf-budgeting",
    learningObjective: "APPLY",
    textBodyFr: "Un budget alloue consciemment votre revenu net entre besoins, envies et épargne. Les méthodes 50/30/20 ou par enveloppes fonctionnent si elles sont suivies régulièrement. Incluez une ligne pour le fonds d'urgence avant d'augmenter les investissements risqués. Adaptez les pourcentages à votre situation réelle — ce contenu est pédagogique, pas un plan financier personnalisé.",
    textBodyEn: "A budget consciously allocates net income between needs, wants, and savings. The 50/30/20 or envelope methods work when followed consistently. Include an emergency fund line before increasing risky investments. Adjust percentages to your real situation — this is educational, not a personalized financial plan.",
    flashcardFrontFr: "Règle 50/30/20",
    flashcardFrontEn: "50/30/20 rule",
    flashcardBackFr: "50 % besoins, 30 % envies, 20 % épargne.",
    flashcardBackEn: "50% needs, 30% wants, 20% savings.",
    exercisePromptFr: "Appliquez la règle 50/30/20 à un revenu mensuel de 3 000 €.",
    exercisePromptEn: "Apply the 50/30/20 rule to a monthly income of €3,000.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Dans la règle 50/30/20, que représente le 20 % ?",
      promptEn: "In the 50/30/20 rule, what does the 20% represent?",
      explanationCorrectFr: "Les 20 % sont dédiés à l'épargne et au remboursement de dettes.",
      explanationCorrectEn: "The 20% is dedicated to savings and debt repayment.",
      difficulty: 2,
      options: [
        { labelFr: "Les besoins essentiels", labelEn: "Essential needs", isCorrect: false },
        { labelFr: "Les envies et loisirs", labelEn: "Wants and leisure", isCorrect: false },
        { labelFr: "L'épargne et remboursement de dettes", labelEn: "Savings and debt repayment", isCorrect: true },
      ],
    },
  },
  {
    slug: "emergency-fund",
    titleFr: "Fonds d'urgence",
    titleEn: "Emergency Fund",
    descriptionFr: "Constituer une réserve liquide pour les chocs de vie.",
    descriptionEn: "Build a liquid reserve for life shocks.",
    moduleSlug: "foundations",
    sortOrder: 4,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "APPLY",
    isShort: true,
    shortTopic: "emergency-fund",
    shortDurationSeconds: 155,
    textBodyFr: "Un fonds d'urgence couvre typiquement 3 à 6 mois de dépenses essentielles, placé dans un compte liquide et accessible. Il protège votre plan d'investissement contre les ventes forcées en cas de perte d'emploi ou de réparation majeure. La taille exacte dépend de votre stabilité d'emploi et de vos obligations — contenu éducatif, pas une recommandation personnalisée.",
    textBodyEn: "An emergency fund typically covers 3 to 6 months of essential expenses in a liquid, accessible account. It protects your investment plan from forced sales after job loss or major repairs. The exact size depends on job stability and obligations — educational content, not personalized advice.",
    flashcardFrontFr: "Fonds d'urgence",
    flashcardFrontEn: "Emergency fund",
    flashcardBackFr: "Réserve liquide pour chocs de vie (typiquement 3–6 mois).",
    flashcardBackEn: "Liquid reserve for life shocks (typically 3–6 months).",
    exercisePromptFr: "Estimez 3 mois de dépenses essentielles.",
    exercisePromptEn: "Estimate 3 months of essential expenses.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Où placer idéalement un fonds d'urgence ?",
      promptEn: "Where should an emergency fund ideally sit?",
      explanationCorrectFr: "Dans un placement liquide et accessible rapidement.",
      explanationCorrectEn: "In a liquid account accessible quickly.",
      difficulty: 1,
      options: [
        { labelFr: "Compte liquide accessible", labelEn: "Liquid accessible account", isCorrect: true },
        { labelFr: "Actions très volatiles uniquement", labelEn: "Only highly volatile stocks", isCorrect: false },
        { labelFr: "Cryptomonnaies spéculatives", labelEn: "Speculative cryptocurrencies", isCorrect: false },
      ],
    },
  },
  {
    slug: "saving-habits",
    titleFr: "Habitudes d'épargne",
    titleEn: "Saving Habits",
    descriptionFr: "Développez des routines d'épargne régulières et automatiques.",
    descriptionEn: "Develop regular and automatic saving routines.",
    moduleSlug: "foundations",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "APPLY",
    textBodyFr: "L'épargne régulière transforme de petits montants en capital significatif sur le long terme. Automatiser un virement mensuel vers un compte d'épargne réduit la dépendance à la volonté. Commencez par un montant modeste et augmentez progressivement. Ces principes sont généraux — adaptez-les à votre capacité réelle sans promesse de résultat.",
    textBodyEn: "Regular saving turns small amounts into significant capital over time. Automating a monthly transfer to a savings account reduces reliance on willpower. Start with a modest amount and increase gradually. These are general principles — adapt them to your real capacity without result promises.",
    flashcardFrontFr: "Épargne automatique",
    flashcardFrontEn: "Automatic saving",
    flashcardBackFr: "Virement programmé vers un compte d'épargne chaque mois.",
    flashcardBackEn: "Scheduled transfer to a savings account each month.",
    exercisePromptFr: "Définissez un montant d'épargne automatique mensuel réaliste.",
    exercisePromptEn: "Define a realistic monthly automatic savings amount.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Automatiser l'épargne aide à réduire la dépendance à la volonté.",
      promptEn: "Automating savings helps reduce reliance on willpower.",
      explanationCorrectFr: "Vrai. L'automatisation rend l'épargne une habitude par défaut.",
      explanationCorrectEn: "True. Automation makes saving a default habit.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "inflation-basics",
    titleFr: "Bases de l'inflation",
    titleEn: "Inflation Basics",
    descriptionFr: "Comprenez comment l'inflation affecte votre pouvoir d'achat.",
    descriptionEn: "Understand how inflation affects your purchasing power.",
    moduleSlug: "foundations",
    sortOrder: 6,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-foundations",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "inflation",
    shortDurationSeconds: 140,
    textBodyFr: "L'inflation est la hausse générale des prix qui réduit le pouvoir d'achat de l'argent. À 3 % par an, 100 € aujourd'hui achètent moins dans 10 ans. Une épargne non rémunérée perd en valeur réelle. Comprendre l'inflation aide à choisir des placements adaptés — sans prédire les taux futurs ni conseiller un produit spécifique.",
    textBodyEn: "Inflation is a general rise in prices that reduces money's purchasing power. At 3% per year, €100 today buys less in 10 years. Unrewarded cash savings lose real value. Understanding inflation helps choose suitable placements — without predicting future rates or recommending specific products.",
    flashcardFrontFr: "Inflation",
    flashcardFrontEn: "Inflation",
    flashcardBackFr: "Hausse générale des prix qui réduit le pouvoir d'achat.",
    flashcardBackEn: "General rise in prices that reduces purchasing power.",
    exercisePromptFr: "Expliquez pourquoi 2 % d'inflation annuelle compte sur 20 ans.",
    exercisePromptEn: "Explain why 2% annual inflation matters over 20 years.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'inflation peut réduire la valeur réelle d'une épargne non rémunérée.",
      promptEn: "Inflation can reduce the real value of unrewarded cash savings.",
      explanationCorrectFr: "Vrai. Le même montant achète moins de biens et services.",
      explanationCorrectEn: "True. The same amount buys fewer goods and services.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "understanding-interest",
    titleFr: "Comprendre l'intérêt",
    titleEn: "Understanding Interest",
    descriptionFr: "Découvrez ce que représente l'intérêt dans un prêt ou un placement.",
    descriptionEn: "Discover what interest represents in a loan or investment.",
    moduleSlug: "debt",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-interest",
    learningObjective: "IDENTIFY",
    textBodyFr: "L'intérêt est le coût du temps et du risque pour le prêteur, ou le rendement pour l'investisseur. Le taux d'intérêt exprime ce coût en pourcentage du capital. Sur un prêt, plus le taux est élevé, plus le coût total augmente. Comparer les TAEG aide à évaluer le coût réel — contenu pédagogique, pas un conseil de crédit.",
    textBodyEn: "Interest is the price of time and risk for the lender, or return for the investor. The interest rate expresses this cost as a percentage of principal. On a loan, a higher rate increases total cost. Comparing APR helps assess real cost — educational content, not credit advice.",
    flashcardFrontFr: "Taux d'intérêt",
    flashcardFrontEn: "Interest rate",
    flashcardBackFr: "Pourcentage du capital payé ou gagné sur une période.",
    flashcardBackEn: "Percentage of principal paid or earned over a period.",
    exercisePromptFr: "Calculez l'intérêt simple sur 1 000 € à 5 % pour un an.",
    exercisePromptEn: "Calculate simple interest on €1,000 at 5% for one year.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Que représente principalement le taux d'intérêt d'un prêt ?",
      promptEn: "What does a loan interest rate mainly represent?",
      explanationCorrectFr: "C'est le coût du financement pour l'emprunteur.",
      explanationCorrectEn: "It is the cost of financing for the borrower.",
      difficulty: 1,
      options: [
        { labelFr: "Le coût du financement", labelEn: "The cost of financing", isCorrect: true },
        { labelFr: "Le salaire du conseiller", labelEn: "The advisor salary", isCorrect: false },
        { labelFr: "La TVA", labelEn: "VAT", isCorrect: false },
      ],
    },
  },
  {
    slug: "simple-vs-compound-interest",
    titleFr: "Intérêt simple vs composé",
    titleEn: "Simple vs Compound Interest",
    descriptionFr: "Comparez l'intérêt simple et l'intérêt composé sur le long terme.",
    descriptionEn: "Compare simple and compound interest over the long term.",
    moduleSlug: "debt",
    sortOrder: 1,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-interest",
    learningObjective: "ANALYZE",
    textBodyFr: "L'intérêt simple est calculé uniquement sur le capital initial. L'intérêt composé réinvestit les intérêts déjà gagnés, accélérant la croissance. Sur le long terme, la capitalisation surpasse l'intérêt simple. Cet effet profite aux investisseurs mais aggrave le coût des dettes à taux élevé — illustration pédagogique, pas une projection garantie.",
    textBodyEn: "Simple interest is calculated only on the initial principal. Compound interest reinvests earned interest, accelerating growth. Over time, compounding outpaces simple interest. This benefits investors but worsens high-rate debt costs — pedagogical illustration, not a guaranteed projection.",
    flashcardFrontFr: "Intérêt composé",
    flashcardFrontEn: "Compound interest",
    flashcardBackFr: "Intérêts calculés sur le capital et les intérêts antérieurs.",
    flashcardBackEn: "Interest calculated on principal and prior interest.",
    exercisePromptFr: "Comparez 1 000 € à 5 % simple vs composé sur 10 ans.",
    exercisePromptEn: "Compare €1,000 at 5% simple vs compound over 10 years.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'intérêt composé croît plus vite que l'intérêt simple sur le long terme.",
      promptEn: "Compound interest grows faster than simple interest over the long term.",
      explanationCorrectFr: "Vrai. La capitalisation accélère la croissance avec le temps.",
      explanationCorrectEn: "True. Compounding accelerates growth over time.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "loans-basics",
    titleFr: "Bases des prêts",
    titleEn: "Loans Basics",
    descriptionFr: "Comprenez les éléments clés d'un prêt : capital, taux, durée.",
    descriptionEn: "Understand key loan elements: principal, rate, term.",
    moduleSlug: "debt",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "pf-debt",
    learningObjective: "IDENTIFY",
    textBodyFr: "Un prêt combine trois éléments : le capital emprunté, le taux d'intérêt et la durée de remboursement. L'amortissement peut être constant (mensualités fixes) ou progressif. Le TAEG inclut les frais et donne une vision plus complète du coût. Comparez toujours le coût total, pas seulement le taux affiché — contenu général, pas une recommandation de produit.",
    textBodyEn: "A loan combines three elements: borrowed principal, interest rate, and repayment term. Amortization can be constant (fixed payments) or progressive. APR includes fees and gives a fuller cost picture. Always compare total cost, not just the advertised rate — general content, not a product recommendation.",
    flashcardFrontFr: "TAEG",
    flashcardFrontEn: "APR",
    flashcardBackFr: "Taux annuel effectif global : coût total du crédit.",
    flashcardBackEn: "Annual percentage rate: total cost of credit.",
    exercisePromptFr: "Comparez deux prêts de même montant mais de durées différentes.",
    exercisePromptEn: "Compare two loans with the same principal but different terms.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Que mesure le TAEG ?",
      promptEn: "What does APR measure?",
      explanationCorrectFr: "Le coût total du crédit incluant frais et intérêts.",
      explanationCorrectEn: "Total cost of credit including fees and interest.",
      difficulty: 2,
      options: [
        { labelFr: "Le coût total du crédit", labelEn: "Total cost of credit", isCorrect: true },
        { labelFr: "Le salaire de l'emprunteur", labelEn: "Borrower salary", isCorrect: false },
        { labelFr: "Le prix de l'immobilier", labelEn: "Real estate price", isCorrect: false },
      ],
    },
  },
  {
    slug: "credit-basics",
    titleFr: "Bases du crédit",
    titleEn: "Credit Basics",
    descriptionFr: "Découvrez comment fonctionne le crédit et le score de crédit.",
    descriptionEn: "Discover how credit and credit scores work.",
    moduleSlug: "debt",
    sortOrder: 3,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-debt",
    learningObjective: "IDENTIFY",
    textBodyFr: "Le crédit permet d'emprunter de l'argent en promettant un remboursement futur. Le score de crédit reflète votre historique de paiement et influence les conditions offertes. Un bon score peut réduire le taux, un mauvais score l'augmente. Gérer le crédit responsablement est une compétence financière fondamentale — sans garantie de résultat spécifique.",
    textBodyEn: "Credit lets you borrow money with a promise of future repayment. A credit score reflects payment history and influences offered terms. A good score may lower rates; a poor score raises them. Managing credit responsibly is a core financial skill — without guarantee of a specific outcome.",
    flashcardFrontFr: "Score de crédit",
    flashcardFrontEn: "Credit score",
    flashcardBackFr: "Indicateur de solvabilité basé sur l'historique de paiement.",
    flashcardBackEn: "Solvency indicator based on payment history.",
    exercisePromptFr: "Listez trois actions qui peuvent améliorer un score de crédit.",
    exercisePromptEn: "List three actions that can improve a credit score.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Un historique de paiements réguliers améliore généralement le score de crédit.",
      promptEn: "A history of regular payments generally improves credit score.",
      explanationCorrectFr: "Vrai. La ponctualité des paiements est un facteur clé.",
      explanationCorrectEn: "True. Payment punctuality is a key factor.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "debt-to-income",
    titleFr: "Ratio dette/revenu",
    titleEn: "Debt-to-Income Ratio",
    descriptionFr: "Calculez et interprétez votre ratio dette sur revenu.",
    descriptionEn: "Calculate and interpret your debt-to-income ratio.",
    moduleSlug: "debt",
    sortOrder: 4,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    textBodyFr: "Le ratio dette/revenu (DTI) compare vos paiements mensuels de dettes à votre revenu brut mensuel. Un DTI élevé signale une pression financière et peut limiter l'accès au crédit. Les seuils varient selon les prêteurs et les marchés. Utilisez ce ratio comme outil de diagnostic général — pas comme critère absolu de décision.",
    textBodyEn: "Debt-to-income ratio (DTI) compares monthly debt payments to gross monthly income. A high DTI signals financial pressure and may limit credit access. Thresholds vary by lender and market. Use this ratio as a general diagnostic tool — not an absolute decision criterion.",
    flashcardFrontFr: "Ratio dette/revenu",
    flashcardFrontEn: "Debt-to-income ratio",
    flashcardBackFr: "Paiements mensuels de dettes ÷ revenu brut mensuel.",
    flashcardBackEn: "Monthly debt payments ÷ gross monthly income.",
    exercisePromptFr: "Calculez le DTI avec 1 500 € de dettes et 5 000 € de revenu brut.",
    exercisePromptEn: "Calculate DTI with €1,500 debt payments and €5,000 gross income.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Un DTI de 40 % signifie que…",
      promptEn: "A DTI of 40% means that…",
      explanationCorrectFr: "40 % du revenu brut sert aux paiements de dettes.",
      explanationCorrectEn: "40% of gross income goes to debt payments.",
      difficulty: 2,
      options: [
        { labelFr: "40 % du revenu sert aux dettes", labelEn: "40% of income goes to debts", isCorrect: true },
        { labelFr: "La dette est nulle", labelEn: "Debt is zero", isCorrect: false },
        { labelFr: "Le revenu est insuffisant", labelEn: "Income is insufficient", isCorrect: false },
      ],
    },
  },
  {
    slug: "debt-repayment-strategies",
    titleFr: "Stratégies de remboursement",
    titleEn: "Debt Repayment Strategies",
    descriptionFr: "Comparez avalanche et boule de neige pour rembourser vos dettes.",
    descriptionEn: "Compare avalanche and snowball to repay your debts.",
    moduleSlug: "debt",
    sortOrder: 5,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "DECIDE",
    textBodyFr: "La méthode avalanche priorise la dette au taux le plus élevé (souvent optimale mathématiquement). La boule de neige priorise le plus petit solde (motivation psychologique). Choisissez une règle, automatisez les paiements et suivez votre progression. Aucune méthode garantit un résultat — adaptez à votre situation et votre motivation.",
    textBodyEn: "The avalanche method prioritizes the highest-rate debt (often mathematically optimal). The snowball prioritizes the smallest balance (psychological motivation). Pick a rule, automate payments, and track progress. No method guarantees an outcome — adapt to your situation and motivation.",
    flashcardFrontFr: "Méthode avalanche",
    flashcardFrontEn: "Avalanche method",
    flashcardBackFr: "Rembourser d'abord la dette au taux le plus élevé.",
    flashcardBackEn: "Pay the highest-rate debt first.",
    exercisePromptFr: "Classez trois dettes par priorité avalanche.",
    exercisePromptEn: "Rank three debts by avalanche priority.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'avalanche priorise généralement le taux d'intérêt le plus élevé.",
      promptEn: "Avalanche usually prioritizes the highest interest rate.",
      explanationCorrectFr: "Vrai. C'est le principe de la méthode avalanche.",
      explanationCorrectEn: "True. That is the avalanche method principle.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "good-vs-bad-debt",
    titleFr: "Dette bonne vs mauvaise",
    titleEn: "Good vs Bad Debt",
    descriptionFr: "Distinguez les dettes productives des dettes coûteuses.",
    descriptionEn: "Distinguish productive debt from costly debt.",
    moduleSlug: "debt",
    sortOrder: 6,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-debt",
    learningObjective: "ANALYZE",
    textBodyFr: "Une dette « productive » finance un actif ou une compétence qui peut générer de la valeur (ex. éducation, immobilier locatif). Une dette « coûteuse » finance des consommations avec un taux élevé (ex. crédit revolving). La distinction dépend du contexte et du taux — pas de catégorie absolue. Évaluez chaque dette selon son coût, son usage et votre capacité de remboursement.",
    textBodyEn: "Productive debt finances an asset or skill that may generate value (e.g. education, rental property). Costly debt finances consumption at high rates (e.g. revolving credit). The distinction depends on context and rate — no absolute category. Evaluate each debt by cost, use, and repayment capacity.",
    flashcardFrontFr: "Dette productive",
    flashcardFrontEn: "Productive debt",
    flashcardBackFr: "Dette qui finance un actif ou une compétence génératrice de valeur.",
    flashcardBackEn: "Debt financing an asset or value-generating skill.",
    exercisePromptFr: "Classez trois dettes en productive ou coûteuse.",
    exercisePromptEn: "Classify three debts as productive or costly.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel exemple est typiquement une dette coûteuse ?",
      promptEn: "Which example is typically costly debt?",
      explanationCorrectFr: "Le crédit revolving à taux élevé est typiquement une dette coûteuse.",
      explanationCorrectEn: "High-rate revolving credit is typically costly debt.",
      difficulty: 2,
      options: [
        { labelFr: "Crédit revolving à taux élevé", labelEn: "High-rate revolving credit", isCorrect: true },
        { labelFr: "Prêt étudiant à faible taux", labelEn: "Low-rate student loan", isCorrect: false },
        { labelFr: "Prêt hypothécaire pour résidence", labelEn: "Mortgage for residence", isCorrect: false },
      ],
    },
  },
  {
    slug: "why-save",
    titleFr: "Pourquoi investir",
    titleEn: "Why Invest",
    descriptionFr: "Comprenez pourquoi l'épargne et l'investissement sont essentiels.",
    descriptionEn: "Understand why saving and investing are essential.",
    moduleSlug: "saving-investing",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-investing",
    learningObjective: "IDENTIFY",
    textBodyFr: "L'épargne protège contre les imprévus et finance vos objectifs futurs. L'investissement permet de faire croître le capital sur le long terme, au-delà de ce que l'épargne liquide offre. Un fonds d'urgence précède généralement les investissements risqués. Ces principes sont généraux — pas une recommandation de placement spécifique.",
    textBodyEn: "Savings protect against unexpected events and fund future goals. Investing grows capital over the long term beyond what liquid savings offer. An emergency fund typically precedes risky investments. These are general principles — not a specific placement recommendation.",
    flashcardFrontFr: "Fonds d'urgence",
    flashcardFrontEn: "Emergency fund",
    flashcardBackFr: "Réserve couvrant typiquement 3 à 6 mois de dépenses essentielles.",
    flashcardBackEn: "Reserve typically covering 3 to 6 months of essential expenses.",
    exercisePromptFr: "Listez trois raisons d'épargner avant d'investir.",
    exercisePromptEn: "List three reasons to save before investing.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Combien de mois de dépenses un fonds d'urgence devrait-il couvrir ?",
      promptEn: "How many months of expenses should an emergency fund cover?",
      explanationCorrectFr: "La recommandation standard est de 3 à 6 mois de dépenses essentielles.",
      explanationCorrectEn: "The standard recommendation is 3 to 6 months of essential expenses.",
      difficulty: 1,
      options: [
        { labelFr: "1 mois", labelEn: "1 month", isCorrect: false },
        { labelFr: "3 à 6 mois", labelEn: "3 to 6 months", isCorrect: true },
        { labelFr: "12 mois", labelEn: "12 months", isCorrect: false },
      ],
    },
  },
  {
    slug: "introduction-to-investing",
    titleFr: "Introduction à l'investissement",
    titleEn: "Introduction to Investing",
    descriptionFr: "Découvrez les bases de l'investissement et les classes d'actifs.",
    descriptionEn: "Discover investing basics and asset classes.",
    moduleSlug: "saving-investing",
    sortOrder: 1,
    estimatedMinutes: 10,
    difficulty: "BEGINNER",
    skillSlug: "pf-investing",
    learningObjective: "IDENTIFY",
    textBodyFr: "Investir consiste à faire fructifier votre argent via des actifs (actions, obligations, immobilier). Les actions représentent une part d'entreprise ; les obligations un prêt à un émetteur. Chaque classe d'actif a un profil risque/rendement différent. Commencez par comprendre ces bases avant de choisir — contenu pédagogique, pas un conseil en investissement.",
    textBodyEn: "Investing grows money through assets (stocks, bonds, real estate). Stocks are ownership shares; bonds are loans to an issuer. Each asset class has a different risk/return profile. Understand these basics before choosing — educational content, not investment advice.",
    flashcardFrontFr: "Action",
    flashcardFrontEn: "Stock",
    flashcardBackFr: "Part de propriété dans une entreprise.",
    flashcardBackEn: "Ownership share in a company.",
    exercisePromptFr: "Nommez trois classes d'actifs différentes.",
    exercisePromptEn: "Name three different asset classes.",
    question: {
      type: "MULTIPLE_CHOICE",
      promptFr: "Quels sont des exemples de classes d'actifs ? (Plusieurs réponses)",
      promptEn: "Which are examples of asset classes? (Multiple answers)",
      explanationCorrectFr: "Actions, obligations et immobilier sont des classes d'actifs distinctes.",
      explanationCorrectEn: "Stocks, bonds, and real estate are distinct asset classes.",
      difficulty: 2,
      options: [
        { labelFr: "Actions", labelEn: "Stocks", isCorrect: true },
        { labelFr: "Obligations", labelEn: "Bonds", isCorrect: true },
        { labelFr: "Abonnement Netflix", labelEn: "Netflix subscription", isCorrect: false },
        { labelFr: "Immobilier", labelEn: "Real estate", isCorrect: true },
      ],
    },
  },
  {
    slug: "risk-and-return",
    titleFr: "Risque et rendement",
    titleEn: "Risk and Return",
    descriptionFr: "Comprenez la relation entre risque et rendement potentiel.",
    descriptionEn: "Understand the relationship between risk and potential return.",
    moduleSlug: "saving-investing",
    sortOrder: 2,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-investing",
    learningObjective: "ANALYZE",
    textBodyFr: "En finance, un rendement plus élevé implique généralement un risque plus élevé. Un portefeuille de base combine souvent actions (croissance) et obligations (stabilité relative), selon l'horizon. Votre tolérance au risque dépend de votre horizon et situation — outil pédagogique, pas un conseil personnalisé.",
    textBodyEn: "In finance, higher returns generally imply higher risk. A basic portfolio often combines stocks (growth) and bonds (relative stability), by horizon. Your risk tolerance depends on horizon and situation — educational tool, not personalized advice.",
    flashcardFrontFr: "Tolérance au risque",
    flashcardFrontEn: "Risk tolerance",
    flashcardBackFr: "Capacité et volonté d'accepter des fluctuations de valeur.",
    flashcardBackEn: "Ability and willingness to accept value fluctuations.",
    exercisePromptFr: "Évaluez votre tolérance au risque sur une échelle de 1 à 5.",
    exercisePromptEn: "Rate your risk tolerance on a scale of 1 to 5.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Un rendement plus élevé est généralement associé à un risque plus élevé.",
      promptEn: "Higher returns are generally associated with higher risk.",
      explanationCorrectFr: "Vrai. C'est un principe fondamental de la finance.",
      explanationCorrectEn: "True. This is a fundamental principle of finance.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "stocks-basics",
    titleFr: "Bases des actions",
    titleEn: "Stocks Basics",
    descriptionFr: "Découvrez comment fonctionnent les actions et le marché boursier.",
    descriptionEn: "Discover how stocks and the stock market work.",
    moduleSlug: "saving-investing",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "pf-investing",
    learningObjective: "IDENTIFY",
    textBodyFr: "Une action représente une part de propriété dans une entreprise. Les actionnaires peuvent recevoir des dividendes et bénéficier de la hausse du prix. Le marché boursier permet l'achat et la vente d'actions entre investisseurs. Les prix fluctuent selon les résultats, l'économie et le sentiment — sans garantie de rendement.",
    textBodyEn: "A stock represents an ownership share in a company. Shareholders may receive dividends and benefit from price appreciation. The stock market enables buying and selling shares between investors. Prices fluctuate with results, economy, and sentiment — with no return guarantee.",
    flashcardFrontFr: "Dividende",
    flashcardFrontEn: "Dividend",
    flashcardBackFr: "Distribution de profits aux actionnaires.",
    flashcardBackEn: "Distribution of profits to shareholders.",
    exercisePromptFr: "Expliquez la différence entre dividende et plus-value.",
    exercisePromptEn: "Explain the difference between dividend and capital gain.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Qu'est-ce qu'un dividende ?",
      promptEn: "What is a dividend?",
      explanationCorrectFr: "Une distribution de profits aux actionnaires.",
      explanationCorrectEn: "A distribution of profits to shareholders.",
      difficulty: 1,
      options: [
        { labelFr: "Distribution de profits", labelEn: "Profit distribution", isCorrect: true },
        { labelFr: "Frais de courtage", labelEn: "Brokerage fee", isCorrect: false },
        { labelFr: "Taux d'intérêt d'un prêt", labelEn: "Loan interest rate", isCorrect: false },
      ],
    },
  },
  {
    slug: "bonds-basics",
    titleFr: "Bases des obligations",
    titleEn: "Bonds Basics",
    descriptionFr: "Comprenez les obligations comme outil d'investissement.",
    descriptionEn: "Understand bonds as an investment tool.",
    moduleSlug: "saving-investing",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "pf-investing",
    learningObjective: "IDENTIFY",
    textBodyFr: "Une obligation est un prêt que vous faites à un émetteur (gouvernement ou entreprise). L'émetteur promet des paiements d'intérêts réguliers et le remboursement du capital à l'échéance. Les obligations sont généralement moins volatiles que les actions mais offrent un rendement plus limité. Le risque dépend de la solvabilité de l'émetteur.",
    textBodyEn: "A bond is a loan you make to an issuer (government or company). The issuer promises regular interest payments and principal repayment at maturity. Bonds are generally less volatile than stocks but offer more limited returns. Risk depends on issuer solvency.",
    flashcardFrontFr: "Obligation",
    flashcardFrontEn: "Bond",
    flashcardBackFr: "Prêt à un émetteur avec intérêts et remboursement à l'échéance.",
    flashcardBackEn: "Loan to an issuer with interest and repayment at maturity.",
    exercisePromptFr: "Comparez le risque d'une obligation d'état et d'une obligation d'entreprise.",
    exercisePromptEn: "Compare risk of a government bond and a corporate bond.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Les obligations sont généralement moins volatiles que les actions.",
      promptEn: "Bonds are generally less volatile than stocks.",
      explanationCorrectFr: "Vrai. Les obligations ont typiquement des fluctuations plus faibles.",
      explanationCorrectEn: "True. Bonds typically have lower fluctuations.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "diversification-basics",
    titleFr: "Bases de la diversification",
    titleEn: "Diversification Basics",
    descriptionFr: "Apprenez à répartir vos investissements pour réduire le risque.",
    descriptionEn: "Learn to spread investments to reduce risk.",
    moduleSlug: "saving-investing",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-investing",
    learningObjective: "APPLY",
    isShort: true,
    shortTopic: "diversification",
    shortDurationSeconds: 150,
    textBodyFr: "La diversification réduit le risque global en répartissant les investissements entre classes d'actifs, secteurs et régions. Un portefeuille concentré sur une seule action ou secteur est plus vulnérable. Les fonds indiciels offrent une diversification simple pour les débutants — illustration pédagogique, pas une recommandation de produit.",
    textBodyEn: "Diversification reduces overall risk by spreading investments across asset classes, sectors, and regions. A portfolio concentrated in one stock or sector is more vulnerable. Index funds offer simple diversification for beginners — pedagogical illustration, not a product recommendation.",
    flashcardFrontFr: "Diversification",
    flashcardFrontEn: "Diversification",
    flashcardBackFr: "Répartir les investissements pour réduire le risque global.",
    flashcardBackEn: "Spreading investments to reduce overall risk.",
    exercisePromptFr: "Proposez trois façons de diversifier un portefeuille.",
    exercisePromptEn: "Suggest three ways to diversify a portfolio.",
    question: {
      type: "MULTIPLE_CHOICE",
      promptFr: "Quels sont des exemples de diversification ? (Plusieurs réponses)",
      promptEn: "Which are examples of diversification? (Multiple answers)",
      explanationCorrectFr: "Investir dans différentes classes d'actifs et régions est de la diversification.",
      explanationCorrectEn: "Investing in different asset classes and regions is diversification.",
      difficulty: 2,
      options: [
        { labelFr: "Actions + obligations + immobilier", labelEn: "Stocks + bonds + real estate", isCorrect: true },
        { labelFr: "Tout investir dans une seule action", labelEn: "Investing everything in one stock", isCorrect: false },
        { labelFr: "Investir dans plusieurs pays", labelEn: "Investing in multiple countries", isCorrect: true },
      ],
    },
  },
  {
    slug: "asset-allocation",
    titleFr: "Allocation d'actifs",
    titleEn: "Asset Allocation",
    descriptionFr: "Déterminez la répartition optimale entre classes d'actifs.",
    descriptionEn: "Determine optimal allocation across asset classes.",
    moduleSlug: "saving-investing",
    sortOrder: 6,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-investing",
    learningObjective: "DECIDE",
    textBodyFr: "L'allocation d'actifs définit le pourcentage de chaque classe dans votre portefeuille (ex. 60 % actions, 40 % obligations). Elle dépend de votre horizon, tolérance au risque et objectifs. Rééquilibrer périodiquement maintient la cible. C'est un cadre général — adaptez à votre situation sans promesse de performance.",
    textBodyEn: "Asset allocation defines each class's percentage in your portfolio (e.g. 60% stocks, 40% bonds). It depends on horizon, risk tolerance, and goals. Periodic rebalancing maintains the target. This is a general framework — adapt to your situation without performance promises.",
    flashcardFrontFr: "Allocation d'actifs",
    flashcardFrontEn: "Asset allocation",
    flashcardBackFr: "Répartition du portefeuille entre classes d'actifs.",
    flashcardBackEn: "Portfolio split across asset classes.",
    exercisePromptFr: "Proposez une allocation pour un horizon de 20 ans.",
    exercisePromptEn: "Propose an allocation for a 20-year horizon.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "L'allocation d'actifs dépend principalement de…",
      promptEn: "Asset allocation mainly depends on…",
      explanationCorrectFr: "L'horizon, la tolérance au risque et les objectifs.",
      explanationCorrectEn: "Horizon, risk tolerance, and goals.",
      difficulty: 2,
      options: [
        { labelFr: "Horizon, risque et objectifs", labelEn: "Horizon, risk, and goals", isCorrect: true },
        { labelFr: "La météo", labelEn: "The weather", isCorrect: false },
        { labelFr: "Le signe astrologique", labelEn: "Astrological sign", isCorrect: false },
      ],
    },
  },
  {
    slug: "real-estate-basics",
    titleFr: "Bases de l'immobilier",
    titleEn: "Real Estate Basics",
    descriptionFr: "Découvrez l'immobilier comme classe d'actif d'investissement.",
    descriptionEn: "Discover real estate as an investment asset class.",
    moduleSlug: "saving-investing",
    sortOrder: 7,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-investing",
    learningObjective: "IDENTIFY",
    textBodyFr: "L'immobilier peut générer des revenus (loyers) et une plus-value (hausse de valeur). Il nécessite un capital initial, des frais de maintenance et une liquidité limitée. L'immobilier locatif, les REITs et la résidence principale ont des profils différents. Évaluez le rendement net après frais — contenu général, pas un conseil d'investissement immobilier.",
    textBodyEn: "Real estate can generate income (rent) and capital gains (value appreciation). It requires initial capital, maintenance costs, and has limited liquidity. Rental property, REITs, and primary residence have different profiles. Evaluate net return after fees — general content, not real estate investment advice.",
    flashcardFrontFr: "REIT",
    flashcardFrontEn: "REIT",
    flashcardBackFr: "Société cotée qui investit dans l'immobilier.",
    flashcardBackEn: "Listed company that invests in real estate.",
    exercisePromptFr: "Comparez immobilier direct et REIT sur liquidité et gestion.",
    exercisePromptEn: "Compare direct real estate and REIT on liquidity and management.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Qu'est-ce qu'un REIT ?",
      promptEn: "What is a REIT?",
      explanationCorrectFr: "Une société cotée qui investit dans l'immobilier.",
      explanationCorrectEn: "A listed company that invests in real estate.",
      difficulty: 2,
      options: [
        { labelFr: "Société cotée immobilière", labelEn: "Listed real estate company", isCorrect: true },
        { labelFr: "Type de prêt hypothécaire", labelEn: "Type of mortgage loan", isCorrect: false },
        { labelFr: "Taxe sur l'immobilier", labelEn: "Property tax", isCorrect: false },
      ],
    },
  },
  {
    slug: "compound-interest",
    titleFr: "Intérêt composé",
    titleEn: "Compound Interest",
    descriptionFr: "Comprenez comment l'intérêt composé accélère la croissance du capital.",
    descriptionEn: "Understand how compound interest accelerates capital growth.",
    moduleSlug: "wealth-building",
    sortOrder: 0,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-compounding",
    learningObjective: "ANALYZE",
    isShort: true,
    shortTopic: "compound-interest",
    shortDurationSeconds: 165,
    textBodyFr: "L'intérêt composé réinvestit les intérêts déjà gagnés. Plus l'horizon est long, plus l'effet de capitalisation devient puissant pour construire un patrimoine. C'est le moteur mathématique de la croissance à long terme — illustration pédagogique, pas une projection garantie de votre situation.",
    textBodyEn: "Compound interest reinvests interest already earned. The longer the horizon, the more powerful compounding becomes for building wealth. It is the mathematical engine of long-term growth — pedagogical illustration, not a guaranteed projection of your situation.",
    flashcardFrontFr: "Intérêt composé",
    flashcardFrontEn: "Compound interest",
    flashcardBackFr: "Intérêts calculés sur le capital et les intérêts antérieurs.",
    flashcardBackEn: "Interest calculated on principal and previously earned interest.",
    exercisePromptFr: "Calculez mentalement l'effet approximatif d'un doublement sur 10 ans à ~7 %/an.",
    exercisePromptEn: "Mentally estimate doubling over ~10 years at ~7%/year.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'intérêt composé croît plus vite que l'intérêt simple sur le long terme.",
      promptEn: "Compound interest grows faster than simple interest over the long term.",
      explanationCorrectFr: "Vrai. La capitalisation accélère la croissance avec le temps.",
      explanationCorrectEn: "True. Compounding accelerates growth over time.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "inflation-and-wealth",
    titleFr: "Inflation et patrimoine",
    titleEn: "Inflation and Wealth",
    descriptionFr: "Protégez votre patrimoine contre l'érosion inflationniste.",
    descriptionEn: "Protect your wealth against inflation erosion.",
    moduleSlug: "wealth-building",
    sortOrder: 1,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-wealth-building",
    learningObjective: "ANALYZE",
    textBodyFr: "L'inflation érode le pouvoir d'achat de l'argent non investi. Sur 20 ans, même une inflation modeste réduit significativement la valeur réelle. Les actifs qui croissent au-delà de l'inflation (actions, immobilier) aident à protéger le patrimoine — sans garantie de performance future.",
    textBodyEn: "Inflation erodes purchasing power of uninvested money. Over 20 years, even modest inflation significantly reduces real value. Assets growing beyond inflation (stocks, real estate) help protect wealth — without guarantee of future performance.",
    flashcardFrontFr: "Érosion inflationniste",
    flashcardFrontEn: "Inflation erosion",
    flashcardBackFr: "Réduction du pouvoir d'achat par la hausse des prix.",
    flashcardBackEn: "Reduction of purchasing power through price rises.",
    exercisePromptFr: "Expliquez l'impact de 3 % d'inflation sur 1 000 € en 15 ans.",
    exercisePromptEn: "Explain the impact of 3% inflation on €1,000 over 15 years.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'inflation réduit la valeur réelle d'une épargne non investie.",
      promptEn: "Inflation reduces the real value of uninvested savings.",
      explanationCorrectFr: "Vrai. Le même montant achète moins de biens et services.",
      explanationCorrectEn: "True. The same amount buys fewer goods and services.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "retirement-basics",
    titleFr: "Bases de la retraite",
    titleEn: "Retirement Basics",
    descriptionFr: "Planifiez votre retraite avec des principes simples.",
    descriptionEn: "Plan your retirement with simple principles.",
    moduleSlug: "wealth-building",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-wealth-building",
    learningObjective: "APPLY",
    textBodyFr: "La retraite se prépare par l'horizon long, un taux d'épargne régulier et une allocation diversifiée. Les régimes publics complètent mais rarement suffisent seuls. Commencer tôt maximise l'effet de capitalisation. Estimez vos besoins futurs en incluant l'inflation — cadre pédagogique, pas un plan de retraite personnalisé.",
    textBodyEn: "Retirement is prepared through long horizon, regular savings rate, and diversified allocation. Public systems supplement but rarely suffice alone. Starting early maximizes compounding. Estimate future needs including inflation — pedagogical framework, not a personalized retirement plan.",
    flashcardFrontFr: "Horizon de retraite",
    flashcardFrontEn: "Retirement horizon",
    flashcardBackFr: "Durée entre maintenant et le début de la retraite.",
    flashcardBackEn: "Time between now and retirement start.",
    exercisePromptFr: "Estimez vos besoins mensuels à la retraite.",
    exercisePromptEn: "Estimate your monthly needs at retirement.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Pourquoi commencer tôt à préparer la retraite ?",
      promptEn: "Why start preparing for retirement early?",
      explanationCorrectFr: "Plus d'horizon maximise l'effet de capitalisation.",
      explanationCorrectEn: "More horizon maximizes compounding effect.",
      difficulty: 1,
      options: [
        { labelFr: "Maximiser la capitalisation", labelEn: "Maximize compounding", isCorrect: true },
        { labelFr: "Éviter les impôts", labelEn: "Avoid taxes", isCorrect: false },
        { labelFr: "Réduire le salaire", labelEn: "Reduce salary", isCorrect: false },
      ],
    },
  },
  {
    slug: "long-term-investing",
    titleFr: "Investissement long terme",
    titleEn: "Long-Term Investing",
    descriptionFr: "Adoptez une perspective long terme pour vos investissements.",
    descriptionEn: "Adopt a long-term perspective for your investments.",
    moduleSlug: "wealth-building",
    sortOrder: 3,
    estimatedMinutes: 8,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-investing",
    learningObjective: "DECIDE",
    textBodyFr: "L'investissement long terme (10+ ans) permet de lisser les fluctuations de marché. Les ventes paniquées en période de baisse détruisent souvent les rendements. Une stratégie disciplinée, des contributions régulières et la patience sont des atouts clés — principes généraux, pas une garantie de résultat.",
    textBodyEn: "Long-term investing (10+ years) smooths market fluctuations. Panic selling during downturns often destroys returns. Disciplined strategy, regular contributions, and patience are key assets — general principles, not a result guarantee.",
    flashcardFrontFr: "Investissement long terme",
    flashcardFrontEn: "Long-term investing",
    flashcardBackFr: "Horizon de placement typiquement supérieur à 10 ans.",
    flashcardBackEn: "Investment horizon typically over 10 years.",
    exercisePromptFr: "Expliquez pourquoi la patience est un atout en investissement.",
    exercisePromptEn: "Explain why patience is an asset in investing.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Un horizon long permet de lisser les fluctuations de marché.",
      promptEn: "A long horizon helps smooth market fluctuations.",
      explanationCorrectFr: "Vrai. Le temps réduit l'impact des variations court terme.",
      explanationCorrectEn: "True. Time reduces the impact of short-term variations.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "portfolio-basics",
    titleFr: "Bases du portefeuille",
    titleEn: "Portfolio Basics",
    descriptionFr: "Construisez et gérez un portefeuille d'investissement simple.",
    descriptionEn: "Build and manage a simple investment portfolio.",
    moduleSlug: "wealth-building",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "pf-investing",
    learningObjective: "APPLY",
    textBodyFr: "Un portefeuille regroupe vos investissements selon une allocation cible. Suivez la performance globale, pas chaque actif individuellement. Rééquilibrez quand l'allocation dérive de la cible. Un portefeuille simple et diversifié surpasse souvent une gestion complexe — cadre général, pas un conseil personnalisé.",
    textBodyEn: "A portfolio groups investments by target allocation. Track overall performance, not each asset individually. Rebalance when allocation drifts from target. A simple diversified portfolio often beats complex management — general framework, not personalized advice.",
    flashcardFrontFr: "Rééquilibrage",
    flashcardFrontEn: "Rebalancing",
    flashcardBackFr: "Ajuster le portefeuille pour retrouver l'allocation cible.",
    flashcardBackEn: "Adjust portfolio to restore target allocation.",
    exercisePromptFr: "Définissez une allocation cible simple pour votre portefeuille.",
    exercisePromptEn: "Define a simple target allocation for your portfolio.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Pourquoi rééquilibrer un portefeuille ?",
      promptEn: "Why rebalance a portfolio?",
      explanationCorrectFr: "Pour retrouver l'allocation cible après des mouvements de marché.",
      explanationCorrectEn: "To restore target allocation after market moves.",
      difficulty: 2,
      options: [
        { labelFr: "Retrouver l'allocation cible", labelEn: "Restore target allocation", isCorrect: true },
        { labelFr: "Augmenter les frais", labelEn: "Increase fees", isCorrect: false },
        { labelFr: "Vendre tout", labelEn: "Sell everything", isCorrect: false },
      ],
    },
  },
  {
    slug: "financial-goals",
    titleFr: "Objectifs financiers",
    titleEn: "Financial Goals",
    descriptionFr: "Définissez et priorisez vos objectifs financiers.",
    descriptionEn: "Define and prioritize your financial goals.",
    moduleSlug: "wealth-building",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-wealth-building",
    learningObjective: "DECIDE",
    textBodyFr: "Des objectifs clairs (court, moyen, long terme) guident vos décisions financières. Chaque objectif a un horizon, un montant cible et une priorité. Le fonds d'urgence précède généralement les objectifs d'investissement. Formalisez vos objectifs par écrit — exercice personnel, pas un plan financier certifié.",
    textBodyEn: "Clear goals (short, medium, long term) guide financial decisions. Each goal has a horizon, target amount, and priority. Emergency fund typically precedes investment goals. Write down your goals — personal exercise, not a certified financial plan.",
    flashcardFrontFr: "Objectif financier",
    flashcardFrontEn: "Financial goal",
    flashcardBackFr: "Cible monétaire avec horizon et priorité définis.",
    flashcardBackEn: "Monetary target with defined horizon and priority.",
    exercisePromptFr: "Listez trois objectifs financiers avec horizon et montant.",
    exercisePromptEn: "List three financial goals with horizon and amount.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel objectif précède généralement les investissements risqués ?",
      promptEn: "Which goal typically precedes risky investments?",
      explanationCorrectFr: "Le fonds d'urgence précède généralement les investissements risqués.",
      explanationCorrectEn: "Emergency fund typically precedes risky investments.",
      difficulty: 1,
      options: [
        { labelFr: "Fonds d'urgence", labelEn: "Emergency fund", isCorrect: true },
        { labelFr: "Voiture de luxe", labelEn: "Luxury car", isCorrect: false },
        { labelFr: "Vacances exotiques", labelEn: "Exotic vacation", isCorrect: false },
      ],
    },
  },
  {
    slug: "wealth-habits",
    titleFr: "Habitudes de patrimoine",
    titleEn: "Wealth Habits",
    descriptionFr: "Adoptez des habitudes qui construisent le patrimoine sur le long terme.",
    descriptionEn: "Adopt habits that build wealth over the long term.",
    moduleSlug: "wealth-building",
    sortOrder: 6,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pf-wealth-building",
    learningObjective: "APPLY",
    textBodyFr: "Les habitudes de patrimoine incluent l'épargne automatique, l'investissement régulier, la révision budgétaire et l'éducation financière continue. La constance surpasse l'intensité ponctuelle. Automatiser réduit la dépendance à la motivation — principes généraux pour tous, pas une promesse de richesse.",
    textBodyEn: "Wealth habits include automatic saving, regular investing, budget review, and ongoing financial education. Consistency beats occasional intensity. Automation reduces reliance on motivation — general principles for everyone, not a wealth promise.",
    flashcardFrontFr: "Épargne automatique",
    flashcardFrontEn: "Automatic saving",
    flashcardBackFr: "Virement programmé vers investissement ou épargne.",
    flashcardBackEn: "Scheduled transfer to investment or savings.",
    exercisePromptFr: "Listez trois habitudes de patrimoine à adopter.",
    exercisePromptEn: "List three wealth habits to adopt.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "La constance surpasse l'intensité ponctuelle en finance personnelle.",
      promptEn: "Consistency beats occasional intensity in personal finance.",
      explanationCorrectFr: "Vrai. Les petites actions régulières créent de grands résultats.",
      explanationCorrectEn: "True. Small regular actions create large results.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
];
