export type CompactLesson = {
  slug: string;
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  moduleSlug: string;
  sortOrder: number;
  estimatedMinutes: number;
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  skillSlug: string;
  learningObjective: "IDENTIFY" | "APPLY" | "ANALYZE" | "DECIDE";
  isShort?: boolean;
  shortTopic?: string;
  shortDurationSeconds?: number;
  textBodyFr: string;
  textBodyEn: string;
  flashcardFrontFr: string;
  flashcardFrontEn: string;
  flashcardBackFr: string;
  flashcardBackEn: string;
  exercisePromptFr: string;
  exercisePromptEn: string;
  question: {
    type: "SINGLE_CHOICE" | "TRUE_FALSE" | "MULTIPLE_CHOICE";
    promptFr: string;
    promptEn: string;
    explanationCorrectFr: string;
    explanationCorrectEn: string;
    difficulty: number;
    options: Array<{ labelFr: string; labelEn: string; isCorrect: boolean }>;
  };
  /** Optional situational mini-case for SITUATIONAL module */
  situation?: {
    scenarioFr: string;
    scenarioEn: string;
    bestActionFr: string;
    bestActionEn: string;
  };
};

export const PMP_MODULES: Array<{
  slug: string;
  titleFr: string;
  titleEn: string;
  category: string;
  sortOrder: number;
  descriptionFr: string;
  descriptionEn: string;
}> = [
  {
    slug: "foundations",
    titleFr: "Fondamentaux",
    titleEn: "Foundations",
    category: "FOUNDATIONS",
    sortOrder: 0,
    descriptionFr: "Définitions, rôles clés et distinction projet vs opération.",
    descriptionEn: "Definitions, key roles, and project vs operations distinction.",
  },
  {
    slug: "people",
    titleFr: "People",
    titleEn: "People",
    category: "PEOPLE",
    sortOrder: 1,
    descriptionFr: "Leadership, équipe, communication, parties prenantes et collaboration.",
    descriptionEn: "Leadership, team, communication, stakeholders, and collaboration.",
  },
  {
    slug: "process",
    titleFr: "Process",
    titleEn: "Process",
    category: "PROCESS",
    sortOrder: 2,
    descriptionFr: "Planification, périmètre, planning, coûts, risques, qualité et intégration.",
    descriptionEn: "Planning, scope, schedule, cost, risk, quality, and integration.",
  },
  {
    slug: "business-environment",
    titleFr: "Environnement business",
    titleEn: "Business Environment",
    category: "BUSINESS_ENVIRONMENT",
    sortOrder: 3,
    descriptionFr: "Gouvernance, conformité, bénéfices et valeur business.",
    descriptionEn: "Governance, compliance, benefits, and business value.",
  },
  {
    slug: "agile",
    titleFr: "Agile",
    titleEn: "Agile",
    category: "AGILE",
    sortOrder: 4,
    descriptionFr: "Mindset agile, livraison itérative, backlog et rétrospective.",
    descriptionEn: "Agile mindset, iterative delivery, backlog, and retrospective.",
  },
  {
    slug: "hybrid",
    titleFr: "Hybride",
    titleEn: "Hybrid",
    category: "HYBRID",
    sortOrder: 5,
    descriptionFr: "Combiner approches prédictives et adaptatives selon le contexte.",
    descriptionEn: "Combine predictive and adaptive approaches by context.",
  },
  {
    slug: "situational-thinking",
    titleFr: "Pensée situationnelle",
    titleEn: "Situational Thinking",
    category: "SITUATIONAL",
    sortOrder: 6,
    descriptionFr: "Mini-cas pour raisonner la meilleure action, pas mémoriser.",
    descriptionEn: "Mini-cases to reason the best action, not memorize.",
  },
];

export const PMP_LESSONS: CompactLesson[] = [
  {
    slug: "what-is-project-management",
    titleFr: "Qu'est-ce que la gestion de projet ?",
    titleEn: "What is Project Management?",
    descriptionFr: "Découvrez la définition et les objectifs de la gestion de projet.",
    descriptionEn: "Discover the definition and objectives of project management.",
    moduleSlug: "foundations",
    sortOrder: 0,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pmp-foundations",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "project-management",
    shortDurationSeconds: 155,
    textBodyFr:
      "Un projet est une initiative temporaire visant à produire un résultat unique : un produit, un service ou un changement mesurable. La gestion de projet coordonne ressources, délais et risques pour atteindre des objectifs définis, puis se termine. Les opérations courantes, par contraste, sont répétitives et permanentes. Comprendre cette distinction aide à choisir les bons outils et le bon niveau de formalisme.",
    textBodyEn:
      "A project is a temporary initiative to produce a unique result: a product, service, or measurable change. Project management coordinates resources, time, and risk to reach defined objectives, then ends. Ongoing operations, by contrast, are repetitive and permanent. Understanding this distinction helps choose the right tools and level of formality.",
    flashcardFrontFr: "Projet",
    flashcardFrontEn: "Project",
    flashcardBackFr: "Initiative temporaire créant un résultat unique.",
    flashcardBackEn: "Temporary initiative creating a unique result.",
    exercisePromptFr: "Identifiez un projet et une opération courante dans votre organisation.",
    exercisePromptEn: "Identify one project and one ongoing operation in your organization.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quelle caractéristique distingue un projet d'une opération courante ?",
      promptEn: "Which characteristic distinguishes a project from ongoing operations?",
      explanationCorrectFr: "Un projet est temporaire et produit un résultat unique.",
      explanationCorrectEn: "A project is temporary and produces a unique result.",
      difficulty: 1,
      options: [
        { labelFr: "Il est permanent", labelEn: "It is permanent", isCorrect: false },
        { labelFr: "Il est temporaire et unique", labelEn: "It is temporary and unique", isCorrect: true },
        { labelFr: "Il n'a pas d'objectif", labelEn: "It has no objective", isCorrect: false },
      ],
    },
  },
  {
    slug: "project-roles",
    titleFr: "Rôles et responsabilités",
    titleEn: "Project Roles and Responsibilities",
    descriptionFr: "Comprenez les rôles clés dans un projet.",
    descriptionEn: "Understand key roles in a project.",
    moduleSlug: "foundations",
    sortOrder: 1,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pmp-foundations",
    learningObjective: "IDENTIFY",
    textBodyFr:
      "Les rôles essentiels incluent le sponsor (autorité, financement et levée des obstacles), le chef de projet (coordination quotidienne et intégration), et l'équipe projet (exécution des livrables). Les parties prenantes influencent ou sont touchées par le projet sans toujours exécuter. Des responsabilités claires réduisent les conflits et accélèrent les décisions.",
    textBodyEn:
      "Essential roles include the sponsor (authority, funding, and escalation), the project manager (day-to-day coordination and integration), and the project team (deliverable execution). Stakeholders influence or are affected by the project without always executing work. Clear responsibilities reduce conflict and speed decisions.",
    flashcardFrontFr: "Sponsor",
    flashcardFrontEn: "Sponsor",
    flashcardBackFr: "Fournit ressources, autorité et soutien au projet.",
    flashcardBackEn: "Provides resources, authority, and support for the project.",
    exercisePromptFr: "Décrivez le rôle du chef de projet dans un projet que vous connaissez.",
    exercisePromptEn: "Describe the project manager's role in a project you know.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Le sponsor est responsable de la coordination quotidienne du projet.",
      promptEn: "The sponsor is responsible for day-to-day project coordination.",
      explanationCorrectFr: "Faux. La coordination quotidienne est du ressort du chef de projet.",
      explanationCorrectEn: "False. Day-to-day coordination is the project manager's responsibility.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: false },
        { labelFr: "Faux", labelEn: "False", isCorrect: true },
      ],
    },
  },
  {
    slug: "leadership",
    titleFr: "Leadership en projet",
    titleEn: "Leadership in Projects",
    descriptionFr: "Inspirer, orienter et créer un environnement où l'équipe performe.",
    descriptionEn: "Inspire, guide, and create an environment where the team performs.",
    moduleSlug: "people",
    sortOrder: 0,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "leadership",
    learningObjective: "APPLY",
    textBodyFr:
      "Le leadership en projet ne repose pas uniquement sur l'autorité hiérarchique : il combine vision claire, exemplarité et capacité à mobiliser. Un bon leader adapte son style (directif, participatif, délégatif) au maturité de l'équipe et au contexte. Il protège l'équipe des distractions tout en restant transparent sur les contraintes. Le leadership sert les objectifs du projet, pas l'ego du leader.",
    textBodyEn:
      "Project leadership is not only hierarchical authority: it combines clear vision, role modeling, and the ability to mobilize. A good leader adapts style (directive, participative, delegating) to team maturity and context. They shield the team from distractions while staying transparent about constraints. Leadership serves project goals, not the leader's ego.",
    flashcardFrontFr: "Leadership adaptatif",
    flashcardFrontEn: "Adaptive leadership",
    flashcardBackFr: "Ajuster le style de leadership au contexte et à la maturité de l'équipe.",
    flashcardBackEn: "Adjust leadership style to context and team maturity.",
    exercisePromptFr: "Décrivez une situation où un style participatif est plus approprié qu'un style directif.",
    exercisePromptEn: "Describe a situation where a participative style is more appropriate than a directive one.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel comportement illustre le leadership en projet ?",
      promptEn: "Which behavior illustrates project leadership?",
      explanationCorrectFr: "Clarifier la vision et aider l'équipe à surmonter les obstacles sert le projet.",
      explanationCorrectEn: "Clarifying vision and helping the team overcome obstacles serves the project.",
      difficulty: 2,
      options: [
        { labelFr: "Centraliser toutes les décisions sans consultation", labelEn: "Centralize all decisions without consultation", isCorrect: false },
        { labelFr: "Clarifier la vision et lever les obstacles pour l'équipe", labelEn: "Clarify vision and remove obstacles for the team", isCorrect: true },
        { labelFr: "Éviter toute communication sur les contraintes", labelEn: "Avoid any communication about constraints", isCorrect: false },
      ],
    },
  },
  {
    slug: "team-development",
    titleFr: "Développement d'équipe",
    titleEn: "Team Development",
    descriptionFr: "Construire une équipe performante et gérer les phases de maturation.",
    descriptionEn: "Build a performing team and manage maturity phases.",
    moduleSlug: "people",
    sortOrder: 1,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "team-development",
    learningObjective: "ANALYZE",
    textBodyFr:
      "Les équipes évoluent typiquement de la formation à la performance : accueil, conflit, normalisation, performance et dissolution. Reconnaître la phase actuelle permet d'intervenir utilement — faciliter l'alignement en phase de conflit, renforcer l'autonomie en phase de performance. Le développement d'équipe inclut compétences, confiance et règles de travail partagées.",
    textBodyEn:
      "Teams typically evolve from forming to performing: forming, conflict, norming, performing, and adjourning. Recognizing the current phase enables useful intervention — facilitating alignment during conflict, reinforcing autonomy during performance. Team development includes skills, trust, and shared working agreements.",
    flashcardFrontFr: "Phase de normalisation",
    flashcardFrontEn: "Norming phase",
    flashcardBackFr: "L'équipe établit des normes et des modes de collaboration.",
    flashcardBackEn: "The team establishes norms and collaboration patterns.",
    exercisePromptFr: "Identifiez la phase d'évolution d'une équipe que vous observez actuellement.",
    exercisePromptEn: "Identify the development phase of a team you currently observe.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "En phase de conflit initial, quelle intervention est généralement la plus utile ?",
      promptEn: "During early conflict phase, which intervention is generally most useful?",
      explanationCorrectFr: "Faciliter l'alignement sur objectifs et règles aide à traverser le conflit constructif.",
      explanationCorrectEn: "Facilitating alignment on goals and rules helps navigate constructive conflict.",
      difficulty: 2,
      options: [
        { labelFr: "Ignorer les tensions pour gagner du temps", labelEn: "Ignore tensions to save time", isCorrect: false },
        { labelFr: "Faciliter l'alignement sur objectifs et règles", labelEn: "Facilitate alignment on goals and rules", isCorrect: true },
        { labelFr: "Dissoudre immédiatement l'équipe", labelEn: "Immediately dissolve the team", isCorrect: false },
      ],
    },
  },
  {
    slug: "conflict-management-basics",
    titleFr: "Bases de la gestion des conflits",
    titleEn: "Conflict Management Basics",
    descriptionFr: "Comprendre les sources de conflit et les modes de résolution.",
    descriptionEn: "Understand conflict sources and resolution modes.",
    moduleSlug: "people",
    sortOrder: 2,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "conflict-management",
    learningObjective: "DECIDE",
    isShort: true,
    shortTopic: "conflict-management",
    shortDurationSeconds: 130,
    textBodyFr:
      "Les conflits en projet naissent souvent de priorités, ressources, valeurs ou informations incomplètes — pas seulement d'ego. Les modes de résolution vont de l'évitement à la collaboration ; la collaboration vise une solution gagnant-gagnant quand le temps et la relation comptent. Un conflit bien géré peut améliorer la décision ; un conflit ignoré peut paralyser la livraison.",
    textBodyEn:
      "Project conflicts often arise from priorities, resources, values, or incomplete information — not only ego. Resolution modes range from avoidance to collaboration; collaboration seeks win-win when time and relationship matter. Well-managed conflict can improve decisions; ignored conflict can stall delivery.",
    flashcardFrontFr: "Collaboration (conflit)",
    flashcardFrontEn: "Collaboration (conflict)",
    flashcardBackFr: "Rechercher une solution qui satisfait les intérêts de toutes les parties.",
    flashcardBackEn: "Seek a solution satisfying all parties' interests.",
    exercisePromptFr: "Choisissez le mode de résolution adapté à un conflit technique entre pairs experts.",
    exercisePromptEn: "Choose the resolution mode suited to a technical conflict between expert peers.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Pour un conflit technique entre experts avec temps limité, quel mode est souvent prioritaire ?",
      promptEn: "For a technical conflict between experts with limited time, which mode is often prioritized?",
      explanationCorrectFr: "La collaboration ou la négociation constructive cherche le meilleur résultat technique.",
      explanationCorrectEn: "Collaboration or constructive negotiation seeks the best technical outcome.",
      difficulty: 2,
      options: [
        { labelFr: "Évitement total", labelEn: "Total avoidance", isCorrect: false },
        { labelFr: "Collaboration ou négociation constructive", labelEn: "Collaboration or constructive negotiation", isCorrect: true },
        { labelFr: "Imposer la solution du chef de projet sans discussion", labelEn: "Impose the PM's solution without discussion", isCorrect: false },
      ],
    },
  },
  {
    slug: "communication",
    titleFr: "Communication en projet",
    titleEn: "Project Communication",
    descriptionFr: "Planifier et exécuter une communication efficace avec les parties prenantes.",
    descriptionEn: "Plan and execute effective communication with stakeholders.",
    moduleSlug: "people",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "communication",
    learningObjective: "APPLY",
    textBodyFr:
      "La communication en projet couvre qui informer, quoi dire, quand, par quel canal et avec quel feedback. Un plan de communication aligne format et fréquence aux besoins des audiences : sponsor, équipe, clients, régulateurs. La transparence sur statut, risques et changements réduit l'anxiété et les rumeurs. Écouter activement est aussi essentiel que diffuser l'information.",
    textBodyEn:
      "Project communication covers who to inform, what to say, when, through which channel, and with what feedback. A communication plan aligns format and frequency to audience needs: sponsor, team, clients, regulators. Transparency on status, risks, and changes reduces anxiety and rumors. Active listening is as essential as broadcasting information.",
    flashcardFrontFr: "Plan de communication",
    flashcardFrontEn: "Communication plan",
    flashcardBackFr: "Document qui définit audiences, messages, canaux et fréquence.",
    flashcardBackEn: "Document defining audiences, messages, channels, and frequency.",
    exercisePromptFr: "Définissez le canal et la fréquence idéale pour informer le sponsor d'un projet.",
    exercisePromptEn: "Define the ideal channel and frequency to inform a project sponsor.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Un plan de communication doit être adapté aux besoins de chaque audience.",
      promptEn: "A communication plan should be tailored to each audience's needs.",
      explanationCorrectFr: "Vrai. Sponsor, équipe et clients ont des besoins d'information différents.",
      explanationCorrectEn: "True. Sponsors, teams, and clients have different information needs.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "stakeholders-basics",
    titleFr: "Qu'est-ce qu'une partie prenante ?",
    titleEn: "What is a Stakeholder?",
    descriptionFr: "Identifier les parties prenantes et leur influence sur le projet.",
    descriptionEn: "Identify stakeholders and their influence on the project.",
    moduleSlug: "people",
    sortOrder: 4,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "stakeholder-engagement",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "stakeholders",
    shortDurationSeconds: 120,
    textBodyFr:
      "Une partie prenante est toute personne ou groupe qui influence le projet ou est affecté par ses résultats : utilisateurs, finance, juridique, opérations, communautés locales. L'analyse d'influence et d'intérêt aide à prioriser l'engagement : haute influence et haute intérêt nécessitent une collaboration étroite. Ignorer une partie prenante clé est une source fréquente d'échec.",
    textBodyEn:
      "A stakeholder is any person or group that influences the project or is affected by its results: users, finance, legal, operations, local communities. Influence and interest analysis helps prioritize engagement: high influence and high interest require close collaboration. Ignoring a key stakeholder is a frequent source of failure.",
    flashcardFrontFr: "Partie prenante",
    flashcardFrontEn: "Stakeholder",
    flashcardBackFr: "Personne ou groupe qui influence ou est affecté par le projet.",
    flashcardBackEn: "Person or group that influences or is affected by the project.",
    exercisePromptFr: "Listez cinq parties prenantes d'un projet logiciel interne.",
    exercisePromptEn: "List five stakeholders for an internal software project.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Qui est une partie prenante d'un projet ?",
      promptEn: "Who is a project stakeholder?",
      explanationCorrectFr: "Toute personne influencée ou capable d'influencer le projet.",
      explanationCorrectEn: "Anyone affected by or able to influence the project.",
      difficulty: 1,
      options: [
        { labelFr: "Seulement l'équipe projet", labelEn: "Only the project team", isCorrect: false },
        { labelFr: "Quiconque influence ou est affecté par le projet", labelEn: "Anyone who influences or is affected by the project", isCorrect: true },
        { labelFr: "Uniquement le sponsor", labelEn: "Only the sponsor", isCorrect: false },
      ],
    },
  },
  {
    slug: "motivation",
    titleFr: "Motivation de l'équipe",
    titleEn: "Team Motivation",
    descriptionFr: "Comprendre les leviers de motivation et de engagement.",
    descriptionEn: "Understand motivation and engagement levers.",
    moduleSlug: "people",
    sortOrder: 5,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "motivation",
    learningObjective: "APPLY",
    textBodyFr:
      "La motivation combine facteurs intrinsèques (autonomie, maîtrise, purpose) et extrinsèques (reconnaissance, récompenses). Les individus ne sont pas motivés par la même chose : certains valorisent la croissance, d'autres la stabilité ou la visibilité. Reconnaître les contributions, donner du feedback constructif et connecter le travail aux objectifs du projet renforcent l'engagement durable.",
    textBodyEn:
      "Motivation combines intrinsic factors (autonomy, mastery, purpose) and extrinsic ones (recognition, rewards). Individuals are not motivated by the same things: some value growth, others stability or visibility. Recognizing contributions, giving constructive feedback, and connecting work to project goals reinforce sustainable engagement.",
    flashcardFrontFr: "Motivation intrinsèque",
    flashcardFrontEn: "Intrinsic motivation",
    flashcardBackFr: "Engagement tiré du travail lui-même : autonomie, maîtrise, purpose.",
    flashcardBackEn: "Engagement drawn from the work itself: autonomy, mastery, purpose.",
    exercisePromptFr: "Identifiez un levier de motivation intrinsèque pour un membre de votre équipe.",
    exercisePromptEn: "Identify one intrinsic motivation lever for a member of your team.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel élément renforce typiquement la motivation intrinsèque ?",
      promptEn: "Which element typically strengthens intrinsic motivation?",
      explanationCorrectFr: "L'autonomie et un purpose clair renforcent l'engagement intrinsèque.",
      explanationCorrectEn: "Autonomy and clear purpose strengthen intrinsic engagement.",
      difficulty: 2,
      options: [
        { labelFr: "Micro-management constant", labelEn: "Constant micromanagement", isCorrect: false },
        { labelFr: "Autonomie et purpose clair", labelEn: "Autonomy and clear purpose", isCorrect: true },
        { labelFr: "Absence totale de feedback", labelEn: "Complete absence of feedback", isCorrect: false },
      ],
    },
  },
  {
    slug: "collaboration",
    titleFr: "Collaboration et travail d'équipe",
    titleEn: "Collaboration and Teamwork",
    descriptionFr: "Favoriser la collaboration transverse et la co-création.",
    descriptionEn: "Foster cross-functional collaboration and co-creation.",
    moduleSlug: "people",
    sortOrder: 6,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "collaboration",
    learningObjective: "APPLY",
    textBodyFr:
      "La collaboration efficace repose sur objectifs partagés, règles de travail explicites et outils adaptés. Les équipes distribuées nécessitent des rituels synchrones (standups, revues) et asynchrones (documentation, tickets). La co-création avec les parties prenantes améliore l'acceptation des livrables. Le chef de projet facilite la collaboration sans remplacer les experts métier.",
    textBodyEn:
      "Effective collaboration rests on shared goals, explicit working agreements, and suitable tools. Distributed teams need synchronous rituals (standups, reviews) and asynchronous ones (documentation, tickets). Co-creation with stakeholders improves deliverable acceptance. The project manager facilitates collaboration without replacing domain experts.",
    flashcardFrontFr: "Règles de travail",
    flashcardFrontEn: "Working agreements",
    flashcardBackFr: "Normes explicites sur communication, décisions et qualité.",
    flashcardBackEn: "Explicit norms on communication, decisions, and quality.",
    exercisePromptFr: "Proposez trois règles de travail pour une équipe distribuée.",
    exercisePromptEn: "Propose three working agreements for a distributed team.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Des règles de travail explicites améliorent la collaboration.",
      promptEn: "Explicit working agreements improve collaboration.",
      explanationCorrectFr: "Vrai. Elles réduisent l'ambiguïté sur attentes et comportements.",
      explanationCorrectEn: "True. They reduce ambiguity on expectations and behaviors.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "planning",
    titleFr: "Planification de projet",
    titleEn: "Project Planning",
    descriptionFr: "Élaborer un plan intégré couvrant périmètre, délais, coûts et risques.",
    descriptionEn: "Develop an integrated plan covering scope, schedule, cost, and risk.",
    moduleSlug: "process",
    sortOrder: 0,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "planning",
    learningObjective: "APPLY",
    textBodyFr:
      "La planification traduit les objectifs en livrables, activités, ressources et jalons mesurables. Un plan de management de projet intègre les sous-plans (périmètre, planning, coûts, qualité, risques, communication). La planification est itérative : on refine quand l'information émerge. Un plan réaliste inclut buffers, hypothèses documentées et critères d'acceptation clairs.",
    textBodyEn:
      "Planning translates objectives into deliverables, activities, resources, and measurable milestones. A project management plan integrates sub-plans (scope, schedule, cost, quality, risk, communication). Planning is iterative: you refine as information emerges. A realistic plan includes buffers, documented assumptions, and clear acceptance criteria.",
    flashcardFrontFr: "Plan de management de projet",
    flashcardFrontEn: "Project management plan",
    flashcardBackFr: "Document intégrant sous-plans pour piloter le projet.",
    flashcardBackEn: "Document integrating sub-plans to steer the project.",
    exercisePromptFr: "Listez les sous-plans essentiels d'un plan de management de projet.",
    exercisePromptEn: "List essential sub-plans of a project management plan.",
    question: {
      type: "MULTIPLE_CHOICE",
      promptFr: "Quels éléments font typiquement partie d'un plan intégré ? (Plusieurs réponses)",
      promptEn: "Which elements typically belong in an integrated plan? (Multiple answers)",
      explanationCorrectFr: "Périmètre, planning, coûts et risques sont des sous-plans classiques.",
      explanationCorrectEn: "Scope, schedule, cost, and risk are classic sub-plans.",
      difficulty: 2,
      options: [
        { labelFr: "Plan de périmètre", labelEn: "Scope plan", isCorrect: true },
        { labelFr: "Plan de planning", labelEn: "Schedule plan", isCorrect: true },
        { labelFr: "Liste de courses personnelles", labelEn: "Personal grocery list", isCorrect: false },
        { labelFr: "Plan de gestion des risques", labelEn: "Risk management plan", isCorrect: true },
      ],
    },
  },
  {
    slug: "scope",
    titleFr: "Gestion du périmètre",
    titleEn: "Scope Management",
    descriptionFr: "Définir, valider et contrôler ce qui est inclus dans le projet.",
    descriptionEn: "Define, validate, and control what is included in the project.",
    moduleSlug: "process",
    sortOrder: 1,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "scope",
    learningObjective: "ANALYZE",
    textBodyFr:
      "Le périmètre décrit les livrables et le travail nécessaire pour les produire, ainsi que ce qui est explicitement exclu. La décomposition en WBS structure le travail en packages mesurables. Le contrôle du périmètre compare le travail réalisé au baseline et gère les demandes de changement. L'élargissement non contrôlé du périmètre (scope creep) menace délais et budget.",
    textBodyEn:
      "Scope describes deliverables and work needed to produce them, plus what is explicitly excluded. WBS decomposition structures work into measurable packages. Scope control compares performed work to baseline and manages change requests. Uncontrolled scope expansion (scope creep) threatens schedule and budget.",
    flashcardFrontFr: "WBS",
    flashcardFrontEn: "WBS",
    flashcardBackFr: "Décomposition hiérarchique du travail du projet.",
    flashcardBackEn: "Hierarchical decomposition of project work.",
    exercisePromptFr: "Décomposez un livrable majeur en trois packages de travail.",
    exercisePromptEn: "Decompose one major deliverable into three work packages.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel outil structure le travail en packages mesurables ?",
      promptEn: "Which tool structures work into measurable packages?",
      explanationCorrectFr: "La WBS décompose le périmètre en éléments de travail.",
      explanationCorrectEn: "The WBS decomposes scope into work elements.",
      difficulty: 2,
      options: [
        { labelFr: "Organigramme des tâches", labelEn: "Gantt chart", isCorrect: false },
        { labelFr: "WBS (structure de décomposition)", labelEn: "WBS (work breakdown structure)", isCorrect: true },
        { labelFr: "Matrice RACI seule", labelEn: "RACI matrix alone", isCorrect: false },
      ],
    },
  },
  {
    slug: "schedule",
    titleFr: "Gestion du planning",
    titleEn: "Schedule Management",
    descriptionFr: "Construire et suivre un planning réaliste avec dépendances et jalons.",
    descriptionEn: "Build and track a realistic schedule with dependencies and milestones.",
    moduleSlug: "process",
    sortOrder: 2,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "schedule",
    learningObjective: "APPLY",
    textBodyFr:
      "Le planning séquence les activités, estime durées et ressources, et identifie le chemin critique — la chaîne d'activités qui détermine la date de fin la plus courte. Les jalons marquent des points de contrôle sans durée. Le suivi compare avancement réel vs planifié (SPI, dérives). Compresser un planning (fast-tracking, crashing) a des coûts et risques qu'il faut évaluer.",
    textBodyEn:
      "The schedule sequences activities, estimates durations and resources, and identifies the critical path — the chain of activities determining the shortest finish date. Milestones mark control points with zero duration. Tracking compares actual vs planned progress (SPI, variances). Compressing a schedule (fast-tracking, crashing) has costs and risks to evaluate.",
    flashcardFrontFr: "Chemin critique",
    flashcardFrontEn: "Critical path",
    flashcardBackFr: "Séquence d'activités déterminant la durée minimale du projet.",
    flashcardBackEn: "Sequence of activities determining minimum project duration.",
    exercisePromptFr: "Identifiez une activité sur le chemin critique d'un projet connu.",
    exercisePromptEn: "Identify one activity on the critical path of a known project.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Le chemin critique détermine la durée minimale du projet.",
      promptEn: "The critical path determines the minimum project duration.",
      explanationCorrectFr: "Vrai. Aucune marge totale sur le chemin critique sans allonger le projet.",
      explanationCorrectEn: "True. No total float on the critical path without extending the project.",
      difficulty: 2,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "cost",
    titleFr: "Gestion des coûts",
    titleEn: "Cost Management",
    descriptionFr: "Estimer, budgéter et contrôler les coûts du projet.",
    descriptionEn: "Estimate, budget, and control project costs.",
    moduleSlug: "process",
    sortOrder: 3,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "cost",
    learningObjective: "ANALYZE",
    textBodyFr:
      "La gestion des coûts couvre estimation (analogique, paramétrique, bottom-up), constitution du budget baseline et suivi des dérives. L'EAC (estimation à la fin) projette le coût total selon la performance actuelle. Les coûts directs (équipe, matériel) et indirects (overhead) doivent être distingués. Un budget sans marge de contingence ignore les risques financiers connus.",
    textBodyEn:
      "Cost management covers estimation (analogous, parametric, bottom-up), budget baseline creation, and variance tracking. EAC (estimate at completion) projects total cost based on current performance. Direct costs (team, materials) and indirect costs (overhead) should be distinguished. A budget without contingency margin ignores known financial risks.",
    flashcardFrontFr: "EAC",
    flashcardFrontEn: "EAC",
    flashcardBackFr: "Estimation du coût total à la fin du projet.",
    flashcardBackEn: "Estimate of total cost at project completion.",
    exercisePromptFr: "Comparez estimation analogique et bottom-up pour un nouveau produit.",
    exercisePromptEn: "Compare analogous and bottom-up estimation for a new product.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Qu'est-ce que l'EAC ?",
      promptEn: "What is EAC?",
      explanationCorrectFr: "L'EAC projette le coût total attendu à la fin du projet.",
      explanationCorrectEn: "EAC projects expected total cost at project end.",
      difficulty: 2,
      options: [
        { labelFr: "Coût initial planifié seulement", labelEn: "Initial planned cost only", isCorrect: false },
        { labelFr: "Estimation du coût à la fin du projet", labelEn: "Estimate at completion", isCorrect: true },
        { labelFr: "Budget de contingence uniquement", labelEn: "Contingency budget only", isCorrect: false },
      ],
    },
  },
  {
    slug: "risk-vs-issue",
    titleFr: "Risque vs problème",
    titleEn: "Risk vs Issue",
    descriptionFr: "Distinguer risque futur et problème actuel pour réagir correctement.",
    descriptionEn: "Distinguish future risk from current issue to respond correctly.",
    moduleSlug: "process",
    sortOrder: 4,
    estimatedMinutes: 6,
    difficulty: "BEGINNER",
    skillSlug: "risk-management",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "risk-vs-issue",
    shortDurationSeconds: 110,
    textBodyFr:
      "Un risque est un événement futur incertain qui pourrait affecter le projet (positif ou négatif) ; on le gère par identification, analyse et réponses planifiées. Un problème (issue) est un événement qui a déjà eu lieu et nécessite une action immédiate. Confondre les deux retarde la réponse : un risque matérialisé devient souvent un problème à traiter dans le registre des issues.",
    textBodyEn:
      "A risk is a future uncertain event that could affect the project (positive or negative); you manage it through identification, analysis, and planned responses. An issue is an event that has already occurred and needs immediate action. Confusing the two delays response: a materialized risk often becomes an issue tracked in the issue log.",
    flashcardFrontFr: "Risque",
    flashcardFrontEn: "Risk",
    flashcardBackFr: "Événement futur incertain pouvant affecter le projet.",
    flashcardBackEn: "Future uncertain event that could affect the project.",
    exercisePromptFr: "Classez trois situations en risque ou problème.",
    exercisePromptEn: "Classify three situations as risk or issue.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Un fournisseur clé a déjà manqué sa date de livraison. C'est :",
      promptEn: "A key supplier has already missed its delivery date. This is:",
      explanationCorrectFr: "C'est un problème : l'événement s'est produit et demande une action.",
      explanationCorrectEn: "This is an issue: the event occurred and requires action.",
      difficulty: 1,
      options: [
        { labelFr: "Un risque futur", labelEn: "A future risk", isCorrect: false },
        { labelFr: "Un problème actuel", labelEn: "A current issue", isCorrect: true },
        { labelFr: "Ni l'un ni l'autre", labelEn: "Neither", isCorrect: false },
      ],
    },
  },
  {
    slug: "quality",
    titleFr: "Gestion de la qualité",
    titleEn: "Quality Management",
    descriptionFr: "Planifier la qualité, assurer et contrôler les livrables.",
    descriptionEn: "Plan quality, assure it, and control deliverables.",
    moduleSlug: "process",
    sortOrder: 5,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "quality",
    learningObjective: "APPLY",
    textBodyFr:
      "La qualité en projet signifie que les livrables respectent les exigences et sont adaptés à l'usage — pas seulement absence de défauts. Le plan de qualité définit standards, métriques et activités d'assurance. Le contrôle qualité vérifie les résultats (tests, revues, inspections). L'amélioration continue via rétrospectives et leçons apprises renforce la qualité sur le long terme.",
    textBodyEn:
      "Project quality means deliverables meet requirements and fit for use — not only absence of defects. The quality plan defines standards, metrics, and assurance activities. Quality control verifies results (tests, reviews, inspections). Continuous improvement via retrospectives and lessons learned strengthens quality long term.",
    flashcardFrontFr: "Assurance qualité",
    flashcardFrontEn: "Quality assurance",
    flashcardBackFr: "Processus pour garantir que les méthodes produisent la qualité attendue.",
    flashcardBackEn: "Processes to ensure methods produce expected quality.",
    exercisePromptFr: "Distinguez une activité d'assurance qualité et une de contrôle qualité.",
    exercisePromptEn: "Distinguish one quality assurance activity from one quality control activity.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel exemple illustre le contrôle qualité ?",
      promptEn: "Which example illustrates quality control?",
      explanationCorrectFr: "Tester un livrable avant release est du contrôle qualité.",
      explanationCorrectEn: "Testing a deliverable before release is quality control.",
      difficulty: 2,
      options: [
        { labelFr: "Définir un standard de code", labelEn: "Define a code standard", isCorrect: false },
        { labelFr: "Exécuter des tests avant livraison", labelEn: "Run tests before delivery", isCorrect: true },
        { labelFr: "Former l'équipe aux bonnes pratiques", labelEn: "Train the team on good practices", isCorrect: false },
      ],
    },
  },
  {
    slug: "change-management-basics",
    titleFr: "Bases du change management",
    titleEn: "Change Management Basics",
    descriptionFr: "Gérer les demandes de changement avec traçabilité et impact.",
    descriptionEn: "Manage change requests with traceability and impact analysis.",
    moduleSlug: "process",
    sortOrder: 6,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "change-management",
    learningObjective: "DECIDE",
    isShort: true,
    shortTopic: "change-management",
    shortDurationSeconds: 140,
    textBodyFr:
      "Le change management en projet traite les modifications au baseline (périmètre, planning, coût) via un processus formel : demande, analyse d'impact, décision, mise à jour du baseline. Les changements non documentés créent de la dette de gouvernance. Distinguer changement de produit (nouvelle fonctionnalité) et changement organisationnel (adoption utilisateurs) évite les confusions.",
    textBodyEn:
      "Project change management handles modifications to baseline (scope, schedule, cost) through a formal process: request, impact analysis, decision, baseline update. Undocumented changes create governance debt. Distinguishing product change (new feature) from organizational change (user adoption) avoids confusion.",
    flashcardFrontFr: "Demande de changement",
    flashcardFrontEn: "Change request",
    flashcardBackFr: "Proposition formelle de modifier le baseline du projet.",
    flashcardBackEn: "Formal proposal to modify the project baseline.",
    exercisePromptFr: "Décrivez les étapes d'une demande de changement typique.",
    exercisePromptEn: "Describe the steps of a typical change request.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Toute modification au baseline doit passer par un processus de changement documenté.",
      promptEn: "Every baseline modification should go through a documented change process.",
      explanationCorrectFr: "Vrai. Cela protège traçabilité, budget et alignement des parties prenantes.",
      explanationCorrectEn: "True. This protects traceability, budget, and stakeholder alignment.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "integration",
    titleFr: "Intégration de projet",
    titleEn: "Project Integration",
    descriptionFr: "Coordonner les domaines de connaissance pour une livraison cohérente.",
    descriptionEn: "Coordinate knowledge areas for coherent delivery.",
    moduleSlug: "process",
    sortOrder: 7,
    estimatedMinutes: 10,
    difficulty: "ADVANCED",
    skillSlug: "integration",
    learningObjective: "DECIDE",
    textBodyFr:
      "L'intégration relie tous les domaines : périmètre, planning, coûts, qualité, risques, ressources, communication, parties prenantes et changements. Le chef de projet arbitre les trade-offs quand les objectifs entrent en conflit. La charte de projet autorise le projet ; le plan de management guide l'exécution ; la clôture formalise les livrables et les leçons. Sans intégration, les sous-plans optimisent localement mais échouent globalement.",
    textBodyEn:
      "Integration connects all domains: scope, schedule, cost, quality, risk, resources, communication, stakeholders, and changes. The project manager arbitrates trade-offs when objectives conflict. The charter authorizes the project; the management plan guides execution; closing formalizes deliverables and lessons. Without integration, sub-plans optimize locally but fail globally.",
    flashcardFrontFr: "Intégration",
    flashcardFrontEn: "Integration",
    flashcardBackFr: "Coordination de tous les domaines pour livrer le projet avec succès.",
    flashcardBackEn: "Coordination of all domains to deliver the project successfully.",
    exercisePromptFr: "Donnez un exemple de trade-off entre planning et qualité.",
    exercisePromptEn: "Give an example of a trade-off between schedule and quality.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel rôle central joue l'intégration en projet ?",
      promptEn: "What central role does integration play in projects?",
      explanationCorrectFr: "Elle coordonne les domaines et arbitre les trade-offs globaux.",
      explanationCorrectEn: "It coordinates domains and arbitrates global trade-offs.",
      difficulty: 3,
      options: [
        { labelFr: "Remplacer tous les sous-plans", labelEn: "Replace all sub-plans", isCorrect: false },
        { labelFr: "Coordonner domaines et arbitrer trade-offs", labelEn: "Coordinate domains and arbitrate trade-offs", isCorrect: true },
        { labelFr: "Éliminer la gestion des risques", labelEn: "Eliminate risk management", isCorrect: false },
      ],
    },
  },
  {
    slug: "governance",
    titleFr: "Gouvernance de projet",
    titleEn: "Project Governance",
    descriptionFr: "Structures de décision, escalade et alignement avec l'organisation.",
    descriptionEn: "Decision structures, escalation, and organizational alignment.",
    moduleSlug: "business-environment",
    sortOrder: 0,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "governance",
    learningObjective: "ANALYZE",
    textBodyFr:
      "La gouvernance définit qui décide quoi, à quel niveau et avec quelles informations. Un comité de pilotage arbitre priorités et budgets ; le chef de projet exécute dans le cadre approuvé. Les politiques organisationnelles (sécurité, achats, conformité) contraignent les choix du projet. Une gouvernance claire évite les décisions parallèles et les blocages.",
    textBodyEn:
      "Governance defines who decides what, at which level, and with which information. A steering committee arbitrates priorities and budgets; the project manager executes within the approved frame. Organizational policies (security, procurement, compliance) constrain project choices. Clear governance avoids parallel decisions and blockages.",
    flashcardFrontFr: "Gouvernance",
    flashcardFrontEn: "Governance",
    flashcardBackFr: "Cadre de décision, escalade et alignement organisationnel.",
    flashcardBackEn: "Decision framework, escalation, and organizational alignment.",
    exercisePromptFr: "Décrivez le rôle d'un comité de pilotage dans un projet.",
    exercisePromptEn: "Describe the role of a steering committee in a project.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel objectif principal de la gouvernance de projet ?",
      promptEn: "What is the main goal of project governance?",
      explanationCorrectFr: "Assurer décisions claires et alignement avec l'organisation.",
      explanationCorrectEn: "Ensure clear decisions and alignment with the organization.",
      difficulty: 2,
      options: [
        { labelFr: "Éliminer le sponsor", labelEn: "Eliminate the sponsor", isCorrect: false },
        { labelFr: "Décisions claires et alignement organisationnel", labelEn: "Clear decisions and organizational alignment", isCorrect: true },
        { labelFr: "Supprimer toute documentation", labelEn: "Remove all documentation", isCorrect: false },
      ],
    },
  },
  {
    slug: "compliance",
    titleFr: "Conformité et contraintes",
    titleEn: "Compliance and Constraints",
    descriptionFr: "Respecter réglementations, politiques et contraintes externes.",
    descriptionEn: "Respect regulations, policies, and external constraints.",
    moduleSlug: "business-environment",
    sortOrder: 1,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "compliance",
    learningObjective: "IDENTIFY",
    textBodyFr:
      "Les projets opèrent dans un cadre réglementaire et politique : données personnelles, sécurité, environnement, secteur bancaire ou santé. Les contraintes (deadline légale, budget fixe, technologie imposée) limitent les options sans être des risques. Identifier ces contraintes en amont évite des redesigns coûteux. La conformité est souvent non négociable.",
    textBodyEn:
      "Projects operate within regulatory and policy frames: personal data, security, environment, banking or healthcare sectors. Constraints (legal deadline, fixed budget, imposed technology) limit options without being risks. Identifying constraints early avoids costly redesigns. Compliance is often non-negotiable.",
    flashcardFrontFr: "Contrainte",
    flashcardFrontEn: "Constraint",
    flashcardBackFr: "Limite fixe imposée au projet (ex. réglementation).",
    flashcardBackEn: "Fixed limit imposed on the project (e.g. regulation).",
    exercisePromptFr: "Listez deux contraintes réglementaires possibles pour un projet IT.",
    exercisePromptEn: "List two possible regulatory constraints for an IT project.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Une contrainte légale est typiquement non négociable.",
      promptEn: "A legal constraint is typically non-negotiable.",
      explanationCorrectFr: "Vrai. La conformité légale ne peut généralement pas être ignorée.",
      explanationCorrectEn: "True. Legal compliance generally cannot be ignored.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "benefits",
    titleFr: "Réalisation des bénéfices",
    titleEn: "Benefits Realization",
    descriptionFr: "Lier livrables projet aux bénéfices business attendus.",
    descriptionEn: "Link project deliverables to expected business benefits.",
    moduleSlug: "business-environment",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "benefits",
    learningObjective: "ANALYZE",
    textBodyFr:
      "Un projet réussi livre des outputs ; la réalisation des bénéfices transforme ces outputs en outcomes mesurables (revenus, satisfaction, efficacité). Le business case définit les bénéfices attendus et les indicateurs. Le suivi post-projet vérifie que les bénéfices se matérialisent — souvent avec un owner des bénéfices distinct du chef de projet.",
    textBodyEn:
      "A successful project delivers outputs; benefits realization turns those outputs into measurable outcomes (revenue, satisfaction, efficiency). The business case defines expected benefits and indicators. Post-project tracking verifies benefits materialize — often with a benefits owner distinct from the project manager.",
    flashcardFrontFr: "Outcome",
    flashcardFrontEn: "Outcome",
    flashcardBackFr: "Résultat business mesurable issu des livrables du projet.",
    flashcardBackEn: "Measurable business result from project deliverables.",
    exercisePromptFr: "Transformez un livrable technique en bénéfice business mesurable.",
    exercisePromptEn: "Turn one technical deliverable into a measurable business benefit.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quelle différence entre output et outcome ?",
      promptEn: "What is the difference between output and outcome?",
      explanationCorrectFr: "L'output est le livrable ; l'outcome est le bénéfice business résultant.",
      explanationCorrectEn: "Output is the deliverable; outcome is the resulting business benefit.",
      difficulty: 2,
      options: [
        { labelFr: "Ils sont identiques", labelEn: "They are identical", isCorrect: false },
        { labelFr: "Output = livrable ; outcome = bénéfice business", labelEn: "Output = deliverable; outcome = business benefit", isCorrect: true },
        { labelFr: "Outcome précède toujours le projet", labelEn: "Outcome always precedes the project", isCorrect: false },
      ],
    },
  },
  {
    slug: "organizational-context",
    titleFr: "Contexte organisationnel",
    titleEn: "Organizational Context",
    descriptionFr: "Comprendre structure, culture et facteurs environnementaux du projet.",
    descriptionEn: "Understand structure, culture, and environmental factors of the project.",
    moduleSlug: "business-environment",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "pmp-business-environment",
    learningObjective: "IDENTIFY",
    textBodyFr:
      "Chaque projet s'inscrit dans une organisation : matricielle, fonctionnelle ou projetisée. La culture (innovation vs conformité) influence vitesse de décision et tolérance au risque. Les facteurs EEF (Enterprise Environmental Factors) incluent marché, ressources disponibles et systèmes existants. Adapter l'approche au contexte est plus efficace que copier un template externe.",
    textBodyEn:
      "Every project sits within an organization: matrix, functional, or projectized. Culture (innovation vs compliance) influences decision speed and risk tolerance. EEFs (Enterprise Environmental Factors) include market, available resources, and existing systems. Adapting approach to context beats copying an external template.",
    flashcardFrontFr: "Structure matricielle",
    flashcardFrontEn: "Matrix structure",
    flashcardBackFr: "Employés rapportent à manager fonctionnel et chef de projet.",
    flashcardBackEn: "Employees report to functional manager and project manager.",
    exercisePromptFr: "Décrivez comment la culture de votre organisation influence les projets.",
    exercisePromptEn: "Describe how your organization's culture influences projects.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quels sont des facteurs environnementaux d'entreprise (EEF) ?",
      promptEn: "What are Enterprise Environmental Factors (EEFs)?",
      explanationCorrectFr: "Conditions externes et internes qui influencent le projet (marché, systèmes).",
      explanationCorrectEn: "External and internal conditions influencing the project (market, systems).",
      difficulty: 2,
      options: [
        { labelFr: "Uniquement le budget du projet", labelEn: "Only the project budget", isCorrect: false },
        { labelFr: "Conditions org et marché influençant le projet", labelEn: "Org and market conditions influencing the project", isCorrect: true },
        { labelFr: "Les préférences personnelles du PM", labelEn: "The PM's personal preferences", isCorrect: false },
      ],
    },
  },
  {
    slug: "business-value",
    titleFr: "Valeur business",
    titleEn: "Business Value",
    descriptionFr: "Prioriser le travail selon la valeur pour l'organisation.",
    descriptionEn: "Prioritize work according to organizational value.",
    moduleSlug: "business-environment",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "business-value",
    learningObjective: "DECIDE",
    textBodyFr:
      "La valeur business combine bénéfices financiers et non financiers : revenus, coûts évités, satisfaction client, conformité, image. Prioriser par valeur évite de livrer beaucoup de faible valeur. Le minimum viable product (MVP) et le value stream mapping aident à concentrer l'effort. Chaque décision de périmètre devrait se poser la question : quelle valeur pour l'organisation ?",
    textBodyEn:
      "Business value combines financial and non-financial benefits: revenue, avoided costs, customer satisfaction, compliance, brand. Value-based prioritization avoids delivering lots of low value. MVP and value stream mapping help focus effort. Every scope decision should ask: what value for the organization?",
    flashcardFrontFr: "Valeur business",
    flashcardFrontEn: "Business value",
    flashcardBackFr: "Bénéfices nets pour l'organisation, financiers et non financiers.",
    flashcardBackEn: "Net benefits for the organization, financial and non-financial.",
    exercisePromptFr: "Classez trois fonctionnalités par valeur business estimée.",
    exercisePromptEn: "Rank three features by estimated business value.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Pour prioriser le backlog, quelle question est centrale ?",
      promptEn: "To prioritize the backlog, which question is central?",
      explanationCorrectFr: "Quelle valeur business cette item apporte à l'organisation ?",
      explanationCorrectEn: "What business value does this item bring to the organization?",
      difficulty: 2,
      options: [
        { labelFr: "Qui a demandé en premier ?", labelEn: "Who asked first?", isCorrect: false },
        { labelFr: "Quelle valeur business pour l'organisation ?", labelEn: "What business value for the organization?", isCorrect: true },
        { labelFr: "Quelle tâche est la plus facile ?", labelEn: "Which task is easiest?", isCorrect: false },
      ],
    },
  },
  {
    slug: "agile-mindset",
    titleFr: "Mindset agile",
    titleEn: "Agile Mindset",
    descriptionFr: "Adopter les valeurs : collaboration, adaptation et livraison de valeur.",
    descriptionEn: "Adopt values: collaboration, adaptation, and value delivery.",
    moduleSlug: "agile",
    sortOrder: 0,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "agile-mindset",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "agile-mindset",
    shortDurationSeconds: 125,
    textBodyFr:
      "Le mindset agile privilégie les personnes et la collaboration, la réponse au changement plutôt que le plan rigide, et la livraison fréquente de valeur. C'est une philosophie de travail, pas seulement une méthode. L'empirisme (transparence, inspection, adaptation) guide l'amélioration continue. L'agilité organisationnelle étend ces principes au-delà des équipes produit.",
    textBodyEn:
      "The agile mindset values people and collaboration, responding to change over rigid plans, and frequent value delivery. It is a work philosophy, not only a method. Empiricism (transparency, inspection, adaptation) guides continuous improvement. Organizational agility extends these principles beyond product teams.",
    flashcardFrontFr: "Mindset agile",
    flashcardFrontEn: "Agile mindset",
    flashcardBackFr: "Collaboration, adaptation et livraison fréquente de valeur.",
    flashcardBackEn: "Collaboration, adaptation, and frequent value delivery.",
    exercisePromptFr: "Comparez une décision « plan rigide » vs « réponse au changement ».",
    exercisePromptEn: "Compare a 'rigid plan' vs 'responding to change' decision.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'agilité valorise la réponse au changement plutôt qu'un plan figé.",
      promptEn: "Agility values responding to change over a fixed plan.",
      explanationCorrectFr: "Vrai. L'adaptation face à l'incertitude est un pilier du mindset agile.",
      explanationCorrectEn: "True. Adapting to uncertainty is a pillar of the agile mindset.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "iterative-delivery",
    titleFr: "Livraison itérative",
    titleEn: "Iterative Delivery",
    descriptionFr: "Livrer par incréments courts pour réduire le risque et valider tôt.",
    descriptionEn: "Deliver in short increments to reduce risk and validate early.",
    moduleSlug: "agile",
    sortOrder: 1,
    estimatedMinutes: 9,
    difficulty: "BEGINNER",
    skillSlug: "pmp-agile",
    learningObjective: "APPLY",
    textBodyFr:
      "La livraison itérative produit des incréments fonctionnels à intervalles réguliers plutôt qu'un big bang final. Chaque itération apporte feedback réel des utilisateurs et réduit le risque de construire le mauvais produit. Les itérations ont une durée fixe (timebox) ; le périmètre s'adapte. Cette approche fonctionne quand les exigences évoluent ou sont difficiles à spécifier en amont.",
    textBodyEn:
      "Iterative delivery produces functional increments at regular intervals rather than one final big bang. Each iteration brings real user feedback and reduces the risk of building the wrong product. Iterations have fixed duration (timebox); scope adapts. This approach works when requirements evolve or are hard to specify upfront.",
    flashcardFrontFr: "Incrément",
    flashcardFrontEn: "Increment",
    flashcardBackFr: "Version fonctionnelle ajoutée du produit à chaque itération.",
    flashcardBackEn: "Functional version of the product added each iteration.",
    exercisePromptFr: "Définissez un incrément pour la première itération d'une nouvelle app.",
    exercisePromptEn: "Define an increment for the first iteration of a new app.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel avantage principal de la livraison itérative ?",
      promptEn: "What is the main advantage of iterative delivery?",
      explanationCorrectFr: "Feedback early réduit le risque de construire le mauvais produit.",
      explanationCorrectEn: "Early feedback reduces the risk of building the wrong product.",
      difficulty: 2,
      options: [
        { labelFr: "Éliminer tout planning", labelEn: "Eliminate all planning", isCorrect: false },
        { labelFr: "Feedback early et réduction du risque produit", labelEn: "Early feedback and reduced product risk", isCorrect: true },
        { labelFr: "Supprimer les tests", labelEn: "Remove testing", isCorrect: false },
      ],
    },
  },
  {
    slug: "backlog",
    titleFr: "Backlog produit",
    titleEn: "Product Backlog",
    descriptionFr: "Prioriser et maintenir la liste ordonnée des besoins.",
    descriptionEn: "Prioritize and maintain the ordered list of needs.",
    moduleSlug: "agile",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "backlog",
    learningObjective: "APPLY",
    textBodyFr:
      "Le backlog produit est la source unique de travail priorisé pour l'équipe. Les items (user stories, epics) sont ordonnés par valeur ; le haut du backlog est le plus détaillé (refinement). Le Product Owner gère le contenu et l'ordre ; l'équipe estime l'effort. Un backlog vivant évolue avec le feedback — il n'est pas un document figé.",
    textBodyEn:
      "The product backlog is the single source of prioritized work for the team. Items (user stories, epics) are ordered by value; top items are most detailed (refinement). The Product Owner manages content and order; the team estimates effort. A living backlog evolves with feedback — it is not a fixed document.",
    flashcardFrontFr: "Backlog produit",
    flashcardFrontEn: "Product backlog",
    flashcardBackFr: "Liste ordonnée et priorisée des besoins produit.",
    flashcardBackEn: "Ordered, prioritized list of product needs.",
    exercisePromptFr: "Priorisez trois user stories pour un sprint selon la valeur.",
    exercisePromptEn: "Prioritize three user stories for a sprint by value.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Qui est typiquement responsable du contenu et l'ordre du backlog produit ?",
      promptEn: "Who is typically responsible for product backlog content and order?",
      explanationCorrectFr: "Le Product Owner gère contenu et priorisation du backlog.",
      explanationCorrectEn: "The Product Owner manages backlog content and prioritization.",
      difficulty: 2,
      options: [
        { labelFr: "Le Scrum Master seul", labelEn: "The Scrum Master alone", isCorrect: false },
        { labelFr: "Le Product Owner", labelEn: "The Product Owner", isCorrect: true },
        { labelFr: "Le sponsor uniquement", labelEn: "The sponsor only", isCorrect: false },
      ],
    },
  },
  {
    slug: "product-ownership",
    titleFr: "Product ownership",
    titleEn: "Product Ownership",
    descriptionFr: "Maximiser la valeur produit et représenter les parties prenantes.",
    descriptionEn: "Maximize product value and represent stakeholders.",
    moduleSlug: "agile",
    sortOrder: 3,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "product-ownership",
    learningObjective: "DECIDE",
    textBodyFr:
      "Le Product Owner maximise la valeur du produit en priorisant le backlog, clarifiant les besoins et acceptant les incréments. Il représente les parties prenantes business et arbitre les trade-offs valeur vs effort. Il ne micro-manage pas l'équipe technique mais définit « quoi » et « pourquoi ». Un PO absent ou faible crée du rework et des priorités floues.",
    textBodyEn:
      "The Product Owner maximizes product value by prioritizing the backlog, clarifying needs, and accepting increments. They represent business stakeholders and arbitrate value vs effort trade-offs. They do not micromanage the technical team but define 'what' and 'why'. An absent or weak PO creates rework and fuzzy priorities.",
    flashcardFrontFr: "Product Owner",
    flashcardFrontEn: "Product Owner",
    flashcardBackFr: "Maximise valeur produit ; priorise backlog et accepte incréments.",
    flashcardBackEn: "Maximizes product value; prioritizes backlog and accepts increments.",
    exercisePromptFr: "Décrivez une décision typique du Product Owner sur le backlog.",
    exercisePromptEn: "Describe a typical Product Owner decision on the backlog.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Le Product Owner définit principalement le « quoi » et le « pourquoi », pas le « comment » technique.",
      promptEn: "The Product Owner mainly defines 'what' and 'why', not technical 'how'.",
      explanationCorrectFr: "Vrai. L'équipe décide comment implémenter ; le PO maximise la valeur.",
      explanationCorrectEn: "True. The team decides how to implement; the PO maximizes value.",
      difficulty: 2,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "sprint-concepts",
    titleFr: "Concepts de sprint",
    titleEn: "Sprint Concepts",
    descriptionFr: "Timebox, sprint goal, planning et review dans un cadre Scrum.",
    descriptionEn: "Timebox, sprint goal, planning, and review in a Scrum frame.",
    moduleSlug: "agile",
    sortOrder: 4,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "sprint-concepts",
    learningObjective: "APPLY",
    textBodyFr:
      "Un sprint est un timebox fixe (souvent 2 semaines) pendant lequel l'équipe livre un incrément vers le sprint goal. Le sprint planning sélectionne le travail du backlog ; le daily synchronise ; la review démontre l'incrément aux parties prenantes ; la retrospective améliore le processus. Le scope du sprint est protégé pendant le sprint — les changements majeurs passent par le backlog.",
    textBodyEn:
      "A sprint is a fixed timebox (often 2 weeks) during which the team delivers an increment toward the sprint goal. Sprint planning selects backlog work; daily syncs progress; review demos the increment to stakeholders; retrospective improves the process. Sprint scope is protected during the sprint — major changes go through the backlog.",
    flashcardFrontFr: "Sprint goal",
    flashcardFrontEn: "Sprint goal",
    flashcardBackFr: "Objectif unique que le sprint vise à atteindre.",
    flashcardBackEn: "Single objective the sprint aims to achieve.",
    exercisePromptFr: "Définissez un sprint goal pour une fonctionnalité de paiement.",
    exercisePromptEn: "Define a sprint goal for a payment feature.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel événement Scrum démontre l'incrément aux parties prenantes ?",
      promptEn: "Which Scrum event demos the increment to stakeholders?",
      explanationCorrectFr: "La sprint review présente l'incrément et collecte le feedback.",
      explanationCorrectEn: "The sprint review presents the increment and collects feedback.",
      difficulty: 2,
      options: [
        { labelFr: "Daily standup", labelEn: "Daily standup", isCorrect: false },
        { labelFr: "Sprint review", labelEn: "Sprint review", isCorrect: true },
        { labelFr: "Sprint retrospective", labelEn: "Sprint retrospective", isCorrect: false },
      ],
    },
  },
  {
    slug: "feedback",
    titleFr: "Feedback et adaptation",
    titleEn: "Feedback and Adaptation",
    descriptionFr: "Utiliser le feedback utilisateur pour adapter le produit et le processus.",
    descriptionEn: "Use user feedback to adapt product and process.",
    moduleSlug: "agile",
    sortOrder: 5,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pmp-agile",
    learningObjective: "ANALYZE",
    textBodyFr:
      "Le feedback transforme les assumptions en connaissances. Sources : utilisateurs, analytics, support, review de sprint. L'adaptation répond au feedback en ajustant backlog, design ou processus. Retarder le feedback (long cycles sans démo) augmente le coût du changement. Un cadre d'inspection régulière (review, démos) rend l'adaptation systématique.",
    textBodyEn:
      "Feedback turns assumptions into knowledge. Sources: users, analytics, support, sprint review. Adaptation responds to feedback by adjusting backlog, design, or process. Delaying feedback (long cycles without demos) increases change cost. Regular inspection (review, demos) makes adaptation systematic.",
    flashcardFrontFr: "Inspection",
    flashcardFrontEn: "Inspection",
    flashcardBackFr: "Examiner le produit et le processus pour identifier les améliorations.",
    flashcardBackEn: "Examine product and process to identify improvements.",
    exercisePromptFr: "Listez trois sources de feedback pour un produit digital.",
    exercisePromptEn: "List three feedback sources for a digital product.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Pourquoi le feedback early réduit le coût du changement ?",
      promptEn: "Why does early feedback reduce the cost of change?",
      explanationCorrectFr: "Corriger tôt évite de construire beaucoup sur une mauvaise assumption.",
      explanationCorrectEn: "Correcting early avoids building much on a wrong assumption.",
      difficulty: 2,
      options: [
        { labelFr: "Parce que le changement est interdit après", labelEn: "Because change is forbidden after", isCorrect: false },
        { labelFr: "Corriger tôt limite le travail basé sur de mauvaises assumptions", labelEn: "Early correction limits work based on wrong assumptions", isCorrect: true },
        { labelFr: "Parce que les utilisateurs ne changent jamais d'avis", labelEn: "Because users never change their minds", isCorrect: false },
      ],
    },
  },
  {
    slug: "retrospective",
    titleFr: "Rétrospective",
    titleEn: "Retrospective",
    descriptionFr: "Améliorer l'équipe et le processus après chaque itération.",
    descriptionEn: "Improve team and process after each iteration.",
    moduleSlug: "agile",
    sortOrder: 6,
    estimatedMinutes: 8,
    difficulty: "BEGINNER",
    skillSlug: "pmp-agile",
    learningObjective: "APPLY",
    textBodyFr:
      "La rétrospective inspecte comment l'équipe a travaillé : ce qui a bien fonctionné, ce qui a bloqué, et quelles actions concrètes amélioreront le prochain cycle. Format classique : Start/Stop/Continue ou 4L (liked, learned, lacked, longed for). Les actions doivent être petites, assignées et suivies. Sans rétrospective, les mêmes problèmes se répètent sprint après sprint.",
    textBodyEn:
      "The retrospective inspects how the team worked: what went well, what blocked, and which concrete actions will improve the next cycle. Classic formats: Start/Stop/Continue or 4L (liked, learned, lacked, longed for). Actions should be small, assigned, and tracked. Without retrospectives, the same problems repeat sprint after sprint.",
    flashcardFrontFr: "Rétrospective",
    flashcardFrontEn: "Retrospective",
    flashcardBackFr: "Cérémonie pour améliorer processus et collaboration de l'équipe.",
    flashcardBackEn: "Ceremony to improve team process and collaboration.",
    exercisePromptFr: "Proposez deux actions concrètes issues d'une rétrospective.",
    exercisePromptEn: "Propose two concrete actions from a retrospective.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Les actions de rétrospective doivent être concrètes et suivies.",
      promptEn: "Retrospective actions should be concrete and tracked.",
      explanationCorrectFr: "Vrai. Des actions vagues sans suivi ne changent pas le comportement.",
      explanationCorrectEn: "True. Vague actions without follow-up do not change behavior.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "hybrid-project-basics",
    titleFr: "Bases du projet hybride",
    titleEn: "Hybrid Project Basics",
    descriptionFr: "Quand le hybride fait sens et bases de la combinaison prédictif-agile.",
    descriptionEn: "When hybrid makes sense and basics of combining predictive and agile.",
    moduleSlug: "hybrid",
    sortOrder: 0,
    estimatedMinutes: 7,
    difficulty: "BEGINNER",
    skillSlug: "hybrid-delivery",
    learningObjective: "IDENTIFY",
    isShort: true,
    shortTopic: "hybrid-project",
    shortDurationSeconds: 135,
    textBodyFr:
      "Un projet hybride mélange planification structurée (jalons, budget global) et exécution agile (sprints, backlog) selon les parties du projet. C'est courant quand certaines composantes sont stables (infrastructure, conformité) et d'autres évolutives (interface utilisateur). Le hybride n'est pas un échec de méthode — c'est un tailoring conscient du contexte.",
    textBodyEn:
      "A hybrid project mixes structured planning (milestones, overall budget) and agile execution (sprints, backlog) across project parts. It is common when some components are stable (infrastructure, compliance) and others evolving (user interface). Hybrid is not method failure — it is conscious tailoring to context.",
    flashcardFrontFr: "Projet hybride",
    flashcardFrontEn: "Hybrid project",
    flashcardBackFr: "Combine planification structurée et exécution agile selon le contexte.",
    flashcardBackEn: "Combines structured planning and agile execution by context.",
    exercisePromptFr: "Identifiez une partie prédictive et une partie agile d'un projet connu.",
    exercisePromptEn: "Identify one predictive and one agile part of a known project.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "L'approche hybride combine typiquement planification structurée et exécution agile.",
      promptEn: "The hybrid approach typically combines structured planning and agile execution.",
      explanationCorrectFr: "Vrai. Le hybride adapte la méthode aux composantes du projet.",
      explanationCorrectEn: "True. Hybrid adapts the method to project components.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "combining-predictive-and-agile",
    titleFr: "Combiner prédictif et agile",
    titleEn: "Combining Predictive and Agile",
    descriptionFr: "Pratiques concrètes pour intégrer les deux modes de travail.",
    descriptionEn: "Concrete practices to integrate both work modes.",
    moduleSlug: "hybrid",
    sortOrder: 1,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "hybrid-delivery",
    learningObjective: "APPLY",
    textBodyFr:
      "Combiner prédictif et agile peut prendre la forme de : roadmap avec jalons fixes et sprints entre les gates ; WBS pour le programme et backlog pour les équipes produit ; budget envelope avec burn rate agile. Les interfaces entre modes doivent être explicites : qui fournit quoi, quand, et avec quels critères d'acceptation. La communication entre équipes prédictives et agiles est le point critique.",
    textBodyEn:
      "Combining predictive and agile can take the form of: roadmap with fixed milestones and sprints between gates; WBS for the program and backlog for product teams; budget envelope with agile burn rate. Interfaces between modes must be explicit: who delivers what, when, and with which acceptance criteria. Communication between predictive and agile teams is the critical point.",
    flashcardFrontFr: "Gate (jalon)",
    flashcardFrontEn: "Gate (milestone)",
    flashcardBackFr: "Point de contrôle prédictif entre phases ou releases.",
    flashcardBackEn: "Predictive control point between phases or releases.",
    exercisePromptFr: "Décrivez comment lier un jalon programme à deux sprints produit.",
    exercisePromptEn: "Describe how to link a program milestone to two product sprints.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel élément est critique quand on combine prédictif et agile ?",
      promptEn: "What is critical when combining predictive and agile?",
      explanationCorrectFr: "Des interfaces explicites entre modes et équipes.",
      explanationCorrectEn: "Explicit interfaces between modes and teams.",
      difficulty: 2,
      options: [
        { labelFr: "Utiliser un seul outil sans adaptation", labelEn: "Use one tool without adaptation", isCorrect: false },
        { labelFr: "Interfaces explicites entre modes et équipes", labelEn: "Explicit interfaces between modes and teams", isCorrect: true },
        { labelFr: "Interdire toute planification", labelEn: "Ban all planning", isCorrect: false },
      ],
    },
  },
  {
    slug: "tailoring",
    titleFr: "Tailoring",
    titleEn: "Tailoring",
    descriptionFr: "Adapter processus, artefacts et gouvernance au contexte du projet.",
    descriptionEn: "Adapt processes, artifacts, and governance to project context.",
    moduleSlug: "hybrid",
    sortOrder: 2,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "hybrid-delivery",
    learningObjective: "DECIDE",
    textBodyFr:
      "Le tailoring sélectionne et adapte processus, artefacts et durée des cérémonies selon taille, risque, culture et réglementation du projet. Un petit projet interne n'a pas besoin du même formalisme qu'un programme régulé. Documenter les choix de tailoring (ce qu'on utilise, ce qu'on simplifie) évite les audits surprises. Le tailoring est continu, pas seulement à l'initiation.",
    textBodyEn:
      "Tailoring selects and adapts processes, artifacts, and ceremony length based on project size, risk, culture, and regulation. A small internal project does not need the same formality as a regulated program. Documenting tailoring choices (what you use, what you simplify) avoids audit surprises. Tailoring is continuous, not only at initiation.",
    flashcardFrontFr: "Tailoring",
    flashcardFrontEn: "Tailoring",
    flashcardBackFr: "Adapter processus et artefacts au contexte spécifique du projet.",
    flashcardBackEn: "Adapt processes and artifacts to the project's specific context.",
    exercisePromptFr: "Listez trois éléments à simplifier pour un petit projet interne.",
    exercisePromptEn: "List three elements to simplify for a small internal project.",
    question: {
      type: "TRUE_FALSE",
      promptFr: "Le tailoring adapte les processus au contexte du projet.",
      promptEn: "Tailoring adapts processes to the project context.",
      explanationCorrectFr: "Vrai. Pas de one-size-fits-all en gestion de projet moderne.",
      explanationCorrectEn: "True. No one-size-fits-all in modern project management.",
      difficulty: 1,
      options: [
        { labelFr: "Vrai", labelEn: "True", isCorrect: true },
        { labelFr: "Faux", labelEn: "False", isCorrect: false },
      ],
    },
  },
  {
    slug: "governance-hybrid",
    titleFr: "Gouvernance hybride",
    titleEn: "Hybrid Governance",
    descriptionFr: "Aligner comités, gates et autonomie agile dans un même programme.",
    descriptionEn: "Align committees, gates, and agile autonomy in one program.",
    moduleSlug: "hybrid",
    sortOrder: 3,
    estimatedMinutes: 10,
    difficulty: "ADVANCED",
    skillSlug: "hybrid-delivery",
    learningObjective: "ANALYZE",
    textBodyFr:
      "La gouvernance hybride combine décisions stratégiques centralisées (budget, scope majeur) et autonomie d'exécution des équipes agiles. Les gates vérifient outcomes et risques sans micro-manager les sprints. Le comité de pilotage voit les métriques de valeur (lead time, satisfaction) en plus des jalons. Clarifier ce qui est décidé au gate vs en sprint évite les conflits d'autorité.",
    textBodyEn:
      "Hybrid governance combines centralized strategic decisions (budget, major scope) and execution autonomy of agile teams. Gates verify outcomes and risks without micromanaging sprints. The steering committee sees value metrics (lead time, satisfaction) in addition to milestones. Clarifying what is decided at the gate vs in sprint avoids authority conflicts.",
    flashcardFrontFr: "Gate de gouvernance",
    flashcardFrontEn: "Governance gate",
    flashcardBackFr: "Point où le comité valide progression, risques et budget.",
    flashcardBackEn: "Point where committee validates progress, risks, and budget.",
    exercisePromptFr: "Définissez ce qui est décidé au gate vs en sprint planning.",
    exercisePromptEn: "Define what is decided at the gate vs in sprint planning.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "En gouvernance hybride, que vérifie typiquement un gate ?",
      promptEn: "In hybrid governance, what does a gate typically verify?",
      explanationCorrectFr: "Outcomes, risques majeurs et alignement budget — pas chaque tâche sprint.",
      explanationCorrectEn: "Outcomes, major risks, and budget alignment — not each sprint task.",
      difficulty: 3,
      options: [
        { labelFr: "Chaque tâche du daily standup", labelEn: "Each daily standup task", isCorrect: false },
        { labelFr: "Outcomes, risques majeurs et budget", labelEn: "Outcomes, major risks, and budget", isCorrect: true },
        { labelFr: "Rien — les gates sont obsolètes", labelEn: "Nothing — gates are obsolete", isCorrect: false },
      ],
    },
  },
  {
    slug: "delivery-strategy",
    titleFr: "Stratégie de livraison",
    titleEn: "Delivery Strategy",
    descriptionFr: "Choisir cadence, releases et critères de succès pour le programme.",
    descriptionEn: "Choose cadence, releases, and success criteria for the program.",
    moduleSlug: "hybrid",
    sortOrder: 4,
    estimatedMinutes: 9,
    difficulty: "INTERMEDIATE",
    skillSlug: "hybrid-delivery",
    learningObjective: "DECIDE",
    textBodyFr:
      "La stratégie de livraison définit cadence (releases, trains), critères de done et comment les incréments s'assemblent en valeur business. En hybride : releases majeures alignées aux gates, incréments mineurs en continu entre les gates. La stratégie doit être visible pour toutes les équipes. Changer de stratégie en cours de route sans communication crée des dépendances cassées.",
    textBodyEn:
      "Delivery strategy defines cadence (releases, trains), done criteria, and how increments assemble into business value. In hybrid: major releases aligned to gates, minor increments continuously between gates. Strategy must be visible to all teams. Changing strategy mid-flight without communication creates broken dependencies.",
    flashcardFrontFr: "Release train",
    flashcardFrontEn: "Release train",
    flashcardBackFr: "Cadence planifiée de releases alignant plusieurs équipes.",
    flashcardBackEn: "Planned release cadence aligning multiple teams.",
    exercisePromptFr: "Définissez une cadence de release pour un programme hybride.",
    exercisePromptEn: "Define a release cadence for a hybrid program.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quel élément central d'une stratégie de livraison hybride ?",
      promptEn: "What is central to a hybrid delivery strategy?",
      explanationCorrectFr: "Cadence de releases et critères de done partagés entre équipes.",
      explanationCorrectEn: "Release cadence and shared done criteria across teams.",
      difficulty: 2,
      options: [
        { labelFr: "Chaque équipe choisit sa cadence sans coordination", labelEn: "Each team picks cadence without coordination", isCorrect: false },
        { labelFr: "Cadence et critères de done partagés", labelEn: "Shared cadence and done criteria", isCorrect: true },
        { labelFr: "Une seule release finale sans incréments", labelEn: "One final release without increments", isCorrect: false },
      ],
    },
  },
  {
    slug: "scope-creep-mid-sprint",
    titleFr: "Élargissement du périmètre en sprint",
    titleEn: "Scope Creep Mid-Sprint",
    descriptionFr: "Raisonner face à une demande de fonctionnalité en cours de sprint.",
    descriptionEn: "Reason through a feature request during an active sprint.",
    moduleSlug: "situational-thinking",
    sortOrder: 0,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "pmp-situational-thinking",
    learningObjective: "DECIDE",
    situation: {
      scenarioFr:
        "En milieu de sprint, un directeur commercial demande une nouvelle fonctionnalité de reporting « urgente » pour une démo client dans 10 jours. L'équipe est déjà engagée sur le sprint goal actuel. Le Product Owner hésite.",
      scenarioEn:
        "Mid-sprint, a sales director requests a new reporting feature as 'urgent' for a client demo in 10 days. The team is already committed to the current sprint goal. The Product Owner hesitates.",
      bestActionFr:
        "Accueillir la demande, évaluer la valeur et l'impact avec le PO, puis ajouter au backlog priorisé — pas insérer dans le sprint courant sans replanifier avec l'équipe.",
      bestActionEn:
        "Acknowledge the request, assess value and impact with the PO, then add to the prioritized backlog — do not insert into the current sprint without replanning with the team.",
    },
    textBodyFr:
      "Face à une demande urgente mid-sprint, la meilleure action protège le sprint goal et la vélocité tout en respectant la partie prenante. Insérer du travail sans replanifier déstabilise l'équipe et masque la vraie capacité. Documenter la demande, quantifier la valeur business et planifier pour le prochain sprint (ou négocier un scope swap explicite) est plus durable que céder à la pression immédiate.",
    textBodyEn:
      "Facing an urgent mid-sprint request, the best action protects the sprint goal and velocity while respecting the stakeholder. Inserting work without replanning destabilizes the team and hides true capacity. Documenting the request, quantifying business value, and planning for the next sprint (or negotiating an explicit scope swap) is more sustainable than yielding to immediate pressure.",
    flashcardFrontFr: "Demande urgente mid-sprint",
    flashcardFrontEn: "Urgent mid-sprint request",
    flashcardBackFr: "Backlog + priorisation, pas insertion silencieuse dans le sprint.",
    flashcardBackEn: "Backlog + prioritization, not silent insertion into the sprint.",
    exercisePromptFr: "Rédigez la réponse que vous donneriez au directeur commercial.",
    exercisePromptEn: "Write the response you would give to the sales director.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Meilleure première action face à cette demande ?",
      promptEn: "Best first action facing this request?",
      explanationCorrectFr: "Documenter, évaluer valeur avec le PO et prioriser au backlog — protège le sprint.",
      explanationCorrectEn: "Document, assess value with PO, and prioritize in backlog — protects the sprint.",
      difficulty: 3,
      options: [
        { labelFr: "Ajouter immédiatement la feature au sprint sans discussion", labelEn: "Immediately add the feature to the sprint without discussion", isCorrect: false },
        { labelFr: "Documenter, évaluer valeur et prioriser au backlog", labelEn: "Document, assess value, and prioritize in backlog", isCorrect: true },
        { labelFr: "Refuser sèchement sans explication", labelEn: "Flatly refuse without explanation", isCorrect: false },
      ],
    },
  },
  {
    slug: "team-conflict-architecture",
    titleFr: "Conflit technique entre experts",
    titleEn: "Technical Conflict Between Experts",
    descriptionFr: "Faciliter un conflit d'architecture sans imposer une solution.",
    descriptionEn: "Facilitate an architecture conflict without imposing a solution.",
    moduleSlug: "situational-thinking",
    sortOrder: 1,
    estimatedMinutes: 10,
    difficulty: "INTERMEDIATE",
    skillSlug: "pmp-situational-thinking",
    learningObjective: "DECIDE",
    situation: {
      scenarioFr:
        "Deux développeurs seniors s'opposent sur l'architecture d'une API : microservices vs monolithe modulaire. Le débat bloque la story critique du sprint. Chacun a des arguments valables liés à la scalabilité et au délai.",
      scenarioEn:
        "Two senior developers disagree on API architecture: microservices vs modular monolith. The debate blocks the sprint's critical story. Each has valid arguments related to scalability and deadline.",
      bestActionFr:
        "Faciliter une session timeboxée avec critères explicites (délai, risque, maintenabilité), faire produire une recommandation par les experts, puis décider ou escalader si nécessaire.",
      bestActionEn:
        "Facilitate a timeboxed session with explicit criteria (deadline, risk, maintainability), have experts produce a recommendation, then decide or escalate if needed.",
    },
    textBodyFr:
      "Un conflit technique entre experts n'est pas résolu par le chef de projet qui choisit la technologie. La facilitation structurée : critères de décision partagés, timebox, prototypage léger si utile, et documentation de la décision. Si le blocage persiste, escalader au tech lead ou architecte avec les options analysées — pas avec le conflit non traité.",
    textBodyEn:
      "Technical conflict between experts is not resolved by the project manager picking the technology. Structured facilitation: shared decision criteria, timebox, light prototyping if useful, and decision documentation. If blockage persists, escalate to tech lead or architect with analyzed options — not with untreated conflict.",
    flashcardFrontFr: "Conflit technique",
    flashcardFrontEn: "Technical conflict",
    flashcardBackFr: "Faciliter avec critères explicites ; ne pas imposer la solution technique.",
    flashcardBackEn: "Facilitate with explicit criteria; do not impose the technical solution.",
    exercisePromptFr: "Listez trois critères de décision pour ce débat d'architecture.",
    exercisePromptEn: "List three decision criteria for this architecture debate.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Quelle approche est la plus appropriée pour le chef de projet ?",
      promptEn: "Which approach is most appropriate for the project manager?",
      explanationCorrectFr: "Faciliter une session timeboxée avec critères et recommandation des experts.",
      explanationCorrectEn: "Facilitate a timeboxed session with criteria and expert recommendation.",
      difficulty: 3,
      options: [
        { labelFr: "Choisir microservices car c'est moderne", labelEn: "Choose microservices because it is modern", isCorrect: false },
        { labelFr: "Faciliter session timeboxée avec critères explicites", labelEn: "Facilitate timeboxed session with explicit criteria", isCorrect: true },
        { labelFr: "Reporter indéfiniment la décision", labelEn: "Postpone the decision indefinitely", isCorrect: false },
      ],
    },
  },
  {
    slug: "vendor-delay-risk",
    titleFr: "Retard fournisseur critique",
    titleEn: "Critical Vendor Delay",
    descriptionFr: "Réagir quand un risque matérialisé menace le chemin critique.",
    descriptionEn: "React when a materialized risk threatens the critical path.",
    moduleSlug: "situational-thinking",
    sortOrder: 2,
    estimatedMinutes: 10,
    difficulty: "ADVANCED",
    skillSlug: "pmp-situational-thinking",
    learningObjective: "DECIDE",
    situation: {
      scenarioFr:
        "Un fournisseur clé annonce un retard de 3 semaines sur un composant hardware indispensable. Le chemin critique absorbe déjà peu de marge. Le sponsor demande « trouver une solution » sans budget supplémentaire.",
      scenarioEn:
        "A key supplier announces a 3-week delay on essential hardware. The critical path already has little float. The sponsor asks to 'find a solution' without additional budget.",
      bestActionFr:
        "Mettre à jour le registre des issues, analyser options (fournisseur alternatif, fast-track parallèle, scope swap), quantifier impact sur EAC et date, puis présenter trade-offs au sponsor pour décision.",
      bestActionEn:
        "Update the issue log, analyze options (alternate supplier, parallel fast-track, scope swap), quantify impact on EAC and date, then present trade-offs to the sponsor for decision.",
    },
    textBodyFr:
      "Quand un risque devient un problème sur le chemin critique, l'action immédiate est l'analyse d'impact et la transparence — pas l'optimisme silencieux. Options typiques : fournisseur alternatif (coût/délai), fast-tracking d'autres activités, réduction de scope, ou négociation avec le fournisseur. Le sponsor doit voir les trade-offs quantifiés pour autoriser budget ou scope.",
    textBodyEn:
      "When a risk becomes an issue on the critical path, immediate action is impact analysis and transparency — not silent optimism. Typical options: alternate supplier (cost/time), fast-tracking other activities, scope reduction, or supplier negotiation. The sponsor must see quantified trade-offs to authorize budget or scope.",
    flashcardFrontFr: "Risque matérialisé",
    flashcardFrontEn: "Materialized risk",
    flashcardBackFr: "Analyser impact, options et trade-offs avant promettre une date.",
    flashcardBackEn: "Analyze impact, options, and trade-offs before promising a date.",
    exercisePromptFr: "Listez trois options face au retard fournisseur.",
    exercisePromptEn: "List three options facing the supplier delay.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Meilleure première action du chef de projet ?",
      promptEn: "Best first action for the project manager?",
      explanationCorrectFr: "Documenter l'issue, analyser options et quantifier impact pour le sponsor.",
      explanationCorrectEn: "Document the issue, analyze options, and quantify impact for the sponsor.",
      difficulty: 3,
      options: [
        { labelFr: "Promettre la date originale au client", labelEn: "Promise the original date to the client", isCorrect: false },
        { labelFr: "Analyser options et présenter trade-offs quantifiés", labelEn: "Analyze options and present quantified trade-offs", isCorrect: true },
        { labelFr: "Ignorer le retard et continuer comme prévu", labelEn: "Ignore the delay and continue as planned", isCorrect: false },
      ],
    },
  },
  {
    slug: "change-request-critical-path",
    titleFr: "Changement sur le chemin critique",
    titleEn: "Change on the Critical Path",
    descriptionFr: "Traiter une demande de changement majeure sans déstabiliser le projet.",
    descriptionEn: "Handle a major change request without destabilizing the project.",
    moduleSlug: "situational-thinking",
    sortOrder: 3,
    estimatedMinutes: 10,
    difficulty: "ADVANCED",
    skillSlug: "pmp-situational-thinking",
    learningObjective: "DECIDE",
    situation: {
      scenarioFr:
        "Le sponsor soumet une demande de changement majeure : ajouter une intégration réglementaire non prévue. Elle touche le chemin critique et nécessite 4 semaines de travail. Le budget baseline n'a pas de contingence restante.",
      scenarioEn:
        "The sponsor submits a major change request: add an unforeseen regulatory integration. It touches the critical path and requires 4 weeks of work. The budget baseline has no remaining contingency.",
      bestActionFr:
        "Traiter via le processus de changement formel : analyse d'impact (planning, coût, risque, qualité), options (scope swap, budget supplémentaire, phasing), recommandation documentée, puis décision du comité ou sponsor avant exécution.",
      bestActionEn:
        "Process through formal change: impact analysis (schedule, cost, risk, quality), options (scope swap, additional budget, phasing), documented recommendation, then committee or sponsor decision before execution.",
    },
    textBodyFr:
      "Une demande de changement majeure du sponsor ne doit pas être exécutée sans analyse — même si le demandeur est le sponsor. Le processus protège l'équipe et clarifie les trade-offs : date, budget, autres livrables. Phasing (livrer l'essentiel réglementaire en premier) ou scope swap sont souvent des options à présenter. Exécuter sans baseline update crée de la dette de gouvernance.",
    textBodyEn:
      "A major change request from the sponsor should not be executed without analysis — even when the requester is the sponsor. The process protects the team and clarifies trade-offs: date, budget, other deliverables. Phasing (deliver essential regulatory part first) or scope swap are often options to present. Executing without baseline update creates governance debt.",
    flashcardFrontFr: "Changement majeur",
    flashcardFrontEn: "Major change",
    flashcardBackFr: "Processus formel + analyse d'impact avant exécution.",
    flashcardBackEn: "Formal process + impact analysis before execution.",
    exercisePromptFr: "Proposez deux options de trade-off pour ce changement.",
    exercisePromptEn: "Propose two trade-off options for this change.",
    question: {
      type: "SINGLE_CHOICE",
      promptFr: "Face à ce changement du sponsor, quelle action est correcte ?",
      promptEn: "Facing this sponsor change, which action is correct?",
      explanationCorrectFr: "Processus formel avec analyse d'impact et décision avant exécution.",
      explanationCorrectEn: "Formal process with impact analysis and decision before execution.",
      difficulty: 3,
      options: [
        { labelFr: "Commencer immédiatement car le sponsor a demandé", labelEn: "Start immediately because the sponsor asked", isCorrect: false },
        { labelFr: "Processus de changement avec analyse d'impact", labelEn: "Change process with impact analysis", isCorrect: true },
        { labelFr: "Refuser sans analyse ni discussion", labelEn: "Refuse without analysis or discussion", isCorrect: false },
      ],
    },
  },
];
