/**
 * PMP concept graph — concepts & sub-concepts (Phase B).
 * PLA pedagogical layer — not PMBOK verbatim reproduction.
 */

import type { ConceptRecord, EcoTaskStableId, PmbokPerformanceDomainId } from "./types";

function c(
  partial: Omit<ConceptRecord, "sourceType" | "sourceConfidence" | "status"> & {
    sourceType?: ConceptRecord["sourceType"];
    sourceConfidence?: ConceptRecord["sourceConfidence"];
  }
): ConceptRecord {
  return {
    ...partial,
    sourceType: partial.sourceType ?? "DERIVED_PEDAGOGICAL",
    sourceConfidence: partial.sourceConfidence ?? "MEDIUM",
    status: "ACTIVE",
  };
}

export const CONCEPTS: readonly ConceptRecord[] = [
  c({
    id: "stakeholders",
    nameEn: "Stakeholders",
    nameFr: "Parties prenantes",
    descriptionEn: "People and groups who affect or are affected by the project.",
    descriptionFr: "Personnes et groupes qui influencent ou sont influencés par le projet.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04", "PEOPLE-T05", "PEOPLE-T06"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    subConceptIds: [
      "stakeholder-identification",
      "stakeholder-analysis",
      "stakeholder-engagement",
      "communication-vs-engagement",
      "stakeholder-influence",
      "stakeholder-trust",
      "expectation-alignment",
      "expectation-management",
    ],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["communication-planning", "governance"],
    commonlyConfusedWith: ["communication-planning"],
    skillIds: [
      "skill-identify-stakeholder",
      "skill-analyze-stakeholder",
      "skill-engagement-strategy",
      "skill-distinguish-communication-engagement",
    ],
    difficulty: "INTERMEDIATE",
    sourceType: "PMBOK8",
  }),
  c({
    id: "stakeholder-engagement",
    nameEn: "Stakeholder engagement",
    nameFr: "Implication des parties prenantes",
    descriptionEn: "Building commitment and collaboration — not merely sending information.",
    descriptionFr: "Créer engagement et collaboration — pas seulement transmettre de l'information.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholders",
    subConceptIds: ["communication-vs-engagement", "stakeholder-trust", "stakeholder-influence"],
    prerequisiteConceptIds: ["stakeholder-identification"],
    relatedConceptIds: ["communication-planning"],
    commonlyConfusedWith: ["communication-planning"],
    skillIds: [
      "skill-engagement-strategy",
      "skill-build-trust",
      "skill-influence-stakeholders",
      "skill-distinguish-communication-engagement",
    ],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "stakeholder-identification",
    nameEn: "Stakeholder identification",
    nameFr: "Identification des parties prenantes",
    descriptionEn: "Discovering who may influence or be impacted by the work.",
    descriptionFr: "Découvrir qui peut influencer ou être impacté par le travail.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholders",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["stakeholder-analysis"],
    commonlyConfusedWith: [],
    skillIds: ["skill-identify-stakeholder"],
    difficulty: "BEGINNER",
  }),
  c({
    id: "stakeholder-analysis",
    nameEn: "Stakeholder analysis",
    nameFr: "Analyse des parties prenantes",
    descriptionEn: "Understanding interests, influence, and engagement needs.",
    descriptionFr: "Comprendre intérêts, influence et besoins d'implication.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholders",
    subConceptIds: [],
    prerequisiteConceptIds: ["stakeholder-identification"],
    relatedConceptIds: ["expectation-alignment"],
    commonlyConfusedWith: [],
    skillIds: ["skill-analyze-stakeholder"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "communication-vs-engagement",
    nameEn: "Communication vs engagement",
    nameFr: "Communication vs engagement",
    descriptionEn: "Information flow differs from building commitment and participation.",
    descriptionFr: "Le flux d'information diffère de la création d'engagement et de participation.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04", "PEOPLE-T08"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholder-engagement",
    subConceptIds: [],
    prerequisiteConceptIds: ["stakeholder-engagement", "communication-planning"],
    relatedConceptIds: ["communication-planning"],
    commonlyConfusedWith: ["communication-planning"],
    skillIds: ["skill-distinguish-communication-engagement"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "communication-planning",
    nameEn: "Communication planning",
    nameFr: "Planification de la communication",
    descriptionEn: "Strategy, channels, feedback loops, and reporting aligned to needs.",
    descriptionFr: "Stratégie, canaux, boucles de retour et rapports alignés aux besoins.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T08"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    subConceptIds: [],
    prerequisiteConceptIds: ["stakeholder-analysis"],
    relatedConceptIds: ["stakeholder-engagement"],
    commonlyConfusedWith: ["stakeholder-engagement"],
    skillIds: ["skill-communication-strategy", "skill-tailor-communication"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "expectation-alignment",
    nameEn: "Expectation alignment",
    nameFr: "Alignement des attentes",
    descriptionEn: "Facilitating shared understanding of what success means.",
    descriptionFr: "Faciliter une compréhension partagée de la réussite.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T05"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholders",
    subConceptIds: [],
    prerequisiteConceptIds: ["stakeholder-analysis"],
    relatedConceptIds: ["expectation-management"],
    commonlyConfusedWith: ["requirements-management"],
    skillIds: ["skill-align-expectations"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "expectation-management",
    nameEn: "Expectation management",
    nameFr: "Pilotage des attentes",
    descriptionEn: "Monitoring satisfaction and adjusting outcomes vs expectations.",
    descriptionFr: "Suivre la satisfaction et ajuster résultats vs attentes.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T06"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholders",
    subConceptIds: [],
    prerequisiteConceptIds: ["expectation-alignment"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["expectation-alignment"],
    skillIds: ["skill-manage-expectations"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "shared-vision",
    nameEn: "Shared vision",
    nameFr: "Vision partagée",
    descriptionEn: "Common understanding of purpose and direction among key stakeholders.",
    descriptionFr: "Compréhension commune du but et de la direction.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T01"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    subConceptIds: ["deliverable-vs-outcome-vs-value"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["stakeholder-engagement", "expectation-alignment"],
    commonlyConfusedWith: [],
    skillIds: ["skill-promote-shared-vision", "skill-facilitate-shared-vision"],
    difficulty: "INTERMEDIATE",
    sourceType: "PMI_ECO_2026",
    sourceConfidence: "HIGH",
  }),
  c({
    id: "conflict-management",
    nameEn: "Conflict management",
    nameFr: "Gestion des conflits",
    descriptionEn: "Identifying, analyzing, and resolving disagreements constructively.",
    descriptionFr: "Identifier, analyser et résoudre les désaccords de façon constructive.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T02"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS", "PD-RESOURCES"],
    subConceptIds: [
      "conflict-vs-issue",
      "root-cause-vs-symptom",
      "collaboration-vs-compromise",
    ],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["team-leadership"],
    commonlyConfusedWith: ["issue-management"],
    skillIds: [
      "skill-identify-conflict-source",
      "skill-select-conflict-response",
      "skill-facilitate-resolution",
    ],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "team-leadership",
    nameEn: "Team leadership",
    nameFr: "Direction d'équipe",
    descriptionEn: "Leading, empowering, and supporting the project team.",
    descriptionFr: "Diriger, responsabiliser et soutenir l'équipe projet.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T03"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    subConceptIds: ["leadership-vs-authority", "coaching-vs-directing", "empowerment-vs-delegation"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["conflict-management", "knowledge-transfer"],
    commonlyConfusedWith: [],
    skillIds: [
      "skill-set-team-expectations",
      "skill-empower-team",
      "skill-select-leadership-style",
    ],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "knowledge-transfer",
    nameEn: "Knowledge transfer",
    nameFr: "Transfert de connaissances",
    descriptionEn: "Ensuring critical knowledge is captured and shared.",
    descriptionFr: "Garantir que les connaissances critiques sont capturées et partagées.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T07"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    subConceptIds: ["tacit-vs-explicit-knowledge"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["continuous-improvement", "communication-planning"],
    commonlyConfusedWith: ["communication-planning"],
    skillIds: ["skill-enable-knowledge-transfer", "skill-choose-knowledge-transfer-method"],
    difficulty: "INTERMEDIATE",
    sourceType: "PMI_ECO_2026",
    sourceConfidence: "HIGH",
  }),
  c({
    id: "integrated-planning",
    nameEn: "Integrated planning",
    nameFr: "Planification intégrée",
    descriptionEn: "Tailoring approach and consolidating plans for delivery.",
    descriptionFr: "Adapter l'approche et consolider les plans de livraison.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T01"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE", "PD-SCOPE"],
    subConceptIds: ["predictive-vs-adaptive", "adaptive-vs-hybrid", "tailoring"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["scope-management", "value-delivery"],
    commonlyConfusedWith: ["governance"],
    skillIds: ["skill-recommend-delivery-approach", "skill-integrated-plan"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "scope-management",
    nameEn: "Scope management",
    nameFr: "Gestion du périmètre",
    descriptionEn: "Defining, agreeing, and controlling what will be delivered.",
    descriptionFr: "Définir, valider et maîtriser ce qui sera livré.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T02"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    subConceptIds: ["scope-vs-change-control", "requested-vs-approved-change"],
    prerequisiteConceptIds: ["integrated-planning"],
    relatedConceptIds: ["change-control", "value-delivery"],
    commonlyConfusedWith: ["change-control"],
    skillIds: ["skill-define-scope", "skill-decompose-scope"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "value-delivery",
    nameEn: "Value-based delivery",
    nameFr: "Livraison axée valeur",
    descriptionEn: "Prioritizing and demonstrating outcomes that matter to stakeholders.",
    descriptionFr: "Prioriser et démontrer des résultats importants pour les parties prenantes.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T03"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    subConceptIds: ["output-vs-outcome", "output-vs-value"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["scope-management"],
    commonlyConfusedWith: ["scope-management"],
    skillIds: ["skill-prioritize-by-value", "skill-track-benefits"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "resource-management",
    nameEn: "Resource management",
    nameFr: "Gestion des ressources",
    descriptionEn: "Planning and optimizing people, tools, and capacity.",
    descriptionFr: "Planifier et optimiser personnes, outils et capacités.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T04"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    subConceptIds: ["resource-availability-vs-utilization"],
    prerequisiteConceptIds: ["integrated-planning"],
    relatedConceptIds: ["team-leadership"],
    commonlyConfusedWith: [],
    skillIds: ["skill-plan-resources", "skill-optimize-resources"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "procurement",
    nameEn: "Procurement",
    nameFr: "Approvisionnements",
    descriptionEn: "Planning, contracting, and managing vendors.",
    descriptionFr: "Planifier, contractualiser et gérer les fournisseurs.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T05"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    subConceptIds: [],
    prerequisiteConceptIds: ["integrated-planning"],
    relatedConceptIds: ["risk-management"],
    commonlyConfusedWith: [],
    skillIds: ["skill-select-contract-type", "skill-manage-vendors"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "project-finance",
    nameEn: "Project finance / cost",
    nameFr: "Finances / coûts du projet",
    descriptionEn: "Budgeting, tracking variances, reserves, and financial governance.",
    descriptionFr: "Budget, écarts, réserves et gouvernance financière.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T06"],
    pmbokPerformanceDomains: ["PD-FINANCE"],
    subConceptIds: ["reserve-vs-budget", "status-vs-forecast", "evm-metric-to-decision"],
    prerequisiteConceptIds: ["integrated-planning"],
    relatedConceptIds: ["project-status"],
    commonlyConfusedWith: [],
    skillIds: [
      "skill-plan-budget",
      "skill-manage-reserves",
      "skill-track-cost-variance",
      "skill-interpret-evm",
    ],
    difficulty: "ADVANCED",
  }),
  c({
    id: "quality-management",
    nameEn: "Quality management",
    nameFr: "Gestion de la qualité",
    descriptionEn: "Requirements, prevention/appraisal/failure costs, QA vs QC.",
    descriptionFr: "Exigences, coûts prévention/appraisal/échec, AQ vs CQ.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T07"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    crossCutting: ["KN-QUALITY"],
    subConceptIds: ["quality-vs-inspection", "prevention-vs-appraisal-cost", "failure-cost-types"],
    prerequisiteConceptIds: ["scope-management"],
    relatedConceptIds: ["compliance"],
    commonlyConfusedWith: [],
    skillIds: ["skill-plan-quality", "skill-distinguish-qa-qc"],
    difficulty: "INTERMEDIATE",
    sourceType: "PMBOK8",
  }),
  c({
    id: "schedule-management",
    nameEn: "Schedule management",
    nameFr: "Gestion de l'échéancier",
    descriptionEn: "Estimating, baselining, and controlling time.",
    descriptionFr: "Estimer, établir une référence et maîtriser le temps.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T08"],
    pmbokPerformanceDomains: ["PD-SCHEDULE"],
    subConceptIds: ["effort-vs-duration", "activity-vs-milestone"],
    prerequisiteConceptIds: ["integrated-planning"],
    relatedConceptIds: ["project-status"],
    commonlyConfusedWith: [],
    skillIds: ["skill-build-schedule", "skill-analyze-schedule-variance"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "project-status",
    nameEn: "Project status assessment",
    nameFr: "Évaluation de l'état du projet",
    descriptionEn: "Metrics, artifacts, progress, and status communication.",
    descriptionFr: "Métriques, artefacts, progrès et communication d'état.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T09"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: ["status-vs-forecast"],
    prerequisiteConceptIds: ["schedule-management", "project-finance"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["project-finance"],
    skillIds: ["skill-define-metrics", "skill-communicate-status"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "project-closure",
    nameEn: "Project closure",
    nameFr: "Clôture du projet",
    descriptionEn: "Acceptance, transition, and formal closeout.",
    descriptionFr: "Acceptation, transition et clôture formelle.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T10"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: [],
    prerequisiteConceptIds: ["project-status"],
    relatedConceptIds: ["continuous-improvement"],
    commonlyConfusedWith: [],
    skillIds: ["skill-close-project", "skill-transition-operations"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "governance",
    nameEn: "Project governance",
    nameFr: "Gouvernance de projet",
    descriptionEn: "Decision rights, escalation, success metrics, and oversight.",
    descriptionFr: "Droits de décision, escalade, métriques de réussite et supervision.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T01"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: ["governance-vs-project-management"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["compliance", "change-control"],
    commonlyConfusedWith: ["integrated-planning"],
    skillIds: ["skill-establish-governance", "skill-define-success-metrics"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "compliance",
    nameEn: "Compliance",
    nameFr: "Conformité",
    descriptionEn: "Regulatory, safety, sustainability, and control requirements.",
    descriptionFr: "Exigences réglementaires, sécurité, durabilité et contrôles.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T02"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: [],
    prerequisiteConceptIds: ["governance"],
    relatedConceptIds: ["quality-management"],
    commonlyConfusedWith: [],
    skillIds: ["skill-assess-compliance", "skill-mitigate-noncompliance"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "change-control",
    nameEn: "Change control",
    nameFr: "Maîtrise des changements",
    descriptionEn: "Evaluating, approving, and implementing controlled changes.",
    descriptionFr: "Évaluer, approuver et mettre en œuvre des changements maîtrisés.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T03"],
    pmbokPerformanceDomains: ["PD-SCOPE", "PD-GOVERNANCE"],
    subConceptIds: ["requested-vs-approved-change", "scope-vs-change-control"],
    prerequisiteConceptIds: ["governance", "scope-management"],
    relatedConceptIds: ["organizational-change"],
    commonlyConfusedWith: ["scope-management"],
    skillIds: ["skill-evaluate-change", "skill-implement-approved-change"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "issue-management",
    nameEn: "Issues and impediments",
    nameFr: "Points à traiter et obstacles",
    descriptionEn: "Current problems blocking progress — distinct from future risks.",
    descriptionFr: "Problèmes actuels bloquant le progrès — distincts des risques futurs.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T04"],
    pmbokPerformanceDomains: ["PD-RISK"],
    subConceptIds: ["conflict-vs-issue", "impediment-vs-issue", "risk-vs-issue"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["conflict-management", "risk-management"],
    commonlyConfusedWith: ["conflict-management", "risk-management"],
    skillIds: ["skill-prioritize-impediments", "skill-resolve-issues"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "risk-management",
    nameEn: "Risk management",
    nameFr: "Gestion des risques",
    descriptionEn: "Uncertainty that may affect objectives — proactive response.",
    descriptionFr: "Incertitude pouvant affecter les objectifs — réponse proactive.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T05"],
    pmbokPerformanceDomains: ["PD-RISK"],
    subConceptIds: ["risk-vs-issue", "risk-response-vs-issue-response"],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["issue-management"],
    commonlyConfusedWith: ["issue-management"],
    skillIds: ["skill-identify-risks", "skill-analyze-risks", "skill-respond-risks"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "continuous-improvement",
    nameEn: "Continuous improvement",
    nameFr: "Amélioration continue",
    descriptionEn: "Lessons learned and updating organizational assets.",
    descriptionFr: "Retours d'expérience et mise à jour des actifs organisationnels.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T06"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["knowledge-transfer", "project-closure"],
    commonlyConfusedWith: [],
    skillIds: ["skill-capture-lessons", "skill-update-process-assets"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "organizational-change",
    nameEn: "Organizational change support",
    nameFr: "Soutien au changement organisationnel",
    descriptionEn: "Helping the organization adopt outcomes of the project.",
    descriptionFr: "Aider l'organisation à adopter les résultats du projet.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T07"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: [],
    prerequisiteConceptIds: ["stakeholder-engagement"],
    relatedConceptIds: ["change-control"],
    commonlyConfusedWith: ["change-control"],
    skillIds: ["skill-assess-culture", "skill-support-adoption"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "external-environment",
    nameEn: "External business environment",
    nameFr: "Environnement commercial externe",
    descriptionEn: "Market, regulatory, and macro changes affecting scope/backlog.",
    descriptionFr: "Changements marché/réglementation/macros affectant périmètre/backlog.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T08"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["value-delivery", "governance"],
    commonlyConfusedWith: [],
    skillIds: ["skill-scan-external-environment", "skill-reprioritize-backlog"],
    difficulty: "ADVANCED",
  }),
  // Sub-concept leaf nodes (referenced above)
  c({
    id: "conflict-vs-issue",
    nameEn: "Conflict vs issue",
    nameFr: "Conflit vs point à traiter",
    descriptionEn: "Interpersonal disagreement vs logged problem requiring action.",
    descriptionFr: "Désaccord interpersonnel vs problème consigné nécessitant action.",
    ecoDomains: ["PEOPLE", "BUSINESS"],
    ecoTaskIds: ["PEOPLE-T02", "BUSINESS-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS", "PD-RISK"],
    parentConceptId: "issue-management",
    subConceptIds: [],
    prerequisiteConceptIds: ["conflict-management", "issue-management"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["conflict-management"],
    skillIds: ["skill-distinguish-conflict-issue"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "risk-vs-issue",
    nameEn: "Risk vs issue",
    nameFr: "Risque vs point à traiter",
    descriptionEn: "Future uncertainty vs present problem.",
    descriptionFr: "Incertitude future vs problème présent.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T04", "BUSINESS-T05"],
    pmbokPerformanceDomains: ["PD-RISK"],
    parentConceptId: "risk-management",
    subConceptIds: [],
    prerequisiteConceptIds: ["risk-management", "issue-management"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["issue-management"],
    skillIds: ["skill-distinguish-risk-issue"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "root-cause-vs-symptom",
    nameEn: "Root cause vs symptom",
    nameFr: "Cause profonde vs symptôme",
    descriptionEn: "Fix the underlying cause, not only visible effects.",
    descriptionFr: "Corriger la cause profonde, pas seulement les effets visibles.",
    ecoDomains: ["PEOPLE", "BUSINESS"],
    ecoTaskIds: ["PEOPLE-T02", "BUSINESS-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "conflict-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-distinguish-root-cause-symptom"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "predictive-vs-adaptive",
    nameEn: "Predictive vs adaptive",
    nameFr: "Prédictif vs adaptatif",
    descriptionEn: "Approach choice depends on uncertainty and stability — not ideology.",
    descriptionFr: "Le choix dépend de l'incertitude et de la stabilité — pas d'idéologie.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T01"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    parentConceptId: "integrated-planning",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["adaptive-vs-hybrid"],
    commonlyConfusedWith: ["adaptive-vs-hybrid"],
    skillIds: ["skill-recommend-delivery-approach"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "adaptive-vs-hybrid",
    nameEn: "Adaptive vs hybrid",
    nameFr: "Adaptatif vs hybride",
    descriptionEn: "Hybrid combines elements by context — not a single fixed recipe.",
    descriptionFr: "L'hybride combine des éléments selon le contexte.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T01"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    parentConceptId: "integrated-planning",
    subConceptIds: [],
    prerequisiteConceptIds: ["predictive-vs-adaptive"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["predictive-vs-adaptive"],
    skillIds: ["skill-recommend-delivery-approach"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "tailoring",
    nameEn: "Tailoring",
    nameFr: "Adaptation (tailoring)",
    descriptionEn: "Right-size processes and artifacts for context.",
    descriptionFr: "Adapter processus et artefacts au contexte.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T01"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    parentConceptId: "integrated-planning",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-tailor-approach"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "requirements-management",
    nameEn: "Requirements vs expectations",
    nameFr: "Exigences vs attentes",
    descriptionEn: "Documented need vs stakeholder belief about outcomes.",
    descriptionFr: "Besoin documenté vs croyance sur les résultats.",
    ecoDomains: ["PEOPLE", "PROCESS"],
    ecoTaskIds: ["PEOPLE-T05", "PROCESS-T02"],
    pmbokPerformanceDomains: ["PD-SCOPE", "PD-STAKEHOLDERS"],
    subConceptIds: [],
    prerequisiteConceptIds: ["expectation-alignment"],
    relatedConceptIds: ["scope-management"],
    commonlyConfusedWith: ["expectation-alignment"],
    skillIds: ["skill-distinguish-requirement-expectation"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "stakeholder-trust",
    nameEn: "Stakeholder trust",
    nameFr: "Confiance des parties prenantes",
    descriptionEn: "Trust enables influence and alignment.",
    descriptionFr: "La confiance permet influence et alignement.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholder-engagement",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-build-trust"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "stakeholder-influence",
    nameEn: "Stakeholder influence",
    nameFr: "Influence des parties prenantes",
    descriptionEn: "Using appropriate influence strategies ethically.",
    descriptionFr: "Utiliser des stratégies d'influence appropriées et éthiques.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T04"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "stakeholder-engagement",
    subConceptIds: [],
    prerequisiteConceptIds: ["stakeholder-analysis"],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-influence-stakeholders"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "leadership-vs-authority",
    nameEn: "Leadership vs authority",
    nameFr: "Leadership vs autorité",
    descriptionEn: "Influence without positional power vs formal decision rights.",
    descriptionFr: "Influence sans pouvoir formel vs droits de décision.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T03"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    parentConceptId: "team-leadership",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["governance"],
    commonlyConfusedWith: ["governance"],
    skillIds: ["skill-select-leadership-style"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "coaching-vs-directing",
    nameEn: "Coaching vs directing",
    nameFr: "Coaching vs direction",
    descriptionEn: "Developing capability vs giving instructions.",
    descriptionFr: "Développer les capacités vs donner des instructions.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T03"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    parentConceptId: "team-leadership",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-coach-team"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "empowerment-vs-delegation",
    nameEn: "Empowerment vs delegation",
    nameFr: "Autonomisation vs délégation",
    descriptionEn: "Shared ownership vs assigning tasks with accountability.",
    descriptionFr: "Propriété partagée vs assignation de tâches avec responsabilité.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T03"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    parentConceptId: "team-leadership",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-empower-team"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "quality-vs-inspection",
    nameEn: "Quality management vs inspection",
    nameFr: "Gestion qualité vs inspection",
    descriptionEn: "Building quality in vs detecting defects after the fact.",
    descriptionFr: "Construire la qualité vs détecter les défauts après coup.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T07"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    crossCutting: ["KN-QUALITY"],
    parentConceptId: "quality-management",
    subConceptIds: [],
    prerequisiteConceptIds: ["quality-management"],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-distinguish-qa-qc"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "prevention-vs-appraisal-cost",
    nameEn: "Prevention vs appraisal cost",
    nameFr: "Coût prévention vs appraisal",
    descriptionEn: "Cost of preventing defects vs cost of measuring quality.",
    descriptionFr: "Coût de prévention vs coût de mesure de la qualité.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T07"],
    pmbokPerformanceDomains: ["PD-FINANCE"],
    crossCutting: ["KN-QUALITY"],
    parentConceptId: "quality-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: ["failure-cost-types"],
    skillIds: ["skill-explain-cost-of-quality"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "failure-cost-types",
    nameEn: "Failure cost types",
    nameFr: "Types de coûts d'échec",
    descriptionEn: "Internal vs external failure — distinct from prevention/appraisal.",
    descriptionFr: "Échec interne vs externe — distinct de prévention/appraisal.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T07"],
    pmbokPerformanceDomains: ["PD-FINANCE"],
    crossCutting: ["KN-QUALITY"],
    parentConceptId: "quality-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: ["prevention-vs-appraisal-cost"],
    skillIds: ["skill-explain-cost-of-quality"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "scope-vs-change-control",
    nameEn: "Scope vs change control",
    nameFr: "Périmètre vs maîtrise des changements",
    descriptionEn: "Defining scope vs governing how changes enter the baseline.",
    descriptionFr: "Définir le périmètre vs gouverner l'entrée des changements.",
    ecoDomains: ["PROCESS", "BUSINESS"],
    ecoTaskIds: ["PROCESS-T02", "BUSINESS-T03"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    parentConceptId: "change-control",
    subConceptIds: [],
    prerequisiteConceptIds: ["scope-management", "change-control"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["change-control"],
    skillIds: ["skill-evaluate-change"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "requested-vs-approved-change",
    nameEn: "Requested vs approved change",
    nameFr: "Changement demandé vs approuvé",
    descriptionEn: "A request is not authorization to implement.",
    descriptionFr: "Une demande n'est pas une autorisation de mise en œuvre.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T03"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    parentConceptId: "change-control",
    subConceptIds: [],
    prerequisiteConceptIds: ["change-control"],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-implement-approved-change"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "impediment-vs-issue",
    nameEn: "Impediment vs issue",
    nameFr: "Obstacle vs point à traiter",
    descriptionEn: "Blockers may be operational impediments or formal issues.",
    descriptionFr: "Les blocages peuvent être obstacles opérationnels ou points formels.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T04"],
    pmbokPerformanceDomains: ["PD-RISK"],
    parentConceptId: "issue-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: ["issue-management"],
    skillIds: ["skill-prioritize-impediments"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "governance-vs-project-management",
    nameEn: "Governance vs project management",
    nameFr: "Gouvernance vs management de projet",
    descriptionEn: "Oversight and decision forums vs day-to-day delivery leadership.",
    descriptionFr: "Supervision et instances de décision vs direction opérationnelle.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T01"],
    pmbokPerformanceDomains: ["PD-GOVERNANCE"],
    parentConceptId: "governance",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["integrated-planning"],
    commonlyConfusedWith: ["integrated-planning"],
    skillIds: ["skill-establish-governance"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "effort-vs-duration",
    nameEn: "Effort vs duration",
    nameFr: "Effort vs durée",
    descriptionEn: "Person-hours differ from calendar elapsed time.",
    descriptionFr: "Heures-personnes différentes du temps calendaire écoulé.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T08"],
    pmbokPerformanceDomains: ["PD-SCHEDULE"],
    parentConceptId: "schedule-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-estimate-work"],
    difficulty: "BEGINNER",
  }),
  c({
    id: "activity-vs-milestone",
    nameEn: "Activity vs milestone",
    nameFr: "Activité vs jalon",
    descriptionEn: "Work packages vs zero-duration checkpoints.",
    descriptionFr: "Lots de travail vs points de contrôle sans durée.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T08"],
    pmbokPerformanceDomains: ["PD-SCHEDULE"],
    parentConceptId: "schedule-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-build-schedule"],
    difficulty: "BEGINNER",
  }),
  c({
    id: "resource-availability-vs-utilization",
    nameEn: "Resource availability vs utilization",
    nameFr: "Disponibilité vs utilisation des ressources",
    descriptionEn: "Capacity on calendar vs assigned load.",
    descriptionFr: "Capacité calendaire vs charge assignée.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T04"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    parentConceptId: "resource-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-optimize-resources"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "output-vs-outcome",
    nameEn: "Output vs outcome",
    nameFr: "Output vs outcome",
    descriptionEn: "Deliverable produced vs result experienced by stakeholders.",
    descriptionFr: "Livrable produit vs résultat vécu par les parties prenantes.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T03"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    parentConceptId: "value-delivery",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["output-vs-value"],
    commonlyConfusedWith: ["output-vs-value"],
    skillIds: ["skill-track-benefits"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "output-vs-value",
    nameEn: "Output vs value",
    nameFr: "Output vs valeur",
    descriptionEn: "Shipping features vs delivering measurable value.",
    descriptionFr: "Livrer des fonctionnalités vs créer de la valeur mesurable.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T03"],
    pmbokPerformanceDomains: ["PD-SCOPE"],
    parentConceptId: "value-delivery",
    subConceptIds: [],
    prerequisiteConceptIds: ["output-vs-outcome"],
    relatedConceptIds: [],
    commonlyConfusedWith: ["scope-management"],
    skillIds: ["skill-prioritize-by-value"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "status-vs-forecast",
    nameEn: "Status vs forecast",
    nameFr: "État vs prévision",
    descriptionEn: "What happened vs what is expected to happen.",
    descriptionFr: "Ce qui s'est passé vs ce qui est attendu.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T09", "PROCESS-T06"],
    pmbokPerformanceDomains: ["PD-FINANCE", "PD-GOVERNANCE"],
    parentConceptId: "project-status",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["reserve-vs-budget"],
    commonlyConfusedWith: [],
    skillIds: ["skill-communicate-status"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "reserve-vs-budget",
    nameEn: "Reserve vs budget",
    nameFr: "Réserve vs budget",
    descriptionEn: "Contingency/management reserves vs baseline budget.",
    descriptionFr: "Réserves vs budget de référence.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T06"],
    pmbokPerformanceDomains: ["PD-FINANCE"],
    parentConceptId: "project-finance",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-manage-reserves"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "risk-response-vs-issue-response",
    nameEn: "Risk response vs issue response",
    nameFr: "Réponse risque vs réponse point à traiter",
    descriptionEn: "Proactive uncertainty handling vs reactive problem resolution.",
    descriptionFr: "Gestion proactive de l'incertitude vs résolution réactive.",
    ecoDomains: ["BUSINESS"],
    ecoTaskIds: ["BUSINESS-T04", "BUSINESS-T05"],
    pmbokPerformanceDomains: ["PD-RISK"],
    parentConceptId: "risk-management",
    subConceptIds: [],
    prerequisiteConceptIds: ["risk-vs-issue"],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-respond-risks", "skill-resolve-issues"],
    difficulty: "ADVANCED",
  }),
  c({
    id: "collaboration-vs-compromise",
    nameEn: "Collaboration vs compromise",
    nameFr: "Collaboration vs compromis",
    descriptionEn: "Conflict modes — win-win vs split-the-difference.",
    descriptionFr: "Modes de conflit — gagnant-gagnant vs partage.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T02"],
    pmbokPerformanceDomains: ["PD-STAKEHOLDERS"],
    parentConceptId: "conflict-management",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: [],
    commonlyConfusedWith: [],
    skillIds: ["skill-select-conflict-response"],
    difficulty: "INTERMEDIATE",
  }),
  c({
    id: "tacit-vs-explicit-knowledge",
    nameEn: "Tacit vs explicit knowledge",
    nameFr: "Connaissance tacite vs explicite",
    descriptionEn:
      "Hard-to-codify experience vs easily documented words, images, numbers.",
    descriptionFr:
      "Expérience difficile à codifier vs mots, images, chiffres documentables.",
    ecoDomains: ["PEOPLE"],
    ecoTaskIds: ["PEOPLE-T07"],
    pmbokPerformanceDomains: ["PD-RESOURCES"],
    parentConceptId: "knowledge-transfer",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["communication-planning"],
    commonlyConfusedWith: ["communication-planning"],
    skillIds: ["skill-choose-knowledge-transfer-method"],
    difficulty: "INTERMEDIATE",
    sourceType: "INSTRUCTOR_DERIVED",
    sourceConfidence: "HIGH",
  }),
  c({
    id: "deliverable-vs-outcome-vs-value",
    nameEn: "Deliverable vs outcome vs value",
    nameFr: "Livrable vs résultat vs valeur",
    descriptionEn: "What is produced vs what changes vs perceived benefit.",
    descriptionFr: "Ce qui est produit vs ce qui change vs bénéfice perçu.",
    ecoDomains: ["PEOPLE", "PROCESS"],
    ecoTaskIds: ["PEOPLE-T01", "PROCESS-T03"],
    pmbokPerformanceDomains: ["PD-SCOPE", "PD-STAKEHOLDERS"],
    parentConceptId: "shared-vision",
    subConceptIds: [],
    prerequisiteConceptIds: [],
    relatedConceptIds: ["output-vs-outcome", "output-vs-value"],
    commonlyConfusedWith: ["output-vs-value"],
    skillIds: ["skill-facilitate-shared-vision"],
    difficulty: "INTERMEDIATE",
    sourceType: "INSTRUCTOR_DERIVED",
    sourceConfidence: "HIGH",
  }),
  c({
    id: "evm-metric-to-decision",
    nameEn: "EVM metric to decision",
    nameFr: "EVM : métrique vers décision",
    descriptionEn: "PV/EV/AC → CPI/SPI → forecast → action — not math for its own sake.",
    descriptionFr: "PV/EV/AC → CPI/SPI → prévision → action — pas du calcul isolé.",
    ecoDomains: ["PROCESS"],
    ecoTaskIds: ["PROCESS-T06"],
    pmbokPerformanceDomains: ["PD-FINANCE"],
    parentConceptId: "project-finance",
    subConceptIds: [],
    prerequisiteConceptIds: ["status-vs-forecast"],
    relatedConceptIds: ["project-status"],
    commonlyConfusedWith: [],
    skillIds: ["skill-interpret-evm"],
    difficulty: "ADVANCED",
    sourceType: "INSTRUCTOR_DERIVED",
    sourceConfidence: "HIGH",
  }),
];

const BY_ID = new Map(CONCEPTS.map((c) => [c.id, c] as const));

export function getConcept(id: string): ConceptRecord | undefined {
  return BY_ID.get(id);
}

export function requireConcept(id: string): ConceptRecord {
  const c = BY_ID.get(id);
  if (!c) throw new Error(`Unknown concept: ${id}`);
  return c;
}

export function conceptsForEcoTask(taskId: EcoTaskStableId): ConceptRecord[] {
  return CONCEPTS.filter((c) => c.ecoTaskIds.includes(taskId));
}

export function conceptsForPmbokDomain(pd: PmbokPerformanceDomainId): ConceptRecord[] {
  return CONCEPTS.filter((c) => c.pmbokPerformanceDomains.includes(pd));
}

export const CONCEPT_COUNT = CONCEPTS.length;

export function listSubConcepts(parentId: string): ConceptRecord[] {
  return CONCEPTS.filter((c) => c.parentConceptId === parentId);
}
