/**
 * Critical distinction cards — Phase B.3 blueprint §13.
 * Pedagogical micro-cards only. Not exam bank items. Not PMI official wording.
 * Source: instructor course condensé (authorized prompt blueprint).
 */

import type { ContentProvenance, EcoTaskStableId } from "./types";

export type CriticalDistinctionCard = {
  id: string;
  leftFr: string;
  leftEn: string;
  rightFr: string;
  rightEn: string;
  /** Optional third pole (e.g. deliverable / outcome / value). */
  middleFr?: string;
  middleEn?: string;
  ruleFr: string;
  ruleEn: string;
  examCueFr: string;
  examCueEn: string;
  ecoTaskIds: EcoTaskStableId[];
  relatedConceptIds: string[];
  instructorLessonIds: string[];
  provenance: ContentProvenance;
  visualHint?: string;
};

function d(
  partial: CriticalDistinctionCard
): CriticalDistinctionCard {
  return partial;
}

export const CRITICAL_DISTINCTIONS: readonly CriticalDistinctionCard[] = [
  d({
    id: "dist-vision-goal-value",
    leftFr: "Vision",
    leftEn: "Vision",
    middleFr: "Objectif",
    middleEn: "Goal",
    rightFr: "Valeur",
    rightEn: "Value",
    ruleFr: "Vision = image partagée du succès ; objectif = cible mesurable ; valeur = bénéfice perçu.",
    ruleEn: "Vision = shared success picture; goal = measurable target; value = perceived benefit.",
    examCueFr: "Si les acteurs divergent sur le succès → aligner la vision avant d'ajouter du scope.",
    examCueEn: "If actors diverge on success → align vision before adding scope.",
    ecoTaskIds: ["PEOPLE-T01", "PROCESS-T03"],
    relatedConceptIds: ["shared-vision", "deliverable-vs-outcome-vs-value"],
    instructorLessonIds: ["INSTRUCTOR-L02"],
    provenance: "INSTRUCTOR_DERIVED",
    visualHint: "vision → objectives → value",
  }),
  d({
    id: "dist-project-vs-product-scope",
    leftFr: "Périmètre projet",
    leftEn: "Project scope",
    rightFr: "Périmètre produit",
    rightEn: "Product scope",
    ruleFr: "Project scope = travail pour produire le résultat. Product scope = caractéristiques du produit.",
    ruleEn: "Project scope = work to produce the result. Product scope = product features/characteristics.",
    examCueFr: "Changement de feature ≠ toujours même processus que changement de travail projet.",
    examCueEn: "A feature change is not always the same process as project-work change.",
    ecoTaskIds: ["PROCESS-T02"],
    relatedConceptIds: ["scope-management"],
    instructorLessonIds: ["INSTRUCTOR-L03"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-dor-vs-dod",
    leftFr: "DoR",
    leftEn: "DoR",
    rightFr: "DoD",
    rightEn: "DoD",
    ruleFr: "DoR = prêts à commencer ? DoD = réellement terminé ?",
    ruleEn: "DoR = ready to start? DoD = actually done?",
    examCueFr: "Ne commencez pas un item non prêt ; ne clôturez pas un item non Done.",
    examCueEn: "Do not start an unready item; do not close an item that is not Done.",
    ecoTaskIds: ["PROCESS-T02", "PROCESS-T07"],
    relatedConceptIds: ["scope-management", "quality-management"],
    instructorLessonIds: ["INSTRUCTOR-L03", "INSTRUCTOR-L05"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-deliverable-outcome-benefit-value",
    leftFr: "Livrable",
    leftEn: "Deliverable",
    middleFr: "Résultat / Bénéfice",
    middleEn: "Outcome / Benefit",
    rightFr: "Valeur",
    rightEn: "Value",
    ruleFr: "Livrer ≠ créer automatiquement de la valeur. Chaîne : deliverable → outcome → benefit → value.",
    ruleEn: "Shipping ≠ automatic value. Chain: deliverable → outcome → benefit → value.",
    examCueFr: "Si le livrable est OK mais personne n'en tire bénéfice → problème de valeur, pas seulement de scope.",
    examCueEn: "If deliverable is OK but no one benefits → value problem, not only scope.",
    ecoTaskIds: ["PROCESS-T03", "PEOPLE-T01"],
    relatedConceptIds: ["value-delivery", "output-vs-outcome", "output-vs-value"],
    instructorLessonIds: ["INSTRUCTOR-L03"],
    provenance: "INSTRUCTOR_DERIVED",
    visualHint: "deliverable → outcome → benefit → value",
  }),
  d({
    id: "dist-risk-vs-issue",
    leftFr: "Risque",
    leftEn: "Risk",
    rightFr: "Point à traiter (issue)",
    rightEn: "Issue",
    ruleFr: "Risque = incertitude future. Issue = condition actuelle.",
    ruleEn: "Risk = future uncertainty. Issue = present condition.",
    examCueFr: "Si c'est déjà arrivé → issue/impediment, pas une réponse risque proactive seule.",
    examCueEn: "If it already happened → issue/impediment, not a proactive risk response alone.",
    ecoTaskIds: ["BUSINESS-T04", "BUSINESS-T05"],
    relatedConceptIds: ["risk-vs-issue", "risk-management", "issue-management"],
    instructorLessonIds: ["INSTRUCTOR-L08"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-threat-vs-opportunity",
    leftFr: "Menace",
    leftEn: "Threat",
    rightFr: "Opportunité",
    rightEn: "Opportunity",
    ruleFr: "Menace = impact négatif potentiel. Opportunité = impact positif potentiel.",
    ruleEn: "Threat = potential negative impact. Opportunity = potential positive impact.",
    examCueFr: "Réponses menace ≠ réponses opportunité (éviter/mitiger vs exploiter/améliorer).",
    examCueEn: "Threat responses ≠ opportunity responses (avoid/mitigate vs exploit/enhance).",
    ecoTaskIds: ["BUSINESS-T05"],
    relatedConceptIds: ["risk-management"],
    instructorLessonIds: ["INSTRUCTOR-L08"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-appetite-vs-threshold",
    leftFr: "Appétit au risque",
    leftEn: "Risk appetite",
    rightFr: "Seuil de risque",
    rightEn: "Risk threshold",
    ruleFr: "Appétit = niveau d'incertitude accepté. Seuil = variation acceptable autour d'un objectif.",
    ruleEn: "Appetite = accepted uncertainty level. Threshold = acceptable variance around an objective.",
    examCueFr: "Dépasser un seuil déclenche action/escalade même si l'appétit global reste large.",
    examCueEn: "Crossing a threshold triggers action/escalation even if overall appetite is wide.",
    ecoTaskIds: ["BUSINESS-T05"],
    relatedConceptIds: ["risk-management"],
    instructorLessonIds: ["INSTRUCTOR-L08"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-corrective-preventive-defect",
    leftFr: "Corrective",
    leftEn: "Corrective",
    middleFr: "Préventive",
    middleEn: "Preventive",
    rightFr: "Réparation de défaut",
    rightEn: "Defect repair",
    ruleFr: "Corrective = réaligner après écart. Préventive = éviter un écart futur. Defect repair = corriger non-conformité.",
    ruleEn: "Corrective = realign after variance. Preventive = avoid future variance. Defect repair = fix nonconformance.",
    examCueFr: "Identifier le type avant d'agir — le processus de changement peut différer.",
    examCueEn: "Identify the type before acting — change handling may differ.",
    ecoTaskIds: ["BUSINESS-T03"],
    relatedConceptIds: ["change-control"],
    instructorLessonIds: ["INSTRUCTOR-L08"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-predictive-vs-adaptive-change",
    leftFr: "Changement prédictif",
    leftEn: "Predictive change",
    rightFr: "Changement adaptatif",
    rightEn: "Adaptive change",
    ruleFr: "Prédictif = change control formel / CCB. Adaptatif = backlog évolutif / PO priorise. Ne pas coller un CCB à chaque sprint.",
    ruleEn: "Predictive = formal change control / CCB. Adaptive = evolving backlog / PO prioritizes. Do not force CCB onto every sprint.",
    examCueFr: "Lisez d'abord l'approche de livraison du scénario.",
    examCueEn: "First read the scenario's delivery approach.",
    ecoTaskIds: ["BUSINESS-T03", "PROCESS-T01"],
    relatedConceptIds: ["change-control", "integrated-planning"],
    instructorLessonIds: ["INSTRUCTOR-L08", "INSTRUCTOR-L01"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-engagement-vs-communication",
    leftFr: "Engagement (T04)",
    leftEn: "Engagement (T04)",
    rightFr: "Communication (T08)",
    rightEn: "Communication (T08)",
    ruleFr: "T04 = implication/relation/engagement. T08 = information/canal/fréquence/transparence. Informer ≠ engager.",
    ruleEn: "T04 = involvement/relationship/engagement. T08 = information/channel/frequency/transparency. Informing ≠ engaging.",
    examCueFr: "Besoin de commitment → T04. Besoin de clarté d'info → T08.",
    examCueEn: "Need commitment → T04. Need information clarity → T08.",
    ecoTaskIds: ["PEOPLE-T04", "PEOPLE-T08"],
    relatedConceptIds: ["stakeholder-engagement", "communication-planning", "communication-vs-engagement"],
    instructorLessonIds: ["INSTRUCTOR-L02", "INSTRUCTOR-L06"],
    provenance: "INSTRUCTOR_DERIVED",
    visualHint: "T04 vs T08 side-by-side",
  }),
  d({
    id: "dist-knowledge-transfer-vs-communication",
    leftFr: "Transfert de connaissances (T07)",
    leftEn: "Knowledge transfer (T07)",
    rightFr: "Communication (T08)",
    rightEn: "Communication (T08)",
    ruleFr: "T07 = faire circuler/préserver le SAVOIR et la capacité. T08 = bonne information, bonnes personnes, bon moment/canal.",
    ruleEn: "T07 = circulate/preserve KNOW-HOW and capability. T08 = right information, right people, right time/channel.",
    examCueFr: "Expert qui part → T07 (pairing/coaching). Rumeurs de date → T08 (canal officiel).",
    examCueEn: "Expert leaving → T07 (pairing/coaching). Date rumors → T08 (official channel).",
    ecoTaskIds: ["PEOPLE-T07", "PEOPLE-T08"],
    relatedConceptIds: ["knowledge-transfer", "communication-planning", "tacit-vs-explicit-knowledge"],
    instructorLessonIds: ["INSTRUCTOR-L06"],
    provenance: "INSTRUCTOR_DERIVED",
    visualHint: "T07 vs T08 side-by-side",
  }),
  d({
    id: "dist-recognition-vs-reward",
    leftFr: "Reconnaissance",
    leftEn: "Recognition",
    rightFr: "Récompense",
    rightEn: "Reward",
    ruleFr: "Reconnaissance = appréciation du comportement. Récompense = avantage concret lié au résultat.",
    ruleEn: "Recognition = appreciation of behavior. Reward = concrete benefit tied to result.",
    examCueFr: "Motivation ≠ uniquement bonus ; la reconnaissance peut être le levier adapté.",
    examCueEn: "Motivation ≠ only bonuses; recognition may be the fit lever.",
    ecoTaskIds: ["PEOPLE-T03"],
    relatedConceptIds: ["team-leadership"],
    instructorLessonIds: ["INSTRUCTOR-L07"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-leadership-vs-management",
    leftFr: "Leadership",
    leftEn: "Leadership",
    rightFr: "Management",
    rightEn: "Management",
    ruleFr: "Leadership = direction, influence, sens. Management = planification, contrôle, coordination.",
    ruleEn: "Leadership = direction, influence, meaning. Management = planning, control, coordination.",
    examCueFr: "Équipe démotivée → leadership/servant. Baseline dérive → management/contrôle.",
    examCueEn: "Demotivated team → leadership/servant. Baseline drift → management/control.",
    ecoTaskIds: ["PEOPLE-T03"],
    relatedConceptIds: ["team-leadership"],
    instructorLessonIds: ["INSTRUCTOR-L07"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-pm-vs-po-vs-sm",
    leftFr: "Chef de projet",
    leftEn: "Project manager",
    middleFr: "Product Owner",
    middleEn: "Product Owner",
    rightFr: "Scrum Master / coach agile",
    rightEn: "Scrum Master / agile coach",
    ruleFr: "PM = intégration/livraison selon contexte. PO = maximise valeur produit. SM/coach = facilite le système agile.",
    ruleEn: "PM = integration/delivery by context. PO = maximizes product value. SM/coach = facilitates the agile system.",
    examCueFr: "Priorité backlog → PO. Obstacle d'équipe → SM/coach. Intégration multi-domaines → PM.",
    examCueEn: "Backlog priority → PO. Team impediment → SM/coach. Cross-domain integration → PM.",
    ecoTaskIds: ["PROCESS-T03", "PEOPLE-T03", "PROCESS-T01"],
    relatedConceptIds: ["value-delivery", "team-leadership"],
    instructorLessonIds: ["INSTRUCTOR-L01", "INSTRUCTOR-L04", "INSTRUCTOR-L07"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-opa-vs-eef",
    leftFr: "OPA",
    leftEn: "OPA",
    rightFr: "EEF",
    rightEn: "EEF",
    ruleFr: "OPA = actifs/processus/connaissances internes. EEF = facteurs environnementaux qui influencent le projet.",
    ruleEn: "OPA = internal assets/processes/knowledge. EEF = environmental factors influencing the project.",
    examCueFr: "Mettre à jour un template → OPA. Nouvelle régulation marché → EEF.",
    examCueEn: "Updating a template → OPA. New market regulation → EEF.",
    ecoTaskIds: ["BUSINESS-T06", "BUSINESS-T08"],
    relatedConceptIds: ["continuous-improvement", "external-environment"],
    instructorLessonIds: ["INSTRUCTOR-L11"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-quality-vs-grade",
    leftFr: "Qualité",
    leftEn: "Quality",
    rightFr: "Grade",
    rightEn: "Grade",
    ruleFr: "Qualité = conformité aux exigences. Grade = catégorie/caractéristiques (peut être bas sans défaut).",
    ruleEn: "Quality = conformance to requirements. Grade = category/features (can be low without defects).",
    examCueFr: "Bas grade ≠ mauvaise qualité si les exigences sont respectées.",
    examCueEn: "Low grade ≠ poor quality if requirements are met.",
    ecoTaskIds: ["PROCESS-T07"],
    relatedConceptIds: ["quality-management"],
    instructorLessonIds: ["INSTRUCTOR-L05"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-contingency-vs-management-reserve",
    leftFr: "Réserve de contingence",
    leftEn: "Contingency reserve",
    rightFr: "Réserve de management",
    rightEn: "Management reserve",
    ruleFr: "Contingence = risques connus (souvent dans baseline). Management reserve = inconnu/imprévu (hors baseline typique).",
    ruleEn: "Contingency = known risks (often in baseline). Management reserve = unknown/unforeseen (typically outside baseline).",
    examCueFr: "Risque identifié → contingence. Inconnu → management reserve / gouvernance.",
    examCueEn: "Identified risk → contingency. Unknown → management reserve / governance.",
    ecoTaskIds: ["PROCESS-T06", "BUSINESS-T05"],
    relatedConceptIds: ["reserve-vs-budget", "project-finance"],
    instructorLessonIds: ["INSTRUCTOR-L04", "INSTRUCTOR-L08"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-raci",
    leftFr: "R / A",
    leftEn: "R / A",
    rightFr: "C / I",
    rightEn: "C / I",
    ruleFr: "Au moins un R ; un seul A par tâche ; C contribue ; I est informé.",
    ruleEn: "At least one R; exactly one A per task; C contributes; I is informed.",
    examCueFr: "Deux A sur la même tâche = confusion d'autorité.",
    examCueEn: "Two As on the same task = authority confusion.",
    ecoTaskIds: ["PROCESS-T04", "PEOPLE-T03"],
    relatedConceptIds: ["resource-management", "team-leadership"],
    instructorLessonIds: ["INSTRUCTOR-L04", "INSTRUCTOR-L07"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-pv-ev-ac",
    leftFr: "PV",
    leftEn: "PV",
    middleFr: "EV",
    middleEn: "EV",
    rightFr: "AC",
    rightEn: "AC",
    ruleFr: "PV = planifié. EV = valeur du travail accompli. AC = coût réel.",
    ruleEn: "PV = planned. EV = earned for work done. AC = actual cost.",
    examCueFr: "Comparer les trois avant de conclure sur coût ou délai.",
    examCueEn: "Compare all three before concluding on cost or schedule.",
    ecoTaskIds: ["PROCESS-T06", "PROCESS-T09"],
    relatedConceptIds: ["project-finance", "evm-metric-to-decision"],
    instructorLessonIds: ["INSTRUCTOR-L04", "INSTRUCTOR-L09"],
    provenance: "INSTRUCTOR_DERIVED",
    visualHint: "PV/EV/AC dashboard",
  }),
  d({
    id: "dist-cpi-vs-spi",
    leftFr: "CPI",
    leftEn: "CPI",
    rightFr: "SPI",
    rightEn: "SPI",
    ruleFr: "CPI = EV/AC (efficacité coût). SPI = EV/PV (efficacité planning).",
    ruleEn: "CPI = EV/AC (cost efficiency). SPI = EV/PV (schedule efficiency).",
    examCueFr: "CPI < 1 → coût. SPI < 1 → planning. Puis décider.",
    examCueEn: "CPI < 1 → cost. SPI < 1 → schedule. Then decide.",
    ecoTaskIds: ["PROCESS-T06", "PROCESS-T08", "PROCESS-T09"],
    relatedConceptIds: ["evm-metric-to-decision", "schedule-management"],
    instructorLessonIds: ["INSTRUCTOR-L04", "INSTRUCTOR-L09"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-eac-vs-etc",
    leftFr: "EAC",
    leftEn: "EAC",
    rightFr: "ETC",
    rightEn: "ETC",
    ruleFr: "EAC = projection du coût total. ETC = travail restant en coût (souvent EAC − AC). Ex. EAC = BAC/CPI si tendance stable.",
    ruleEn: "EAC = projected total cost. ETC = remaining cost (often EAC − AC). E.g. EAC = BAC/CPI if trend continues.",
    examCueFr: "Ne confondez pas BAC (plan) et EAC (prévision).",
    examCueEn: "Do not confuse BAC (plan) and EAC (forecast).",
    ecoTaskIds: ["PROCESS-T06"],
    relatedConceptIds: ["project-finance", "status-vs-forecast"],
    instructorLessonIds: ["INSTRUCTOR-L04"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-project-program-portfolio",
    leftFr: "Projet",
    leftEn: "Project",
    middleFr: "Programme",
    middleEn: "Program",
    rightFr: "Portefeuille",
    rightEn: "Portfolio",
    ruleFr: "Projet = résultats spécifiques. Programme = bénéfices via projets liés. Portefeuille = alignement stratégique.",
    ruleEn: "Project = specific outcomes. Program = benefits via related projects. Portfolio = strategic alignment.",
    examCueFr: "Décision stratégique multi-projets → portfolio, pas micro-gestion d'un seul projet.",
    examCueEn: "Multi-project strategic decision → portfolio, not micromanaging one project.",
    ecoTaskIds: ["PROCESS-T01", "BUSINESS-T01"],
    relatedConceptIds: ["integrated-planning", "governance"],
    instructorLessonIds: ["INSTRUCTOR-L01"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
  d({
    id: "dist-risk-vs-impediment",
    leftFr: "Issue",
    leftEn: "Issue",
    rightFr: "Impediment / obstacle",
    rightEn: "Impediment / obstacle",
    ruleFr: "Issue = condition actuelle. Impediment = bloque/ralentit l'équipe maintenant.",
    ruleEn: "Issue = present condition. Impediment = blocks/slows the team now.",
    examCueFr: "Équipe bloquée → lever l'obstacle ; ne pas seulement logger un risque futur.",
    examCueEn: "Team blocked → remove impediment; do not only log a future risk.",
    ecoTaskIds: ["BUSINESS-T04"],
    relatedConceptIds: ["issue-management"],
    instructorLessonIds: ["INSTRUCTOR-L08"],
    provenance: "INSTRUCTOR_DERIVED",
  }),
];

export function getDistinction(id: string): CriticalDistinctionCard | undefined {
  return CRITICAL_DISTINCTIONS.find((x) => x.id === id);
}

export function distinctionsForEcoTask(
  ecoTaskId: EcoTaskStableId
): CriticalDistinctionCard[] {
  return CRITICAL_DISTINCTIONS.filter((d) => d.ecoTaskIds.includes(ecoTaskId));
}

export function distinctionsForInstructorLesson(
  lessonId: string
): CriticalDistinctionCard[] {
  return CRITICAL_DISTINCTIONS.filter((d) =>
    d.instructorLessonIds.includes(lessonId)
  );
}

export const CRITICAL_DISTINCTION_COUNT = CRITICAL_DISTINCTIONS.length;
