/**
 * Measurable mastery skills — bridge concepts to questions & attempts.
 */

import type { CognitiveLevel, MasterySkillRecord } from "./types";

function s(
  partial: Omit<MasterySkillRecord, "sourceType" | "sourceConfidence"> & {
    sourceConfidence?: MasterySkillRecord["sourceConfidence"];
  }
): MasterySkillRecord {
  return {
    ...partial,
    sourceType: "DERIVED_PEDAGOGICAL",
    sourceConfidence: partial.sourceConfidence ?? "MEDIUM",
  };
}

export const MASTERY_SKILLS: readonly MasterySkillRecord[] = [
  s({ id: "skill-identify-stakeholder", conceptId: "stakeholder-identification", nameEn: "Identify stakeholders", nameFr: "Identifier les parties prenantes", descriptionEn: "Discover affected parties early.", descriptionFr: "Découvrir tôt les parties impactées.", prerequisiteSkillIds: [], difficulty: "BEGINNER", cognitiveLevel: "RECOGNITION", plaSkillSlug: "stakeholder-engagement" }),
  s({ id: "skill-analyze-stakeholder", conceptId: "stakeholder-analysis", nameEn: "Analyze stakeholders", nameFr: "Analyser les parties prenantes", descriptionEn: "Assess interest, influence, and engagement needs.", descriptionFr: "Évaluer intérêt, influence et besoins.", prerequisiteSkillIds: ["skill-identify-stakeholder"], difficulty: "INTERMEDIATE", cognitiveLevel: "ANALYSIS", plaSkillSlug: "stakeholder-engagement" }),
  s({ id: "skill-engagement-strategy", conceptId: "stakeholder-engagement", nameEn: "Determine engagement strategy", nameFr: "Déterminer la stratégie d'engagement", descriptionEn: "Choose actions that improve commitment.", descriptionFr: "Choisir des actions qui améliorent l'engagement.", prerequisiteSkillIds: ["skill-analyze-stakeholder"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "stakeholder-engagement" }),
  s({ id: "skill-distinguish-communication-engagement", conceptId: "communication-vs-engagement", nameEn: "Distinguish communication from engagement", nameFr: "Distinguer communication et engagement", descriptionEn: "Select engagement actions vs information-only steps.", descriptionFr: "Choisir engagement vs simple information.", prerequisiteSkillIds: ["skill-engagement-strategy"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "communication" }),
  s({ id: "skill-build-trust", conceptId: "stakeholder-trust", nameEn: "Build stakeholder trust", nameFr: "Instaurer la confiance", descriptionEn: "Act transparently to enable influence.", descriptionFr: "Agir avec transparence pour influencer.", prerequisiteSkillIds: ["skill-analyze-stakeholder"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "stakeholder-engagement" }),
  s({ id: "skill-influence-stakeholders", conceptId: "stakeholder-influence", nameEn: "Influence stakeholders", nameFr: "Influencer les parties prenantes", descriptionEn: "Apply ethical influence toward project goals.", descriptionFr: "Influencer éthiquement vers les objectifs.", prerequisiteSkillIds: ["skill-build-trust"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "stakeholder-engagement" }),
  s({ id: "skill-align-expectations", conceptId: "expectation-alignment", nameEn: "Align expectations", nameFr: "Aligner les attentes", descriptionEn: "Facilitate shared success criteria.", descriptionFr: "Faciliter des critères de réussite partagés.", prerequisiteSkillIds: ["skill-analyze-stakeholder"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-manage-expectations", conceptId: "expectation-management", nameEn: "Manage expectations", nameFr: "Piloter les attentes", descriptionEn: "Monitor and adjust vs stakeholder satisfaction.", descriptionFr: "Suivre et ajuster vs satisfaction.", prerequisiteSkillIds: ["skill-align-expectations"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-communication-strategy", conceptId: "communication-planning", nameEn: "Design communication strategy", nameFr: "Concevoir la stratégie de communication", descriptionEn: "Choose content, frequency, channel, and technology for each stakeholder information need.", descriptionFr: "Choisir contenu, fréquence, canal et technologie selon le besoin d'information.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "communication" }),
  s({ id: "skill-tailor-communication", conceptId: "communication-planning", nameEn: "Tailor communication", nameFr: "Adapter la communication", descriptionEn: "Match interactive/push/pull mode to urgency, culture, confidentiality, and accessibility.", descriptionFr: "Adapter mode interactif/push/pull à l'urgence, la culture, la confidentialité et l'accessibilité.", prerequisiteSkillIds: ["skill-communication-strategy"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "communication" }),
  s({ id: "skill-promote-shared-vision", conceptId: "shared-vision", nameEn: "Promote shared vision", nameFr: "Promouvoir la vision partagée", descriptionEn: "Keep a current, understood picture of success among key stakeholders.", descriptionFr: "Maintenir une image du succès comprise et à jour chez les parties clés.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "leadership" }),
  s({ id: "skill-facilitate-shared-vision", conceptId: "shared-vision", nameEn: "Facilitate shared vision", nameFr: "Faciliter la vision partagée", descriptionEn: "Run alignment techniques when stakeholders disagree on success.", descriptionFr: "Animer des techniques d'alignement quand le succès est divergently compris.", prerequisiteSkillIds: ["skill-promote-shared-vision"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "leadership", sourceConfidence: "HIGH" }),
  s({ id: "skill-identify-conflict-source", conceptId: "conflict-management", nameEn: "Identify conflict source", nameFr: "Identifier la source du conflit", descriptionEn: "Find underlying disagreement drivers.", descriptionFr: "Trouver les drivers du désaccord.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "ANALYSIS", plaSkillSlug: "conflict-management" }),
  s({ id: "skill-select-conflict-response", conceptId: "conflict-management", nameEn: "Select conflict response", nameFr: "Choisir la réponse au conflit", descriptionEn: "Pick mode appropriate to context.", descriptionFr: "Choisir le mode adapté au contexte.", prerequisiteSkillIds: ["skill-identify-conflict-source"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "conflict-management" }),
  s({ id: "skill-facilitate-resolution", conceptId: "conflict-management", nameEn: "Facilitate resolution", nameFr: "Faciliter la résolution", descriptionEn: "Guide parties to agreed path.", descriptionFr: "Guider vers une voie convenue.", prerequisiteSkillIds: ["skill-select-conflict-response"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT" }),
  s({ id: "skill-distinguish-conflict-issue", conceptId: "conflict-vs-issue", nameEn: "Distinguish conflict from issue", nameFr: "Distinguer conflit et point à traiter", descriptionEn: "Interpersonal vs logged problem.", descriptionFr: "Interpersonnel vs problème consigné.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "pmp-situational-thinking" }),
  s({ id: "skill-distinguish-root-cause-symptom", conceptId: "root-cause-vs-symptom", nameEn: "Distinguish root cause from symptom", nameFr: "Distinguer cause profonde et symptôme", descriptionEn: "Address underlying cause first.", descriptionFr: "Traiter la cause profonde d'abord.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "ANALYSIS", plaSkillSlug: "pmp-situational-thinking" }),
  s({ id: "skill-set-team-expectations", conceptId: "team-leadership", nameEn: "Set team expectations", nameFr: "Fixer les attentes d'équipe", descriptionEn: "Clarify roles and norms.", descriptionFr: "Clarifier rôles et normes.", prerequisiteSkillIds: [], difficulty: "BEGINNER", cognitiveLevel: "APPLICATION", plaSkillSlug: "team-development" }),
  s({ id: "skill-empower-team", conceptId: "team-leadership", nameEn: "Empower the team", nameFr: "Responsabiliser l'équipe", descriptionEn: "Enable ownership within boundaries.", descriptionFr: "Permettre la propriété dans les limites.", prerequisiteSkillIds: ["skill-set-team-expectations"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "leadership" }),
  s({ id: "skill-select-leadership-style", conceptId: "team-leadership", nameEn: "Select leadership style", nameFr: "Choisir le style de leadership", descriptionEn: "Adapt style to situation.", descriptionFr: "Adapter le style à la situation.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "JUDGMENT", plaSkillSlug: "leadership" }),
  s({ id: "skill-coach-team", conceptId: "coaching-vs-directing", nameEn: "Coach vs direct appropriately", nameFr: "Coacher vs diriger", descriptionEn: "Develop vs instruct as needed.", descriptionFr: "Développer vs instruire selon le besoin.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "JUDGMENT" }),
  s({ id: "skill-enable-knowledge-transfer", conceptId: "knowledge-transfer", nameEn: "Enable knowledge transfer", nameFr: "Permettre le transfert de connaissances", descriptionEn: "Identify critical knowledge and organize transfer across individual, project, and organization levels.", descriptionFr: "Identifier les connaissances critiques et organiser le transfert aux niveaux individu, projet et organisation.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "pmp-people" }),
  s({ id: "skill-choose-knowledge-transfer-method", conceptId: "tacit-vs-explicit-knowledge", nameEn: "Choose knowledge transfer method", nameFr: "Choisir la méthode de transfert", descriptionEn: "Select interaction/coaching for tacit knowledge and documentation/repositories for explicit knowledge.", descriptionFr: "Choisir interaction/coaching pour le tacite et documentation/dépôts pour l'explicite.", prerequisiteSkillIds: ["skill-enable-knowledge-transfer"], difficulty: "INTERMEDIATE", cognitiveLevel: "JUDGMENT", plaSkillSlug: "pmp-people", sourceConfidence: "HIGH" }),
  s({ id: "skill-recommend-delivery-approach", conceptId: "integrated-planning", nameEn: "Recommend delivery approach", nameFr: "Recommander l'approche de livraison", descriptionEn: "Tailor predictive/agile/hybrid to context.", descriptionFr: "Adapter prédictif/agile/hybride au contexte.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "pmp-hybrid" }),
  s({ id: "skill-integrated-plan", conceptId: "integrated-planning", nameEn: "Build integrated plan", nameFr: "Construire le plan intégré", descriptionEn: "Consolidate subsidiary plans.", descriptionFr: "Consolider les plans subsidiaires.", prerequisiteSkillIds: ["skill-recommend-delivery-approach"], difficulty: "ADVANCED", cognitiveLevel: "APPLICATION", plaSkillSlug: "pmp-process" }),
  s({ id: "skill-tailor-approach", conceptId: "tailoring", nameEn: "Tailor processes", nameFr: "Adapter les processus", descriptionEn: "Right-size governance and artifacts.", descriptionFr: "Dimensionner gouvernance et artefacts.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "JUDGMENT" }),
  s({ id: "skill-define-scope", conceptId: "scope-management", nameEn: "Define scope", nameFr: "Définir le périmètre", descriptionEn: "Establish boundaries and deliverables.", descriptionFr: "Établir limites et livrables.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-decompose-scope", conceptId: "scope-management", nameEn: "Decompose scope", nameFr: "Décomposer le périmètre", descriptionEn: "Break down into manageable components.", descriptionFr: "Décomposer en composants gérables.", prerequisiteSkillIds: ["skill-define-scope"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-prioritize-by-value", conceptId: "value-delivery", nameEn: "Prioritize by value", nameFr: "Prioriser par la valeur", descriptionEn: "Order work by stakeholder value.", descriptionFr: "Ordonner le travail par valeur.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "JUDGMENT", plaSkillSlug: "business-value" }),
  s({ id: "skill-track-benefits", conceptId: "value-delivery", nameEn: "Track benefits", nameFr: "Suivre les bénéfices", descriptionEn: "Measure value realization.", descriptionFr: "Mesurer la réalisation de valeur.", prerequisiteSkillIds: ["skill-prioritize-by-value"], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS", plaSkillSlug: "business-value" }),
  s({ id: "skill-plan-resources", conceptId: "resource-management", nameEn: "Plan resources", nameFr: "Planifier les ressources", descriptionEn: "Match capacity to work.", descriptionFr: "Aligner capacité et travail.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-optimize-resources", conceptId: "resource-management", nameEn: "Optimize resources", nameFr: "Optimiser les ressources", descriptionEn: "Balance availability and utilization.", descriptionFr: "Équilibrer disponibilité et utilisation.", prerequisiteSkillIds: ["skill-plan-resources"], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS" }),
  s({ id: "skill-select-contract-type", conceptId: "procurement", nameEn: "Select contract type", nameFr: "Choisir le type de contrat", descriptionEn: "Match contract to risk allocation.", descriptionFr: "Adapter le contrat au partage des risques.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "procurement" }),
  s({ id: "skill-manage-vendors", conceptId: "procurement", nameEn: "Manage vendors", nameFr: "Gérer les fournisseurs", descriptionEn: "Monitor vendor performance.", descriptionFr: "Suivre la performance fournisseur.", prerequisiteSkillIds: ["skill-select-contract-type"], difficulty: "ADVANCED", cognitiveLevel: "APPLICATION", plaSkillSlug: "procurement" }),
  s({ id: "skill-plan-budget", conceptId: "project-finance", nameEn: "Plan project budget", nameFr: "Planifier le budget", descriptionEn: "Estimate and baseline costs.", descriptionFr: "Estimer et référencer les coûts.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "APPLICATION", plaSkillSlug: "cost" }),
  s({ id: "skill-manage-reserves", conceptId: "project-finance", nameEn: "Manage reserves", nameFr: "Gérer les réserves", descriptionEn: "Use contingency appropriately.", descriptionFr: "Utiliser les réserves correctement.", prerequisiteSkillIds: ["skill-plan-budget"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "cost" }),
  s({ id: "skill-track-cost-variance", conceptId: "project-finance", nameEn: "Track cost variance", nameFr: "Suivre les écarts de coût", descriptionEn: "Compare actuals to baseline.", descriptionFr: "Comparer réel vs référence.", prerequisiteSkillIds: ["skill-plan-budget"], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS", plaSkillSlug: "cost" }),
  s({ id: "skill-interpret-evm", conceptId: "evm-metric-to-decision", nameEn: "Interpret EVM into decisions", nameFr: "Interpréter l'EVM en décisions", descriptionEn: "Turn PV/EV/AC and CPI/SPI into forecast and sponsor-ready options.", descriptionFr: "Transformer PV/EV/AC et CPI/SPI en prévision et options pour le sponsor.", prerequisiteSkillIds: ["skill-track-cost-variance"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "cost", sourceConfidence: "HIGH" }),
  s({ id: "skill-plan-quality", conceptId: "quality-management", nameEn: "Plan quality", nameFr: "Planifier la qualité", descriptionEn: "Define quality requirements and processes.", descriptionFr: "Définir exigences et processus qualité.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "quality" }),
  s({ id: "skill-distinguish-qa-qc", conceptId: "quality-vs-inspection", nameEn: "Distinguish QA from QC", nameFr: "Distinguer AQ et CQ", descriptionEn: "Prevention vs inspection focus.", descriptionFr: "Prévention vs inspection.", prerequisiteSkillIds: ["skill-plan-quality"], difficulty: "INTERMEDIATE", cognitiveLevel: "UNDERSTANDING", plaSkillSlug: "quality" }),
  s({ id: "skill-explain-cost-of-quality", conceptId: "quality-management", nameEn: "Explain cost of quality", nameFr: "Expliquer le coût de la qualité", descriptionEn: "Classify prevention/appraisal/failure costs.", descriptionFr: "Classer coûts prévention/appraisal/échec.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "UNDERSTANDING" }),
  s({ id: "skill-build-schedule", conceptId: "schedule-management", nameEn: "Build schedule", nameFr: "Construire l'échéancier", descriptionEn: "Sequence activities and milestones.", descriptionFr: "Séquencer activités et jalons.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "schedule" }),
  s({ id: "skill-estimate-work", conceptId: "effort-vs-duration", nameEn: "Estimate effort and duration", nameFr: "Estimer effort et durée", descriptionEn: "Separate person-effort from calendar time.", descriptionFr: "Séparer effort-personnes et temps calendaire.", prerequisiteSkillIds: [], difficulty: "BEGINNER", cognitiveLevel: "UNDERSTANDING", plaSkillSlug: "schedule" }),
  s({ id: "skill-analyze-schedule-variance", conceptId: "schedule-management", nameEn: "Analyze schedule variance", nameFr: "Analyser les écarts d'échéancier", descriptionEn: "Interpret slip and dependencies.", descriptionFr: "Interpréter retards et dépendances.", prerequisiteSkillIds: ["skill-build-schedule"], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS", plaSkillSlug: "schedule" }),
  s({ id: "skill-define-metrics", conceptId: "project-status", nameEn: "Define project metrics", nameFr: "Définir les métriques projet", descriptionEn: "Select meaningful KPIs.", descriptionFr: "Sélectionner des KPI pertinents.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-communicate-status", conceptId: "project-status", nameEn: "Communicate status", nameFr: "Communiquer l'état", descriptionEn: "Report progress vs forecast clearly.", descriptionFr: "Rapporter progrès vs prévision.", prerequisiteSkillIds: ["skill-define-metrics"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-close-project", conceptId: "project-closure", nameEn: "Close project", nameFr: "Clore le projet", descriptionEn: "Obtain acceptance and close contracts.", descriptionFr: "Obtenir acceptation et clore contrats.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-transition-operations", conceptId: "project-closure", nameEn: "Transition to operations", nameFr: "Transition vers opérations", descriptionEn: "Validate readiness for handover.", descriptionFr: "Valider la préparation au transfert.", prerequisiteSkillIds: ["skill-close-project"], difficulty: "ADVANCED", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-establish-governance", conceptId: "governance", nameEn: "Establish governance", nameFr: "Établir la gouvernance", descriptionEn: "Define decision rights and escalation.", descriptionFr: "Définir droits de décision et escalade.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "governance" }),
  s({ id: "skill-define-success-metrics", conceptId: "governance", nameEn: "Define success metrics", nameFr: "Définir les métriques de réussite", descriptionEn: "Align metrics to value.", descriptionFr: "Aligner métriques et valeur.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "governance" }),
  s({ id: "skill-assess-compliance", conceptId: "compliance", nameEn: "Assess compliance", nameFr: "Évaluer la conformité", descriptionEn: "Identify regulatory requirements.", descriptionFr: "Identifier exigences réglementaires.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS" }),
  s({ id: "skill-mitigate-noncompliance", conceptId: "compliance", nameEn: "Mitigate noncompliance", nameFr: "Atténuer la non-conformité", descriptionEn: "Respond to compliance threats.", descriptionFr: "Répondre aux menaces de conformité.", prerequisiteSkillIds: ["skill-assess-compliance"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT" }),
  s({ id: "skill-evaluate-change", conceptId: "change-control", nameEn: "Evaluate change requests", nameFr: "Évaluer les demandes de changement", descriptionEn: "Analyze impact before approval.", descriptionFr: "Analyser l'impact avant approbation.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "ANALYSIS", plaSkillSlug: "change-management" }),
  s({ id: "skill-implement-approved-change", conceptId: "change-control", nameEn: "Implement approved changes", nameFr: "Mettre en œuvre les changements approuvés", descriptionEn: "Update docs after approval only.", descriptionFr: "Mettre à jour docs après approbation seulement.", prerequisiteSkillIds: ["skill-evaluate-change"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION", plaSkillSlug: "change-management" }),
  s({ id: "skill-prioritize-impediments", conceptId: "issue-management", nameEn: "Prioritize impediments", nameFr: "Prioriser les obstacles", descriptionEn: "Focus on highest impact blockers.", descriptionFr: "Cibler les blocages à fort impact.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "JUDGMENT", plaSkillSlug: "pmp-situational-thinking" }),
  s({ id: "skill-resolve-issues", conceptId: "issue-management", nameEn: "Resolve issues", nameFr: "Résoudre les points à traiter", descriptionEn: "Take corrective action on logged issues.", descriptionFr: "Agir sur les points consignés.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-identify-risks", conceptId: "risk-management", nameEn: "Identify risks", nameFr: "Identifier les risques", descriptionEn: "Surface future uncertainties.", descriptionFr: "Faire émerger les incertitudes futures.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "RECOGNITION", plaSkillSlug: "risk-management" }),
  s({ id: "skill-analyze-risks", conceptId: "risk-management", nameEn: "Analyze risks", nameFr: "Analyser les risques", descriptionEn: "Assess probability and impact.", descriptionFr: "Évaluer probabilité et impact.", prerequisiteSkillIds: ["skill-identify-risks"], difficulty: "INTERMEDIATE", cognitiveLevel: "ANALYSIS", plaSkillSlug: "risk-management" }),
  s({ id: "skill-respond-risks", conceptId: "risk-management", nameEn: "Respond to risks", nameFr: "Répondre aux risques", descriptionEn: "Select and execute risk responses.", descriptionFr: "Choisir et exécuter les réponses.", prerequisiteSkillIds: ["skill-analyze-risks"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "risk-management" }),
  s({ id: "skill-distinguish-risk-issue", conceptId: "risk-vs-issue", nameEn: "Distinguish risk from issue", nameFr: "Distinguer risque et point à traiter", descriptionEn: "Future uncertainty vs present problem.", descriptionFr: "Incertitude future vs problème présent.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "pmp-situational-thinking" }),
  s({ id: "skill-capture-lessons", conceptId: "continuous-improvement", nameEn: "Capture lessons learned", nameFr: "Capturer les leçons apprises", descriptionEn: "Document insights for reuse.", descriptionFr: "Documenter pour réutilisation.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-update-process-assets", conceptId: "continuous-improvement", nameEn: "Update process assets", nameFr: "Mettre à jour les actifs de processus", descriptionEn: "Improve organizational knowledge.", descriptionFr: "Améliorer les connaissances organisationnelles.", prerequisiteSkillIds: ["skill-capture-lessons"], difficulty: "INTERMEDIATE", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-assess-culture", conceptId: "organizational-change", nameEn: "Assess organizational culture", nameFr: "Évaluer la culture organisationnelle", descriptionEn: "Understand adoption context.", descriptionFr: "Comprendre le contexte d'adoption.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS" }),
  s({ id: "skill-support-adoption", conceptId: "organizational-change", nameEn: "Support adoption", nameFr: "Soutenir l'adoption", descriptionEn: "Enable org change for outcomes.", descriptionFr: "Permettre le changement org pour les résultats.", prerequisiteSkillIds: ["skill-assess-culture"], difficulty: "ADVANCED", cognitiveLevel: "APPLICATION" }),
  s({ id: "skill-scan-external-environment", conceptId: "external-environment", nameEn: "Scan external environment", nameFr: "Analyser l'environnement externe", descriptionEn: "Monitor market/regulatory shifts.", descriptionFr: "Surveiller marché/réglementation.", prerequisiteSkillIds: [], difficulty: "ADVANCED", cognitiveLevel: "ANALYSIS" }),
  s({ id: "skill-reprioritize-backlog", conceptId: "external-environment", nameEn: "Reprioritize backlog", nameFr: "Reprioriser le backlog", descriptionEn: "Adjust scope for external change.", descriptionFr: "Ajuster périmètre selon changements externes.", prerequisiteSkillIds: ["skill-scan-external-environment"], difficulty: "ADVANCED", cognitiveLevel: "JUDGMENT", plaSkillSlug: "business-value" }),
  s({ id: "skill-distinguish-requirement-expectation", conceptId: "requirements-management", nameEn: "Distinguish requirement from expectation", nameFr: "Distinguer exigence et attente", descriptionEn: "Documented need vs belief.", descriptionFr: "Besoin documenté vs croyance.", prerequisiteSkillIds: [], difficulty: "INTERMEDIATE", cognitiveLevel: "UNDERSTANDING" }),
];

const BY_ID = new Map(MASTERY_SKILLS.map((sk) => [sk.id, sk] as const));

export function getMasterySkill(id: string): MasterySkillRecord | undefined {
  return BY_ID.get(id);
}

export function skillsForConcept(conceptId: string): MasterySkillRecord[] {
  return MASTERY_SKILLS.filter((s) => s.conceptId === conceptId);
}

export const MASTERY_SKILL_COUNT = MASTERY_SKILLS.length;

export function mapLearningObjectiveToCognitive(
  objective: "IDENTIFY" | "APPLY" | "ANALYZE" | "DECIDE"
): CognitiveLevel {
  switch (objective) {
    case "IDENTIFY":
      return "RECOGNITION";
    case "APPLY":
      return "APPLICATION";
    case "ANALYZE":
      return "ANALYSIS";
    case "DECIDE":
      return "JUDGMENT";
    default:
      return "APPLICATION";
  }
}
