/**
 * Commonly confused concept pairs & misconception records.
 */

import type { MisconceptionRecord } from "./types";

function m(
  partial: Omit<MisconceptionRecord, "sourceType" | "sourceConfidence">
): MisconceptionRecord {
  return {
    ...partial,
    sourceType: "DERIVED_PEDAGOGICAL",
    sourceConfidence: "HIGH",
  };
}

export const MISCONCEPTIONS: readonly MisconceptionRecord[] = [
  m({
    id: "mc-communication-engagement",
    nameEn: "Communication equals engagement",
    nameFr: "Communication = engagement",
    explanationEn: "Sending updates is not the same as improving stakeholder commitment.",
    explanationFr: "Envoyer des mises à jour n'améliore pas automatiquement l'engagement.",
    confusionType: "terminology",
    conceptAId: "communication-planning",
    conceptBId: "stakeholder-engagement",
    affectedSkillIds: ["skill-distinguish-communication-engagement"],
    ecoTaskIds: ["PEOPLE-T04", "PEOPLE-T08"],
    errorKinds: ["misconception", "stakeholder-confusion"],
  }),
  m({
    id: "mc-expectation-requirement",
    nameEn: "Expectation equals requirement",
    nameFr: "Attente = exigence",
    explanationEn: "Stakeholder beliefs may differ from documented requirements.",
    explanationFr: "Les attentes peuvent différer des exigences documentées.",
    confusionType: "terminology",
    conceptAId: "expectation-alignment",
    conceptBId: "requirements-management",
    affectedSkillIds: ["skill-distinguish-requirement-expectation"],
    ecoTaskIds: ["PEOPLE-T05", "PROCESS-T02"],
    errorKinds: ["conceptual-gap", "stakeholder-confusion"],
  }),
  m({
    id: "mc-conflict-issue",
    nameEn: "Conflict equals issue",
    nameFr: "Conflit = point à traiter",
    explanationEn: "Interpersonal tension differs from a logged issue requiring resolution.",
    explanationFr: "Tension interpersonnelle ≠ point consigné à résoudre.",
    confusionType: "process-vs-event",
    conceptAId: "conflict-management",
    conceptBId: "issue-management",
    affectedSkillIds: ["skill-distinguish-conflict-issue"],
    ecoTaskIds: ["PEOPLE-T02", "BUSINESS-T04"],
    errorKinds: ["misconception", "stakeholder-confusion"],
  }),
  m({
    id: "mc-risk-issue",
    nameEn: "Risk equals issue",
    nameFr: "Risque = point à traiter",
    explanationEn: "Future uncertainty is not the same as a problem that already occurred.",
    explanationFr: "Incertitude future ≠ problème déjà survenu.",
    confusionType: "process-vs-event",
    conceptAId: "risk-management",
    conceptBId: "issue-management",
    affectedSkillIds: ["skill-distinguish-risk-issue"],
    ecoTaskIds: ["BUSINESS-T04", "BUSINESS-T05"],
    errorKinds: ["risk-confusion", "misconception"],
  }),
  m({
    id: "mc-impediment-issue",
    nameEn: "Impediment equals issue",
    nameFr: "Obstacle = point à traiter",
    explanationEn: "Operational blockers may or may not become formal issues.",
    explanationFr: "Blocage opérationnel ≠ toujours un point formel.",
    confusionType: "process-vs-event",
    conceptAId: "issue-management",
    conceptBId: "impediment-vs-issue",
    affectedSkillIds: ["skill-prioritize-impediments"],
    ecoTaskIds: ["BUSINESS-T04"],
    errorKinds: ["application-error"],
  }),
  m({
    id: "mc-governance-pm",
    nameEn: "Governance equals project management",
    nameFr: "Gouvernance = management de projet",
    explanationEn: "Oversight forums differ from day-to-day delivery leadership.",
    explanationFr: "Supervision ≠ direction opérationnelle quotidienne.",
    confusionType: "role-vs-activity",
    conceptAId: "governance",
    conceptBId: "integrated-planning",
    affectedSkillIds: ["skill-establish-governance"],
    ecoTaskIds: ["BUSINESS-T01", "PROCESS-T01"],
    errorKinds: ["conceptual-gap"],
  }),
  m({
    id: "mc-leadership-authority",
    nameEn: "Leadership equals authority",
    nameFr: "Leadership = autorité",
    explanationEn: "Influence without positional power is still leadership.",
    explanationFr: "Influencer sans pouvoir formel reste du leadership.",
    confusionType: "role-vs-activity",
    conceptAId: "team-leadership",
    conceptBId: "leadership-vs-authority",
    affectedSkillIds: ["skill-select-leadership-style"],
    ecoTaskIds: ["PEOPLE-T03"],
    errorKinds: ["misconception"],
  }),
  m({
    id: "mc-coaching-directing",
    nameEn: "Coaching equals directing",
    nameFr: "Coaching = direction",
    explanationEn: "Developing capability differs from giving orders.",
    explanationFr: "Développer ≠ donner des ordres.",
    confusionType: "role-vs-activity",
    conceptAId: "coaching-vs-directing",
    conceptBId: "team-leadership",
    affectedSkillIds: ["skill-coach-team"],
    ecoTaskIds: ["PEOPLE-T03"],
    errorKinds: ["application-error"],
  }),
  m({
    id: "mc-empowerment-delegation",
    nameEn: "Empowerment equals delegation",
    nameFr: "Autonomisation = délégation",
    explanationEn: "Shared ownership differs from task assignment.",
    explanationFr: "Propriété partagée ≠ simple délégation.",
    confusionType: "terminology",
    conceptAId: "empowerment-vs-delegation",
    conceptBId: "team-leadership",
    affectedSkillIds: ["skill-empower-team"],
    ecoTaskIds: ["PEOPLE-T03"],
    errorKinds: ["misconception"],
  }),
  m({
    id: "mc-quality-inspection",
    nameEn: "Quality management equals inspection",
    nameFr: "Gestion qualité = inspection",
    explanationEn: "Building quality in differs from detecting defects after delivery.",
    explanationFr: "Construire la qualité ≠ inspecter après coup.",
    confusionType: "process-vs-event",
    conceptAId: "quality-management",
    conceptBId: "quality-vs-inspection",
    affectedSkillIds: ["skill-distinguish-qa-qc"],
    ecoTaskIds: ["PROCESS-T07"],
    errorKinds: ["misconception"],
  }),
  m({
    id: "mc-prevention-appraisal",
    nameEn: "Prevention cost equals appraisal cost",
    nameFr: "Coût prévention = coût appraisal",
    explanationEn: "Preventing defects vs measuring quality are different cost categories.",
    explanationFr: "Prévenir ≠ mesurer — catégories de coût différentes.",
    confusionType: "terminology",
    conceptAId: "prevention-vs-appraisal-cost",
    conceptBId: "quality-management",
    affectedSkillIds: ["skill-explain-cost-of-quality"],
    ecoTaskIds: ["PROCESS-T07"],
    errorKinds: ["knowledge-recall"],
  }),
  m({
    id: "mc-failure-prevention",
    nameEn: "Failure cost equals prevention/appraisal",
    nameFr: "Coût d'échec = prévention/appraisal",
    explanationEn: "Internal/external failure costs differ from prevention and appraisal.",
    explanationFr: "Coûts d'échec ≠ prévention/appraisal.",
    confusionType: "terminology",
    conceptAId: "failure-cost-types",
    conceptBId: "prevention-vs-appraisal-cost",
    affectedSkillIds: ["skill-explain-cost-of-quality"],
    ecoTaskIds: ["PROCESS-T07"],
    errorKinds: ["knowledge-recall"],
  }),
  m({
    id: "mc-scope-change",
    nameEn: "Scope change equals change control",
    nameFr: "Changement de périmètre = maîtrise des changements",
    explanationEn: "Defining scope differs from governing how changes enter the baseline.",
    explanationFr: "Définir le périmètre ≠ gouverner les changements.",
    confusionType: "process-vs-event",
    conceptAId: "scope-management",
    conceptBId: "change-control",
    affectedSkillIds: ["skill-evaluate-change"],
    ecoTaskIds: ["PROCESS-T02", "BUSINESS-T03"],
    errorKinds: ["scope-confusion"],
  }),
  m({
    id: "mc-requested-approved",
    nameEn: "Requested change equals approved change",
    nameFr: "Changement demandé = approuvé",
    explanationEn: "A request is not authorization to implement.",
    explanationFr: "Demande ≠ autorisation de mise en œuvre.",
    confusionType: "process-vs-event",
    conceptAId: "requested-vs-approved-change",
    conceptBId: "change-control",
    affectedSkillIds: ["skill-implement-approved-change"],
    ecoTaskIds: ["BUSINESS-T03"],
    errorKinds: ["application-error", "scope-confusion"],
  }),
  m({
    id: "mc-predictive-adaptive",
    nameEn: "Predictive equals adaptive",
    nameFr: "Prédictif = adaptatif",
    explanationEn: "Approach choice depends on context — not interchangeable labels.",
    explanationFr: "Le choix dépend du contexte — pas interchangeable.",
    confusionType: "terminology",
    conceptAId: "predictive-vs-adaptive",
    conceptBId: "adaptive-vs-hybrid",
    affectedSkillIds: ["skill-recommend-delivery-approach"],
    ecoTaskIds: ["PROCESS-T01"],
    errorKinds: ["strategy-error"],
  }),
  m({
    id: "mc-adaptive-hybrid",
    nameEn: "Adaptive equals hybrid",
    nameFr: "Adaptatif = hybride",
    explanationEn: "Hybrid combines elements by context — not synonymous with agile.",
    explanationFr: "Hybride combine selon contexte — ≠ agile seul.",
    confusionType: "terminology",
    conceptAId: "adaptive-vs-hybrid",
    conceptBId: "predictive-vs-adaptive",
    affectedSkillIds: ["skill-recommend-delivery-approach"],
    ecoTaskIds: ["PROCESS-T01"],
    errorKinds: ["strategy-error", "application-error"],
  }),
  m({
    id: "mc-effort-duration",
    nameEn: "Effort equals duration",
    nameFr: "Effort = durée",
    explanationEn: "Person-hours differ from calendar elapsed time.",
    explanationFr: "Heures-personnes ≠ temps calendaire.",
    confusionType: "terminology",
    conceptAId: "effort-vs-duration",
    conceptBId: "schedule-management",
    affectedSkillIds: ["skill-estimate-work"],
    ecoTaskIds: ["PROCESS-T08"],
    errorKinds: ["knowledge-recall"],
  }),
  m({
    id: "mc-activity-milestone",
    nameEn: "Activity equals milestone",
    nameFr: "Activité = jalon",
    explanationEn: "Work packages have duration; milestones are checkpoints.",
    explanationFr: "Activités ont durée; jalons sont des points de contrôle.",
    confusionType: "terminology",
    conceptAId: "activity-vs-milestone",
    conceptBId: "schedule-management",
    affectedSkillIds: ["skill-build-schedule"],
    ecoTaskIds: ["PROCESS-T08"],
    errorKinds: ["knowledge-recall"],
  }),
  m({
    id: "mc-availability-utilization",
    nameEn: "Availability equals utilization",
    nameFr: "Disponibilité = utilisation",
    explanationEn: "Calendar capacity differs from assigned load.",
    explanationFr: "Capacité calendaire ≠ charge assignée.",
    confusionType: "terminology",
    conceptAId: "resource-availability-vs-utilization",
    conceptBId: "resource-management",
    affectedSkillIds: ["skill-optimize-resources"],
    ecoTaskIds: ["PROCESS-T04"],
    errorKinds: ["application-error"],
  }),
  m({
    id: "mc-output-outcome",
    nameEn: "Output equals outcome",
    nameFr: "Output = outcome",
    explanationEn: "Deliverable produced vs result experienced differ.",
    explanationFr: "Livrable produit ≠ résultat vécu.",
    confusionType: "output-vs-outcome",
    conceptAId: "output-vs-outcome",
    conceptBId: "value-delivery",
    affectedSkillIds: ["skill-track-benefits"],
    ecoTaskIds: ["PROCESS-T03"],
    errorKinds: ["conceptual-gap"],
  }),
  m({
    id: "mc-output-value",
    nameEn: "Output equals value",
    nameFr: "Output = valeur",
    explanationEn: "Shipping features does not guarantee stakeholder value.",
    explanationFr: "Livrer ≠ créer de la valeur.",
    confusionType: "output-vs-outcome",
    conceptAId: "output-vs-value",
    conceptBId: "value-delivery",
    affectedSkillIds: ["skill-prioritize-by-value"],
    ecoTaskIds: ["PROCESS-T03"],
    errorKinds: ["conceptual-gap", "strategy-error"],
  }),
  m({
    id: "mc-status-forecast",
    nameEn: "Status equals forecast",
    nameFr: "État = prévision",
    explanationEn: "Past performance reporting differs from future projection.",
    explanationFr: "Rapport passé ≠ projection future.",
    confusionType: "process-vs-event",
    conceptAId: "status-vs-forecast",
    conceptBId: "project-status",
    affectedSkillIds: ["skill-communicate-status"],
    ecoTaskIds: ["PROCESS-T09", "PROCESS-T06"],
    errorKinds: ["application-error"],
  }),
  m({
    id: "mc-reserve-budget",
    nameEn: "Reserve equals budget",
    nameFr: "Réserve = budget",
    explanationEn: "Contingency/management reserves are not the same as baseline budget.",
    explanationFr: "Réserves ≠ budget de référence.",
    confusionType: "terminology",
    conceptAId: "reserve-vs-budget",
    conceptBId: "project-finance",
    affectedSkillIds: ["skill-manage-reserves"],
    ecoTaskIds: ["PROCESS-T06"],
    errorKinds: ["knowledge-recall"],
  }),
  m({
    id: "mc-risk-response-issue",
    nameEn: "Risk response equals issue response",
    nameFr: "Réponse risque = réponse point à traiter",
    explanationEn: "Proactive uncertainty handling differs from reactive problem fixing.",
    explanationFr: "Proactif (risque) ≠ réactif (point à traiter).",
    confusionType: "process-vs-event",
    conceptAId: "risk-response-vs-issue-response",
    conceptBId: "risk-vs-issue",
    affectedSkillIds: ["skill-respond-risks", "skill-resolve-issues"],
    ecoTaskIds: ["BUSINESS-T04", "BUSINESS-T05"],
    errorKinds: ["risk-confusion"],
  }),
  m({
    id: "mc-collaboration-compromise",
    nameEn: "Collaboration equals compromise",
    nameFr: "Collaboration = compromis",
    explanationEn: "Win-win collaboration differs from split-the-difference compromise.",
    explanationFr: "Collaboration gagnant-gagnant ≠ compromis partagé.",
    confusionType: "terminology",
    conceptAId: "collaboration-vs-compromise",
    conceptBId: "conflict-management",
    affectedSkillIds: ["skill-select-conflict-response"],
    ecoTaskIds: ["PEOPLE-T02"],
    errorKinds: ["misconception"],
  }),
  m({
    id: "mc-root-cause-symptom",
    nameEn: "Symptom treated as root cause",
    nameFr: "Symptôme traité comme cause profonde",
    explanationEn: "Fixing visible effects may leave underlying cause intact.",
    explanationFr: "Corriger le symptôme peut laisser la cause intacte.",
    confusionType: "symptom-vs-cause",
    conceptAId: "root-cause-vs-symptom",
    conceptBId: "conflict-management",
    affectedSkillIds: ["skill-distinguish-root-cause-symptom"],
    ecoTaskIds: ["PEOPLE-T02", "BUSINESS-T04"],
    errorKinds: ["application-error", "strategy-error"],
  }),
  m({
    id: "mc-knowledge-transfer-communication",
    nameEn: "Knowledge transfer equals communication",
    nameFr: "Transfert de connaissances = communication",
    explanationEn:
      "Circulating information (T08) is not the same as transferring capability/know-how (T07).",
    explanationFr:
      "Faire circuler l'information (T08) n'équivaut pas à transférer savoir/capacité (T07).",
    confusionType: "terminology",
    conceptAId: "knowledge-transfer",
    conceptBId: "communication-planning",
    affectedSkillIds: [
      "skill-enable-knowledge-transfer",
      "skill-distinguish-communication-engagement",
    ],
    ecoTaskIds: ["PEOPLE-T07", "PEOPLE-T08"],
    errorKinds: ["misconception", "communication-error"],
  }),
  m({
    id: "mc-documenting-equals-transfer",
    nameEn: "Documenting equals knowledge transfer",
    nameFr: "Documenter = transfert de connaissances",
    explanationEn:
      "Tacit knowledge requires interaction, coaching, or observation — not documents alone.",
    explanationFr:
      "Le savoir tacite exige interaction, coaching ou observation — pas la seule documentation.",
    confusionType: "process-vs-event",
    conceptAId: "tacit-vs-explicit-knowledge",
    conceptBId: "knowledge-transfer",
    affectedSkillIds: ["skill-choose-knowledge-transfer-method"],
    ecoTaskIds: ["PEOPLE-T07"],
    errorKinds: ["misconception", "application-error"],
  }),
];

const BY_ID = new Map(MISCONCEPTIONS.map((x) => [x.id, x] as const));

export function getMisconception(id: string): MisconceptionRecord | undefined {
  return BY_ID.get(id);
}

export function misconceptionsForConcept(conceptId: string): MisconceptionRecord[] {
  return MISCONCEPTIONS.filter(
    (m) => m.conceptAId === conceptId || m.conceptBId === conceptId
  );
}

export const MISCONCEPTION_COUNT = MISCONCEPTIONS.length;

export function misconceptionsForEcoTask(
  taskId: MisconceptionRecord["ecoTaskIds"][number]
): MisconceptionRecord[] {
  return MISCONCEPTIONS.filter((m) => m.ecoTaskIds.includes(taskId));
}
